//
//  OracleSecurity.h
//  OracleSecurityLib
//
/*
 Copyright (c) 2011 Oracle.
 All rights reserved. 
 */

#import <Foundation/Foundation.h>
#import "OracleIdentityConnect.h"

/************************************************************************
 * Class: OracleSecurity
 *
 * Purpose: This class is the factory class for the Oracle Security 
 *   Provider.  Go to this class to get an instance of the currenly
 *   active Oracle Secrity Provider.  Interact with this class to 
 *   setup the type of provider to be generated by this class and 
 *   the paramters for that provider.
 *
 * 22 April 2011 (Created)
 ************************************************************************/
@interface OracleIdentity : NSObject 
{
}
// Gets an instance of the active security provider implementation
+ (id<OracleIdentityConnect>) getActiveIdentityConnect;
@end
