// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_cs extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "T\u0159\u00EDda %@ generovala chybu, kdy\u017E j\u00ED byla p\u0159id\u011Blena pam\u011B\u0165 a byla spu\u0161t\u011Bna - Bylo p\u0159eru\u0161eno p\u0159id\u00E1v\u00E1n\u00ED modulu Application Lifecycle Listener CHYBA: %@"},
    {"ADF-MF-16002", "Neplatn\u00E9 pou\u017Eit\u00ED"},
    {"ADF-MF-16003", "Tato funkce mus\u00ED b\u00FDt vol\u00E1na v hlavn\u00EDm vl\u00E1knu."},
    {"ADF-MF-16004", "Tato funkce NESM\u00CD b\u00FDt vol\u00E1na v hlavn\u00EDm vl\u00E1knu."},
    {"ADF-MF-16005", "Chybn\u00FD konfigura\u010Dn\u00ED soubor"},
    {"ADF-MF-16006", "Neplatn\u00E1 konfigurace"},
    {"ADF-MF-16007", "Implement\u00E1tor AdfmfContainerUtilities nen\u00ED konfigurov\u00E1n."},
    {"ADF-MF-16008", "T\u0159\u00EDda implement\u00E1toru AdfmfContainerUtilities nebyla nalezena."},
    {"ADF-MF-16009", "Nelze vytvo\u0159it implement\u00E1tor AdfmfContainerUtilities."},
    {"ADF-MF-16010", "Chybn\u00FD po\u017Eadavek"},
    {"ADF-MF-16011", "Soubor nelze st\u00E1hnout kv\u016Fli chyb\u011B 400 Chybn\u00FD po\u017Eadavek."},
    {"ADF-MF-16012", "Neautorizov\u00E1no"},
    {"ADF-MF-16013", "Soubor nelze st\u00E1hnout kv\u016Fli chyb\u011B 401 Neautorizov\u00E1no (nespr\u00E1vn\u00E9 u\u017Eivatelsk\u00E9 jm\u00E9no nebo heslo)."},
    {"ADF-MF-16014", "Zak\u00E1z\u00E1no"},
    {"ADF-MF-16015", "Soubor nelze st\u00E1hnout kv\u016Fli chyb\u011B 403 Zak\u00E1z\u00E1no."},
    {"ADF-MF-16016", "Nenalezeno"},
    {"ADF-MF-16017", "Soubor nelze st\u00E1hnout kv\u016Fli chyb\u011B 404 Nenalezeno."},
    {"ADF-MF-16018", "Chybn\u00E1 br\u00E1na"},
    {"ADF-MF-16019", "Soubor nelze st\u00E1hnout kv\u016Fli chyb\u011B 502 Chybn\u00E1 br\u00E1na."},
    {"ADF-MF-16020", "Slu\u017Eba nen\u00ED k dispozici"},
    {"ADF-MF-16021", "Soubor nelze st\u00E1hnout kv\u016Fli chyb\u011B 503 Slu\u017Eba nen\u00ED k dispozici."},
    {"ADF-MF-16022", "Neplatn\u00FD argument"},
    {"ADF-MF-16023", "Metod\u011B [oraADFLogger getLogger:] byl p\u0159ed\u00E1n pr\u00E1zdn\u00FD n\u00E1zev bal\u00ED\u010Dku."},
    {"ADF-MF-16024", "Chyba: Adresa URL souboru nem\u016F\u017Ee b\u00FDt nulov\u00E1"},
    {"ADF-MF-16025", "N\u00E1zev vlastnosti nem\u016F\u017Ee b\u00FDt nulov\u00FD."},
    {"ADF-MF-16026", "P\u0159\u00EDli\u0161 m\u00E1lo argument\u016F"},
    {"ADF-MF-16027", "Chyb\u00ED n\u00E1zev t\u0159\u00EDdy."},
    {"ADF-MF-16028", "Chyb\u00ED metoda."},
    {"ADF-MF-16029", "Chyb\u00ED ID funkce."},
    {"ADF-MF-16030", "Nerozpoznan\u00FD typ vol\u00E1n\u00ED"},
    {"ADF-MF-16031", "Objekt FeatureContext nebyl nalezen."},
    {"ADF-MF-16032", "Neo\u010Dek\u00E1van\u00E1 odpov\u011B\u010F"},
    {"ADF-MF-16033", "Odpov\u011B\u010F CVM vr\u00E1tila nulovou odpov\u011B\u010F. "},
    {"ADF-MF-16034", "Odpov\u011B\u010F CVM vr\u00E1tila nulov\u00FD objekt FeatureContextAccessor."},
    {"ADF-MF-16035", "Odpov\u011B\u010F JS vr\u00E1tila nulovou odpov\u011B\u010F"},
    {"ADF-MF-16036", "Nelze odeslat vol\u00E1n\u00ED JavaScript do kan\u00E1lu _Control_Channel_."},
    {"ADF-MF-16037", "Chyba vstupu/v\u00FDstupu"},
    {"ADF-MF-16038", "Do\u0161lo k chyb\u011B p\u0159i odeb\u00EDr\u00E1n\u00ED souboru."},
    {"ADF-MF-16039", "Chyba p\u0159i kop\u00EDrov\u00E1n\u00ED souboru."},
    {"ADF-MF-16040", "Chyb\u00ED o\u010Dek\u00E1van\u00FD soubor."},
    {"ADF-MF-16041", "P\u0159i p\u0159esouv\u00E1n\u00ED souboru do\u0161lo k chyb\u011B."},
    {"ADF-MF-16042", "Nelze vytvo\u0159it adres\u00E1\u0159."},
    {"ADF-MF-16043", "Chyba stahov\u00E1n\u00ED"},
    {"ADF-MF-16044", "P\u0159ipojen\u00ED nelze vytvo\u0159it"},
    {"ADF-MF-16045", "P\u0159i stahov\u00E1n\u00ED souboru do\u0161lo k neo\u010Dek\u00E1van\u00E9 chyb\u011B."},
    {"ADF-MF-16046", "Selh\u00E1n\u00ED p\u0159i ov\u011B\u0159en\u00ED"},
    {"ADF-MF-16047", "Nem\u00E1me \u017E\u00E1dn\u00E9 u\u017Eivatelsk\u00E9 jm\u00E9no ani heslo."},
    {"ADF-MF-16048", "Soubor nelze st\u00E1hnout kv\u016Fli selh\u00E1n\u00ED ov\u011B\u0159ov\u00E1n\u00ED."},
    {"ADF-MF-16049", "Neplatn\u00FD dokument kontejneru"},
    {"ADF-MF-16050", "Byl nalezen prvek \\'funkce\\' v dob\u011B, kdy prob\u00EDhalo zpracov\u00E1n\u00ED aktivn\u00EDho prvku \\'funkce\\'."},
    {"ADF-MF-16051", "ID funkce, \\'_Control_Channel_\\' je v konfliktu s vyhrazen\u00FDm n\u00E1zvem identifik\u00E1toru kan\u00E1lu VM"},
    {"ADF-MF-16052", "T\u0159\u00EDda \\'OracleAdfmfFeature\\' byla inicializov\u00E1na chybn\u00FDm typem prvku."},
    {"ADF-MF-16053", "Chybn\u00FD stav"},
    {"ADF-MF-16054", "Adresa URL souboru nem\u016F\u017Ee b\u00FDt nulov\u00E1"},
    {"ADF-MF-16055", "Do\u0161lo k pokusu o p\u0159id\u00E1n\u00ED objektu, kter\u00FD nebyl typu ASIHTTPRequest, do fronty ASINetworkQueue"},
    {"ADF-MF-16056", "Chyba p\u0159i vytv\u00E1\u0159en\u00ED kontaktu"},
    {"ADF-MF-16057", "Chyba p\u0159i odeb\u00EDr\u00E1n\u00ED kontaktu"},
    {"ADF-MF-16058", "Chyba typu Neplatn\u00FD argument"},
    {"ADF-MF-16059", "Chyba typu Vypr\u0161el \u010Dasov\u00FD limit"},
    {"ADF-MF-16060", "Chyba \u010Dekaj\u00EDc\u00ED operace"},
    {"ADF-MF-16061", "Chyba vstupu/v\u00FDstupu"},
    {"ADF-MF-16062", "Chyba typu Nepodporov\u00E1no"},
    {"ADF-MF-16063", "Chyba typu Opr\u00E1vn\u011Bn\u00ED odep\u0159eno"},
    {"ADF-MF-16064", "Nezn\u00E1m\u00E1 chyba"},
    {"ADF-MF-16066", "Neplatn\u00E1 t\u0159\u00EDda"},
    {"ADF-MF-16067", "Ve t\u0159\u00EDd\u011B chyb\u00ED implementace povinn\u00E9 funkce. Aktivujte lad\u011Bn\u00ED, aby byly informace o t\u0159\u00EDd\u011B protokolov\u00E1ny."},
    {"ADF-MF-16068", "T\u0159\u00EDda zobrazen\u00ED funkce nebyla nalezena."},
    {"ADF-MF-16069", "T\u0159\u00EDdu zobrazen\u00ED funkce nelze vytvo\u0159it."},
    {"ADF-MF-16070", "Poskytovatel zobrazen\u00ED poskytl nulov\u00E9 zobrazen\u00ED funkce."},
    {"ADF-MF-16071", "T\u0159\u00EDda nen\u00ED platn\u00E9ho typu zobrazen\u00ED. Aktu\u00E1ln\u011B podporovan\u00E1 podt\u0159\u00EDda mus\u00ED b\u00FDt odvozena ze t\u0159\u00EDd UIView nebo UIViewController"},
    {"ADF-MF-16072", "P\u0159ipojen\u00ED HttpURLConnection pou\u017Eit\u00E9 funkc\u00ED nebylo nalezeno."},
    {"ADF-MF-16073", "P\u0159ipojen\u00ED pou\u017Eit\u00E9 funkc\u00ED HttpURLConnection m\u00E1 nulovou adresu URL."},
    {"ADF-MF-16074", "Neplatn\u00E1 zpr\u00E1va"},
    {"ADF-MF-16075", "Ve zpr\u00E1v\u011B byl specifikov\u00E1n nezn\u00E1m\u00FD typ zpr\u00E1vy."},
    {"ADF-MF-16076", "Chyba p\u0159ihl\u00E1\u0161en\u00ED"},
    {"ADF-MF-16077", "Chyba konfigurace"},
    {"ADF-MF-16078", " Selh\u00E1n\u00ED p\u0159i na\u010D\u00EDt\u00E1n\u00ED funkce UIWebView"},
    {"ADF-MF-16079", " Na\u010D\u00EDt\u00E1n\u00ED funkce selhalo '%@' URL: %@"},
    {"ADF-MF-16080", "Obra\u0165te se na spr\u00E1vce."},
    {"ADF-MF-16081", "Server pro p\u0159ihl\u00E1\u0161en\u00ED nen\u00ED v dosahu."},
    {"ADF-MF-16082", "Neplatn\u00E9 u\u017Eivatelsk\u00E9 jm\u00E9no nebo heslo. Pokud probl\u00E9m potrv\u00E1, obra\u0165te se na spr\u00E1vce syst\u00E9mu."},
    {"ADF-MF-16083", "Chyba konfigurace. Obra\u0165te se na spr\u00E1vce. "},
    {"ADF-MF-16084", "Selh\u00E1n\u00ED ACS"},
    {"ADF-MF-16085", "Neplatn\u00E1 konfigurace ACS. U\u017Eivatelsk\u00FD objekt nebyl spr\u00E1vn\u011B na\u010Dten z d\u016Fvodu chyby konfigurace ACS. Obra\u0165te se na spr\u00E1vce."},
    {"ADF-MF-16086", "Server nen\u00ED dosa\u017Eiteln\u00FD. Ujist\u011Bte se, zda je za\u0159\u00EDzen\u00ED p\u0159ipojen\u00E9 k Internetu."},
    {"ADF-MF-16087", "U\u017Eivatelsk\u00E9 jm\u00E9no/heslo nen\u00ED platn\u00E9. Opakujte akci."},
    {"ADF-MF-16088", "Chyba konfigurace. Chyb\u00ED adresa URL slu\u017Eby \u0159\u00EDzen\u00ED p\u0159\u00EDstupu. Obra\u0165te se na spr\u00E1vce."},
    {"ADF-MF-16089", "P\u0159ekro\u010Dili jste maxim\u00E1ln\u00ED povolen\u00FD po\u010Det pokus\u016F o p\u0159ihl\u00E1\u0161en\u00ED. Jste zablokov\u00E1ni. Obra\u0165te se na spr\u00E1vce."},
    {"ADF-MF-16090", "Nelze prov\u00E9st zm\u011Bny kontroly konfigurace. Zkontrolujte s\u00ED\u0165ov\u00E9 p\u0159ipojen\u00ED nebo se obra\u0165te na spr\u00E1vce."},
    {"ADF-MF-16091", "Nelze aktualizovat konfigurace z konfigura\u010Dn\u00ED slu\u017Eby."},
    {"ADF-MF-16092", "Nespr\u00E1vn\u011B vytvo\u0159en\u00E1 zpr\u00E1va"},
    {"ADF-MF-16093", "Nen\u00ED povolena pr\u00E1zdn\u00E1 zpr\u00E1va s po\u017Eadavkem."},
    {"ADF-MF-16094", "Nepodporovan\u00E1 zpr\u00E1va"},
    {"ADF-MF-16095", "V tomto kan\u00E1lu nejsou syst\u00E9mov\u00E9 zpr\u00E1vy podporov\u00E1ny"},
    {"ADF-MF-16096", "Neplatn\u00FD syst\u00E9mov\u00FD po\u017Eadavek %@"},
    {"ADF-MF-16097", "V tomto kan\u00E1lu nejsou zpr\u00E1vy aplikace podporov\u00E1ny"},
    {"ADF-MF-16098", "Neplatn\u00FD po\u017Eadavek na aplikaci %@"},
    {"ADF-MF-16099", "Nezpracovan\u00E1 zpr\u00E1va"},
    {"ADF-MF-16100", "Nezpracovan\u00E1 zpr\u00E1va Adf - Referen\u010Dn\u00ED ID: %d Typ: %d T\u011Blo zpr\u00E1vy: %@"},
    {"ADF-MF-16101", "Byla p\u0159ijata nevy\u017E\u00E1dan\u00E1 zpr\u00E1va s odpov\u011Bd\u00ED"},
    {"ADF-MF-16102", "Byla p\u0159ijata zpr\u00E1va nezn\u00E1m\u00E9ho typu"},
    {"ADF-MF-16103", "AdfChannel.handle - Chyba p\u0159i zpracov\u00E1n\u00ED kan\u00E1lu VMChannel: %@ - ERROR: %@"},
    {"ADF-MF-16104", "Nen\u00ED zad\u00E1n '%@'. Vynechan\u00E1 chyba: '%@'"},
    {"ADF-MF-16105", "P\u0159\u00EDstup za\u0159\u00EDzen\u00ED deaktivov\u00E1n pro funkci '%@': adresa URL:%@, z\u00E1kladn\u00ED URL:%@, zpr\u00E1va:%@"},
    {"ADF-MF-16106", "Adresa URL nepovolena pro p\u0159\u00EDstup za\u0159\u00EDzen\u00ED k funkci '%@': adresa URL:%@, z\u00E1kladn\u00ED URL:%@, zpr\u00E1va:%@"},
    {"ADF-MF-16107", "CHYBA p\u0159i vytv\u00E1\u0159en\u00ED seznamu povolen\u00FDch polo\u017Eek: %@"},
    {"ADF-MF-16108", "Nelze odeslat aktualizovanou \u0161\u00ED\u0159ku/v\u00FD\u0161ku na stranu Java"},
    {"ADF-MF-16109", "Nen\u00ED mo\u017En\u00E9 prov\u00E9st registraci u ud\u00E1lost\u00ED zm\u011Bn statusu s\u00EDt\u011B. Status s\u00EDt\u011B bude nedostupn\u00FD"},
    {"ADF-MF-16110", "V\u00FDchoz\u00ED p\u0159ihla\u0161ovac\u00ED p\u0159ipojen\u00ED \\'%@\\' nen\u00ED definov\u00E1no."},
    {"ADF-MF-16111", "Ve skupin\u011B chyb\u00ED vzhled '%@'. Ignorov\u00E1no."},
    {"ADF-MF-16112", "Aktivn\u00ED skupina vzhled\u016F '%@' nevr\u00E1tila \u017E\u00E1dn\u00FD vzhled."},
    {"ADF-MF-16113", "P\u0159\u00EDloha %@ nebyla nalezena nebo ji nelze p\u0159e\u010D\u00EDst"},
    {"ADF-MF-16114", "%@ nepodporuje vlastnost deliverResponseJson:toCallbackSet: pro po\u017Eadavek:"},
    {"ADF-MF-16115", "%@ nen\u00ED ve webov\u00E9m zobrazen\u00ED definov\u00E1n. Vol\u00E1n\u00ED v\u00FDsledku JavaScript bylo p\u0159eru\u0161eno."},
    {"ADF-MF-16116", "Do\u0161lo k probl\u00E9mu p\u0159i vol\u00E1n\u00ED funkce '%@': %@"},
    {"ADF-MF-16117", "CHYBA: byla nalezena v\u00FDjimka p\u0159i prov\u00E1d\u011Bn\u00ED vol\u00E1n\u00ED %d: %@"},
    {"ADF-MF-16118", "Chyba ov\u011B\u0159ov\u00E1n\u00ED aplikace. D\u016Fvod = %@"},
    {"ADF-MF-16119", "Chyba ov\u011B\u0159ov\u00E1n\u00ED funkce. Funkce je zak\u00E1z\u00E1na. D\u016Fvod = %@"},
    {"ADF-MF-16120", "Chyba ov\u011B\u0159en\u00ED. Opakujte pokus."},
    {"ADF-MF-16121", "ACS vr\u00E1til chybu: %@"},
    {"ADF-MF-16122", "ACS nen\u00ED konfigurov\u00E1n pro p\u0159ipojen\u00ED %@. Objekty u\u017Eivatele nejsou zaregistrov\u00E1ny."},
    {"ADF-MF-16123", "P\u0159ihl\u00E1\u0161en\u00ED na \u00FArovni aplikace selhalo kv\u016Fli chyb\u011Bj\u00EDc\u00EDmu kontextu ov\u011B\u0159ov\u00E1n\u00ED."},
    {"ADF-MF-16124", "Soubor existuje v cest\u011B pam\u011Bti cache"},
    {"ADF-MF-16125", "Nelze vytvo\u0159it adres\u00E1\u0159 pro pam\u011B\u0165 cache v '%@', proto\u017Ee soubor ji\u017E existuje."},
    {"ADF-MF-16126", "Nepoda\u0159ilo se vytvo\u0159it adres\u00E1\u0159 pam\u011Bti cache."},
    {"ADF-MF-16127", "Nepoda\u0159ilo se vytvo\u0159it adres\u00E1\u0159 pro pam\u011B\u0165 cache v '%@'"},
    {"ADF-MF-16128", "Nepoda\u0159ilo se proj\u00EDt adres\u00E1\u0159 pam\u011Bti cache"},
    {"ADF-MF-16129", "Vytv\u00E1\u0159en\u00ED seznamu adres\u00E1\u0159e pam\u011Bti cache selhalo v cest\u011B '%@'"},
    {"ADF-MF-16130", "Selhalo odeb\u00EDr\u00E1n\u00ED souboru pam\u011Bti cache"},
    {"ADF-MF-16131", "Selhalo odeb\u00EDr\u00E1n\u00ED dat ulo\u017Een\u00FDch v pam\u011Bti cache v cest\u011B \\'%@\\'"},
    {"ADF-MF-16132", "Do\u0161lo k chyb\u011B, proto\u017Ee nebylo mo\u017En\u00E9 st\u00E1hnout konfiguraci."},
    {"ADF-MF-16133", "Zobrazen\u00ED funkce selhalo"},
    {"ADF-MF-16134", "Funkci nelze zobrazit. Pokus o zobrazen\u00ED funkce '%@' selhal.  CHYBA: %@"},
    {"ADF-MF-16135", "Chyba \u0159adi\u010De aplikace"},
    {"ADF-MF-16136", "Slo\u017Eka \u0159adi\u010De aplikace '%@' neexistuje."},
    {"ADF-MF-16137", "Nebylo mo\u017Eno na\u010D\u00EDst soubor .properties: %@ - CHYBA: %@"},
    {"ADF-MF-16138", "Chyba p\u0159i serializaci n\u00E1vratu: %@"},
    {"ADF-MF-16139", "ID vlastnosti nelze ur\u010Dit. P\u0159eru\u0161en\u00ED vol\u00E1n\u00ED do t\u0159\u00EDdy Java."},
    {"ADF-MF-16140", "Selhalo ov\u011B\u0159ov\u00E1n\u00ED kan\u00E1lu CVM."},
    {"ADF-MF-16141", "CVM vr\u00E1til neo\u010Dek\u00E1van\u00FD typ objektu: %@"},
    {"ADF-MF-16142", "Nelze odeslat zpr\u00E1vu"},
    {"ADF-MF-16143", "Textovou zpr\u00E1vu nelze odeslat, proto\u017Ee odes\u00EDl\u00E1n\u00ED textov\u00FDch zpr\u00E1v nen\u00ED v tomto za\u0159\u00EDzen\u00ED povoleno."},
    {"ADF-MF-16144", "Nelze odeslat zpr\u00E1vu, proto\u017Ee nelze z\u00EDskat editor textov\u00E9 zpr\u00E1vy."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - N\u00E1zev t\u0159\u00EDdy nebyl zad\u00E1n."},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - Vol\u00E1n\u00ED morphClassName zp\u016Fsobilo CHYBU: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - N\u00E1zev t\u0159\u00EDdy morphClassName selhal."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - Metoda nebyla zad\u00E1na."},
    {"ADF-MF-16149", "Nelze vytvo\u0159it t\u0159\u00EDdu: %@"},
    {"ADF-MF-16150", "Vol\u00E1n\u00ED New u typu objektu selhala: %@"},
    {"ADF-MF-16151", "Instance t\u0159\u00EDdy %@ neodpov\u00EDd\u00E1 selektoru '%@'."},
    {"ADF-MF-16152", "Vyvol\u00E1n\u00ED '%@' zp\u016Fsobilo chybu: %@"},
    {"ADF-MF-16153", "Serializace v\u00FDsledku z '%@' u typu %@ zp\u016Fsobila CHYBU: %@"},
    {"ADF-MF-16154", "Serializace v\u00FDsledku '%@' u typu %@ generovala nulu."},
    {"ADF-MF-16155", "credentialStoreKey pro p\u0159ipojen\u00ED %@ nem\u016F\u017Ee m\u00EDt hodnotu null."},
    {"ADF-MF-16156", "credentialStoreKey pro p\u0159ipojen\u00ED nem\u016F\u017Ee m\u00EDt hodnotu null."},
    {"ADF-MF-16157", "Do\u0161lo k obecn\u00E9 chyb\u011B p\u0159ihl\u00E1\u0161en\u00ED. U\u017Eivatel pravd\u011Bpodobn\u011B zadal nespr\u00E1vn\u00E9 ov\u011B\u0159ovac\u00ED \u00FAdaje, nebo konfigurace p\u0159ipojen\u00ED p\u0159ihl\u00E1\u0161en\u00ED m\u016F\u017Ee obsahovat chybu. Nap\u0159. m\u016F\u017Ee chyb\u011Bt adresa URL p\u0159ihl\u00E1\u0161en\u00ED nebo n\u00E1zev souboru cookie."},
    {"ADF-MF-16158", "Server nen\u00ED dostupn\u00FD. Ov\u011B\u0159te p\u0159ipojen\u00ED k internetu."},
    {"ADF-MF-16159", "Chyba v threadShellInitializationComplete: %@"},
    {"ADF-MF-16160", "Chyba v paintMirrorLoop: %@"},
    {"ADF-MF-16161", "ACS nen\u00ED konfigurov\u00E1no pro v\u00FDchoz\u00ED p\u0159ipojen\u00ED a omezen\u00E9 funkce nejsou dostupn\u00E9."},
    {"ADF-MF-16162", "Chyba v u\u017Eivatelsk\u00E9m jm\u00E9nu"},
    {"ADF-MF-16163", "U\u017Eivatelsk\u00E9 jm\u00E9no nebo pou\u017Eit\u00E9 jm\u00E9no z\u00E1kazn\u00EDka se li\u0161\u00ED od p\u016Fvodn\u00EDho u\u017Eivatelsk\u00E9ho jm\u00E9na anebo jm\u00E9na z\u00E1kazn\u00EDka. Pokud jste zadali chybn\u00E9 u\u017Eivatelsk\u00E9 jm\u00E9no nebo jm\u00E9no z\u00E1kazn\u00EDka, mus\u00EDte opravit u\u017Eivatelsk\u00E9 jm\u00E9no nebo jm\u00E9no z\u00E1kazn\u00EDka. Chcete-li se p\u0159ihl\u00E1sit jako nov\u00FD u\u017Eivatel, mus\u00EDte aplikaci nejd\u0159\u00EDve ukon\u010Dit."},
    {"ADF-MF-16164", "Chyb\u00ED n\u00E1zev z\u00E1hlav\u00ED v\u00EDce z\u00E1kazn\u00EDk\u016F"},
    {"ADF-MF-16165", "Nelze prov\u00E9st ov\u011B\u0159en\u00ED, proto\u017Ee v aplikaci v\u00EDce z\u00E1kazn\u00EDk\u016F nebyl pro ov\u011B\u0159en\u00ED poskytnut dostatek informac\u00ED. V konfiguraci chyb\u00ED n\u00E1zev z\u00E1hlav\u00ED v\u00EDce z\u00E1kazn\u00EDk\u016F. Obra\u0165te se na spr\u00E1vce."},
    {"ADF-MF-16166", "Nebylo zad\u00E1no jm\u00E9no z\u00E1kazn\u00EDka."},
    {"ADF-MF-16167", "Nelze prov\u00E9st ov\u011B\u0159en\u00ED, proto\u017Ee nebylo poskytnuto jm\u00E9no z\u00E1kazn\u00EDka. Opakujte pokus."},
    {"ADF-MF-16168", "Bude proveden pokus o p\u0159ihl\u00E1\u0161en\u00ED \u00FArovn\u011B aplikace. Server=%@ pro u\u017Eivatele=%@"},
    {"ADF-MF-16169", "P\u0159ihl\u00E1\u0161en\u00ED \u00FArovn\u011B aplikace prob\u011Bhlo \u00FAsp\u011B\u0161n\u011B."},
    {"ADF-MF-16170", "OMCredentialStore nevr\u00E1tilo vlastnost pro kSecAttrLabel."},
    {"ADF-MF-16171", "Objekty u\u017Eivatele aplikace jsou na\u010Dteny z \u00FAlo\u017Ei\u0161t\u011B ov\u011B\u0159ovac\u00EDch \u00FAdaj\u016F: %@"},
    {"ADF-MF-16172", "Test ov\u011B\u0159en\u00ED u\u017Eivatele vrac\u00ED %@."},
    {"ADF-MF-16173", "P\u0159ihl\u00E1\u0161en\u00ED na \u00FArovni vlastnosti selhalo z d\u016Fvodu neo\u010Dek\u00E1van\u00E9 podm\u00EDnky."},
    {"ADF-MF-16174", "Pokus o p\u0159ihl\u00E1\u0161en\u00ED na \u00FArovni vlastnosti pro u\u017Eivatele=%@."},
    {"ADF-MF-16175", "Pokus o odhl\u00E1\u0161en\u00ED na \u00FArovni vlastnosti."},
    {"ADF-MF-16176", "Objekty u\u017Eivatele jsou pr\u00E1v\u011B na\u010D\u00EDt\u00E1ny, proto\u017Ee se jedn\u00E1 o p\u0159ihl\u00E1\u0161en\u00ED vzd\u00E1len\u00E9 funkce."},
    {"ADF-MF-16177", "Ov\u011B\u0159ov\u00E1n\u00ED prob\u011Bhlo \u00FAsp\u011B\u0161n\u011B."},
    {"ADF-MF-16178", "vr\u00E1cen\u00E1 odpov\u011B\u010F objekt\u016F u\u017Eivatele=%@"},
    {"ADF-MF-16179", "vr\u00E1cen\u00E1 opr\u00E1vn\u011Bn\u00ED objekt\u016F u\u017Eivatele=%@ role=%@"},
    {"ADF-MF-16180", "Vyvol\u00E1n\u00ED ACS s p\u0159en\u00E1\u0161en\u00FDmi daty=%@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: authContext nebylo z\u00EDsk\u00E1no."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: pausedFeature nebylo z\u00EDsk\u00E1no."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: authContext nebylo z\u00EDsk\u00E1no."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: pausedFeature nebylo z\u00EDsk\u00E1no."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: authContext nebylo z\u00EDsk\u00E1no."},
    {"ADF-MF-16186", "Chyba konfigurace"},
    {"ADF-MF-16187", "P\u0159ipojen\u00ED pro p\u0159ihl\u00E1\u0161en\u00ED aplikace nen\u00ED definov\u00E1no. Aplikaci nelze spustit. Obra\u0165te se na spr\u00E1vce."},
    {"ADF-MF-16188", "P\u0159ipojen\u00ED pro p\u0159ihl\u00E1\u0161en\u00ED funkce nen\u00ED definov\u00E1no. K funkci nelze z\u00EDskat p\u0159\u00EDstup. Obra\u0165te se na spr\u00E1vce."},
    {"ADF-MF-16189", "Odhl\u00E1sit"},
    {"ADF-MF-16190", "Bylo zah\u00E1jeno odhla\u0161ov\u00E1n\u00ED. Aplikace bude ukon\u010Dena."},
    {"ADF-MF-16191", "Chyba konfigurace p\u0159ipojen\u00ED pro p\u0159ihl\u00E1\u0161en\u00ED. {0} Obra\u0165te se na spr\u00E1vce."},
    {"ADF-MF-16192", "Kl\u00ED\u010D \u00FAlo\u017Ei\u0161t\u011B ov\u011B\u0159ovac\u00EDch \u00FAdaj\u016F nen\u00ED ur\u010Den."},
    {"ADF-MF-16193", "Neplatn\u00E9 nebo chyb\u011Bj\u00EDc\u00ED u\u017Eivatelsk\u00E9 jm\u00E9no nebo heslo"},
    {"ADF-MF-16195", "Chyba kompozitn\u00EDho \u00FAlo\u017Ei\u0161t\u011B ov\u011B\u0159ovac\u00EDch \u00FAdaj\u016F"},
    {"ADF-MF-16196", "Neplatn\u00E1 adresa URL Slu\u017Eby \u0159\u00EDzen\u00ED p\u0159\u00EDstupu"},
    {"ADF-MF-16197", "Neplatn\u00E1 adresa URL odhl\u00E1\u0161en\u00ED"},
    {"ADF-MF-16198", "Neplatn\u00E1 adresa URL p\u0159ihl\u00E1\u0161en\u00ED"},
    {"ADF-MF-16199", "Soubor cookie nen\u00ED zad\u00E1n."},
    {"ADF-MF-16200", "\u010Casov\u00FD limit prodlevy mus\u00ED b\u00FDt 10 nebo vy\u0161\u0161\u00ED, \u010Dasov\u00FD limit relace mus\u00ED b\u00FDt 30 nebo vy\u0161\u0161\u00ED a vy\u0161\u0161\u00ED ne\u017E \u010Dasov\u00FD limit prodlevy."},
    {"ADF-MF-16201", "Chyba konfigurace p\u0159ipojen\u00ED pro p\u0159ihl\u00E1\u0161en\u00ED"},
    {"ADF-MF-16202", "Ov\u011B\u0159ovac\u00ED adresa URL odpov\u011Bd\u011Bla s neplatn\u00FDm k\u00F3dem HTTP odpov\u011Bdi. Nejedn\u00E1 se o z\u00E1kladn\u00ED koncov\u00FD bod ov\u011B\u0159en\u00ED. Obra\u0165te se na spr\u00E1vce."},
    {"ADF-MF-16203", "Soubor nebyl nalezen: %@"},
    {"ADF-MF-16204", "E-mailov\u00E1 zpr\u00E1va nebyla ulo\u017Eena nebo za\u0159azena do fronty, pravd\u011Bpodobn\u011B z d\u016Fvodu chyby."},
    {"ADF-MF-16205", "P\u0159i pokusu o ulo\u017Een\u00ED e-mailov\u00E9 zpr\u00E1vy do slo\u017Eky Koncepty do\u0161lo k chyb\u011B."},
    {"ADF-MF-16206", "P\u0159i pokusu o za\u0159azen\u00ED e-mailov\u00E9 zpr\u00E1vy do fronty nebo jej\u00ED odesl\u00E1n\u00ED do\u0161lo k chyb\u011B."},
    {"ADF-MF-16207", "P\u0159i pokusu o vytvo\u0159en\u00ED nebo odesl\u00E1n\u00ED e-mailu do\u0161lo k nezn\u00E1m\u00E9 chyb\u011B."},
    {"ADF-MF-16208", "P\u0159i pokusu o vytvo\u0159en\u00ED nebo odesl\u00E1n\u00ED textov\u00E9 zpr\u00E1vy do\u0161lo k nezn\u00E1m\u00E9 chyb\u011B."},
    {"ADF-MF-16209", "Soubor nebyl nalezen"},
    {"ADF-MF-16210", "Byla zji\u0161t\u011Bna neplatn\u00E1 p\u0159edpona pro mapov\u00E1n\u00ED identifik\u00E1toru URI. P\u0159edpona: %@ je ji\u017E namapov\u00E1na k identifik\u00E1toru URI: %@, opakovan\u00E9 mapov\u00E1n\u00ED p\u0159edpony k identifik\u00E1toru URI: %@ nen\u00ED povoleno."},
    {"ADF-MF-16211", "Byla zji\u0161t\u011Bna neplatn\u00E1 p\u0159edpona pro mapov\u00E1n\u00ED identifik\u00E1toru URI. URI: %@ je ji\u017E namapov\u00E1n k p\u0159edpon\u011B: %@, opakovan\u00E9 mapov\u00E1n\u00ED identifik\u00E1toru URI k p\u0159edpon\u011B: %@ nen\u00ED povoleno."},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
