// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_es extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "La clase %@ produjo un error al asignarse e iniciarse - ERROR al abortar la agregaci\u00F3n de listener de ciclo de vida de la aplicaci\u00F3n: %@"},
    {"ADF-MF-16002", "Uso no v\u00E1lido"},
    {"ADF-MF-16003", "Esta funci\u00F3n se debe llamar en el thread principal."},
    {"ADF-MF-16004", "Esta funci\u00F3n NO se debe llamar en el thread principal."},
    {"ADF-MF-16005", "Archivo de configuraci\u00F3n err\u00F3neo"},
    {"ADF-MF-16006", "Configuraci\u00F3n no v\u00E1lida"},
    {"ADF-MF-16007", "El implantador de AdfmfContainerUtilities no est\u00E1 configurado."},
    {"ADF-MF-16008", "No se ha encontrado la clase de implantador de AdfmfContainerUtilities."},
    {"ADF-MF-16009", "No se ha podido crear el implantador de AdfmfContainerUtilities."},
    {"ADF-MF-16010", "Solicitud Err\u00F3nea"},
    {"ADF-MF-16011", "El archivo no se ha podido descargar debido al error 400 - Solicitud Err\u00F3nea."},
    {"ADF-MF-16012", "No autorizado"},
    {"ADF-MF-16013", "El archivo no se ha podido descargar debido al error 401 - No Autorizado (nombre de usuario o contrase\u00F1a err\u00F3neos)."},
    {"ADF-MF-16014", "Prohibido"},
    {"ADF-MF-16015", "El archivo no se ha podido descargar debido al error 403 - Prohibido."},
    {"ADF-MF-16016", "No Encontrado"},
    {"ADF-MF-16017", "El archivo no se ha podido descargar debido al error 404 - No Encontrado."},
    {"ADF-MF-16018", "Gateway Err\u00F3neo"},
    {"ADF-MF-16019", "El archivo no se ha podido descargar debido al error 502 - Gateway Err\u00F3neo."},
    {"ADF-MF-16020", "Servicio no disponible"},
    {"ADF-MF-16021", "El archivo no se ha podido descargar debido al error 503 - Servicio no Disponible."},
    {"ADF-MF-16022", "Argumento no v\u00E1lido"},
    {"ADF-MF-16023", "Se ha transferido un nombre de paquete nulo a [oraADFLogger getLogger:]."},
    {"ADF-MF-16024", "La URL del archivo de error no puede ser nula"},
    {"ADF-MF-16025", "El nombre de propiedad no puede ser nula."},
    {"ADF-MF-16026", "Pocos argumentos."},
    {"ADF-MF-16027", "Falta el nombre de clase."},
    {"ADF-MF-16028", "Falta el m\u00E9todo."},
    {"ADF-MF-16029", "Falta el ID de funci\u00F3n."},
    {"ADF-MF-16030", "Tipo de llamada no reconocido"},
    {"ADF-MF-16031", "No se ha encontrado FeatureContext."},
    {"ADF-MF-16032", "Respuesta inesperada"},
    {"ADF-MF-16033", "La respuesta de CVM ha devuelto una respuesta nula. "},
    {"ADF-MF-16034", "La respuesta de CVM ha devuelto un FeatureContextAccessor nil."},
    {"ADF-MF-16035", "La respuesta de JS ha devuelto una respuesta nil."},
    {"ADF-MF-16036", "No se pueden enviar llamadas de JavaScript a _Control_Channel_."},
    {"ADF-MF-16037", "Error de E/S"},
    {"ADF-MF-16038", "Error al eliminar el archivo."},
    {"ADF-MF-16039", "Error al copiar el archivo."},
    {"ADF-MF-16040", "Falta el archivo esperado."},
    {"ADF-MF-16041", "Error al mover el archivo."},
    {"ADF-MF-16042", "No se ha podido crear el directorio."},
    {"ADF-MF-16043", "Error de Descarga"},
    {"ADF-MF-16044", "No se ha podido crear la conexi\u00F3n"},
    {"ADF-MF-16045", "Se ha producido un error inesperado al descargar el archivo."},
    {"ADF-MF-16046", "Fallo de Autenticaci\u00F3n"},
    {"ADF-MF-16047", "No disponemos de nombre de usuario o contrase\u00F1a."},
    {"ADF-MF-16048", "El archivo no se ha podido descargar debido a un fallo de autenticaci\u00F3n."},
    {"ADF-MF-16049", "Documento de contenedor no v\u00E1lido"},
    {"ADF-MF-16050", "Se ha encontrado el elemento de \\'funci\u00F3n\\' mientras se procesaba una \\'funci\u00F3n\\' activa."},
    {"ADF-MF-16051", "El ID de funci\u00F3n \\'_Control_Channel_\\' entra en conflicto con un nombre de identificador de canal VM reservado"},
    {"ADF-MF-16052", "La clase \\'OracleAdfmfFeature\\' se inici\u00F3 con un tipo de elemento err\u00F3neo."},
    {"ADF-MF-16053", "Estado err\u00F3neo"},
    {"ADF-MF-16054", "La URL del archivo no puede ser nula"},
    {"ADF-MF-16055", "Se ha intentado agregar un objeto que no era ASIHTTPRequest a ASINetworkQueue"},
    {"ADF-MF-16056", "Error al crear contacto"},
    {"ADF-MF-16057", "Error al eliminar contacto"},
    {"ADF-MF-16058", "Error de argumento no v\u00E1lido"},
    {"ADF-MF-16059", "Error de timeout"},
    {"ADF-MF-16060", "Error de operaci\u00F3n pendiente"},
    {"ADF-MF-16061", "Error de E/S"},
    {"ADF-MF-16062", "Error no soportado"},
    {"ADF-MF-16063", "Error de permiso denegado"},
    {"ADF-MF-16064", "Error desconocido"},
    {"ADF-MF-16066", "Clase no v\u00E1lida"},
    {"ADF-MF-16067", "A la clase le falta la implantaci\u00F3n de una funci\u00F3n necesaria. Active la depuraci\u00F3n para registrar informaci\u00F3n sobre la clase."},
    {"ADF-MF-16068", "No se ha encontrado la clase de vista de funci\u00F3n."},
    {"ADF-MF-16069", "No se ha podido crear la clase de vista de funci\u00F3n."},
    {"ADF-MF-16070", "El controlador de vista produjo una vista nula para la vista de funci\u00F3n."},
    {"ADF-MF-16071", "La clase no es un tipo de vista v\u00E1lido. Las subclases soportadas actualmente deben ser UIView o UIViewController"},
    {"ADF-MF-16072", "No se ha encontrado la HttpURLConnection usada por una funci\u00F3n."},
    {"ADF-MF-16073", "La HttpURLConnection usada por una funci\u00F3n tiene una URL nula."},
    {"ADF-MF-16074", "Mensaje no V\u00E1lido"},
    {"ADF-MF-16075", " Tipo de mensaje desconocido especificado por el mensaje."},
    {"ADF-MF-16076", "Error de Conexi\u00F3n"},
    {"ADF-MF-16077", "Error de configuraci\u00F3n"},
    {"ADF-MF-16078", " Fallo al cargar UIWebView"},
    {"ADF-MF-16079", " Fallo al cargar la funci\u00F3n \\'%@\\' URL: %@"},
    {"ADF-MF-16080", "P\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16081", "No se puede acceder al servidor de conexi\u00F3n."},
    {"ADF-MF-16082", "Nombre de usuario/contrase\u00F1a no v\u00E1lidos. Si el problema persiste, p\u00F3ngase en contacto con el administrador del sistema."},
    {"ADF-MF-16083", "Error de configuraci\u00F3n. P\u00F3ngase en contacto con el administrador. "},
    {"ADF-MF-16084", "Fallo de ACS"},
    {"ADF-MF-16085", "Configuraci\u00F3n de ACS no v\u00E1lida. El objeto de usuario no se ha recuperado correctamente debido a un error de configuraci\u00F3n de ACS. Puede que en usuario no se haya registrado en ACS. P\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16086", "No se puede acceder al servidor. Aseg\u00FArese de que el dispositivo est\u00E9 conectado a Internet."},
    {"ADF-MF-16087", "Nombre de usuario/contrase\u00F1a no v\u00E1lidos. Vuelva a intentarlo."},
    {"ADF-MF-16088", "Error de configuraci\u00F3n. Falta la URL del servicio de control de acceso. P\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16089", "Ha excedido el n\u00FAmero m\u00E1ximo de intentos de conexi\u00F3n permitido. El usuario se ha bloqueado. P\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16090", "No se ha podido realizar la comprobaci\u00F3n de los cambios de configuraci\u00F3n. Compruebe la conexi\u00F3n de red o p\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16091", "No se han podido actualizar las configuraciones del servicio de configuraci\u00F3n."},
    {"ADF-MF-16092", "Mensaje con formato incorrecto"},
    {"ADF-MF-16093", "No est\u00E1 permitido que el mensaje de solicitud est\u00E9 vac\u00EDo."},
    {"ADF-MF-16094", "Mensaje no soportado"},
    {"ADF-MF-16095", "Los mensajes del sistema no est\u00E1n soportados en este canal"},
    {"ADF-MF-16096", "Solicitud de sistema no v\u00E1lida %@"},
    {"ADF-MF-16097", "Los mensajes de aplicaci\u00F3n no est\u00E1n soportados en este canal"},
    {"ADF-MF-16098", "Solicitud de aplicaci\u00F3n no v\u00E1lida %@"},
    {"ADF-MF-16099", "Mensaje no tratado"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ID de referencia: %d Tipo: %d Cuerpo: %@"},
    {"ADF-MF-16101", "Se ha recibido un mensaje de respuesta no solicitado"},
    {"ADF-MF-16102", "Se ha recibido un tipo de mensaje desconocido"},
    {"ADF-MF-16103", "AdfChannel.handle - Error al manejar el mensaje de VMChannel: %@ - ERROR: %@"},
    {"ADF-MF-16104", "No se ha especificado '%@'. Error borrado: '%@'"},
    {"ADF-MF-16105", "Acceso al dispositivo desactivado para la funci\u00F3n \\'%@\\': url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16106", "La URL no ha permitido el acceso al dispositivo para la funci\u00F3n \\'%@\\': url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16107", "ERROR de lista blanca: %@"},
    {"ADF-MF-16108", "No se ha podido enviar el ancho y la altura actualizados a Java"},
    {"ADF-MF-16109", "No se han podido registrar los eventos de cambio de estado de red. El estado de red no estar\u00E1 disponible"},
    {"ADF-MF-16110", "No se ha definido la conexi\u00F3n por defecto '%@'."},
    {"ADF-MF-16111", "Falta una familia de la m\u00E1scara '%@'. Ignorada."},
    {"ADF-MF-16112", "La familia de m\u00E1scaras activa '%@' no ha devuelto ninguna m\u00E1scara."},
    {"ADF-MF-16113", "No se ha encontrado o no se puede leer el anexo %@"},
    {"ADF-MF-16114", "%@ no soporta deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "%@ no est\u00E1 definido en webview. Llamada de resultado JavaScript abortada."},
    {"ADF-MF-16116", "Se produjo un problema al llamar a la funci\u00F3n '%@': %@"},
    {"ADF-MF-16117", "ERROR: se ha encontrado una excepci\u00F3n al ejecutar la devoluci\u00F3n de llamada %d: %@"},
    {"ADF-MF-16118", "Error al autenticar la aplicaci\u00F3n. Motivo = %@"},
    {"ADF-MF-16119", "Error al autenticar la funci\u00F3n. Funci\u00F3n desactivada. Motivo = %@"},
    {"ADF-MF-16120", "Error de autenticaci\u00F3n. Vuelva a intentarlo."},
    {"ADF-MF-16121", "ACS ha devuelto el error: %@"},
    {"ADF-MF-16122", "ACS no se ha configurado para la conexi\u00F3n %@. Los objetos de usuario no est\u00E1n registrados."},
    {"ADF-MF-16123", "Fallo de conexi\u00F3n de nivel de aplicaci\u00F3n debido a la falta de contexto de autenticaci\u00F3n."},
    {"ADF-MF-16124", "El archivo existe en la ruta de acceso de cach\u00E9"},
    {"ADF-MF-16125", "No se ha podido crear un directorio para la cach\u00E9 en '%@', porque el archivo ya existe"},
    {"ADF-MF-16126", "Fallo al crear un directorio de cach\u00E9"},
    {"ADF-MF-16127", "Fallo al crear un directorio para cach\u00E9 en '%@'"},
    {"ADF-MF-16128", "Fallo al recorrer directorio de cach\u00E9"},
    {"ADF-MF-16129", "Fallo al mostrar el directorio de cach\u00E9 en la ruta de acceso '%@'"},
    {"ADF-MF-16130", "Fallo al eliminar archivo de cach\u00E9"},
    {"ADF-MF-16131", "Fallo al eliminar datos de cach\u00E9 en la ruta de acceso '%@'"},
    {"ADF-MF-16132", "Bloqueando ahora porque no se puede descargar la configuraci\u00F3n."},
    {"ADF-MF-16133", "Fallo al mostrar la funci\u00F3n"},
    {"ADF-MF-16134", "No se ha podido mostrar la funci\u00F3n. Fallo al intentar mostrar la funci\u00F3n '%@'. ERROR: %@"},
    {"ADF-MF-16135", "Error del controlador de aplicaci\u00F3n"},
    {"ADF-MF-16136", "La carpeta '%@' del controlador de la aplicaci\u00F3n no existe."},
    {"ADF-MF-16137", "No se puede cargar el archivo .properties: %@ - ERROR: %@"},
    {"ADF-MF-16138", "Error al serializar la devoluci\u00F3n: %@"},
    {"ADF-MF-16139", "El ID de funci\u00F3n no se ha podido determinar. Abortando la llamada a clase Java."},
    {"ADF-MF-16140", "Fallo al verificar el canal de CVM."},
    {"ADF-MF-16141", "CVM ha devuelto un tipo de objeto inesperado: %@"},
    {"ADF-MF-16142", "No se puede enviar el mensaje"},
    {"ADF-MF-16143", "No se ha podido enviar un mensaje porque los mensajes de texto no est\u00E1n disponibles en este dispositivo."},
    {"ADF-MF-16144", "No se ha podido enviar el mensaje porque no se ha podido obtener el creador de mensajes de texto."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - No se ha especificado 'classname'"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - La llamada a morphClassName ha producido un ERROR: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Fallo de 'classname' morphClassName."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - No se ha especificado 'method'"},
    {"ADF-MF-16149", "No se ha podido crear la clase: %@"},
    {"ADF-MF-16150", "Fallo de nuevo en tipo de objeto: %@"},
    {"ADF-MF-16151", "La instancia de la clase %@ no responde al selector '%@'."},
    {"ADF-MF-16152", "La llamada a '%@' ha producido un error: %@"},
    {"ADF-MF-16153", "El resultado de serializaci\u00F3n de '%@' en el tipo %@ ha producido ERROR: %@"},
    {"ADF-MF-16154", "El resultado de serializaci\u00F3n de '%@' en el tipo %@ ha generado un valor nil."},
    {"ADF-MF-16155", "credentialStoreKey para la conexi\u00F3n %@ no puede ser un valor nil"},
    {"ADF-MF-16156", "credentialStoreKey para la conexi\u00F3n no puede ser un valor nil"},
    {"ADF-MF-16157", "Se ha producido un error de conexi\u00F3n general. Puede que el usuario haya introducido credenciales no v\u00E1lidas o que la configuraci\u00F3n de la conexi\u00F3n contenga errores. Es decir, puede que falte la URL de conexi\u00F3n o el nombre de cookie o que sean incorrectos."},
    {"ADF-MF-16158", "No se puede acceder al servidor. Aseg\u00FArese de que est\u00E1 conectado a Internet."},
    {"ADF-MF-16159", "Error en threadShellInitializationComplete: %@"},
    {"ADF-MF-16160", "Error en paintMirrorLoop: %@"},
    {"ADF-MF-16161", "ACS no se ha configurado para la conexi\u00F3n por defecto y las funciones restringidas no est\u00E1n disponibles."},
    {"ADF-MF-16162", "Error en el nombre de usuario"},
    {"ADF-MF-16163", "El nombre de usuario o el nombre de contenido son distintos del nombre de usuario o del nombre de contenido originales. Debe corregir el nombre de usuario o de contenido si ha introducido otros incorrectos. Para conectarse como un nuevo usuario, debe salir antes de la aplicaci\u00F3n."},
    {"ADF-MF-16164", "Falta el nombre de cabecera de varios contenidos"},
    {"ADF-MF-16165", "No se puede autenticar porque no se ha proporcionado informaci\u00F3n suficiente para la autenticaci\u00F3n en la aplicaci\u00F3n de varios clientes. Falta el nombre de cabecera de varios clientes en la configuraci\u00F3n. P\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16166", "No se ha introducido el nombre del cliente"},
    {"ADF-MF-16167", "No se puede autenticar porque no se ha proporcionado el nombre de cliente. Vuelva a intentarlo."},
    {"ADF-MF-16168", "Se intentar\u00E1 la conexi\u00F3n de nivel de aplicaci\u00F3n. Servidor=%@ para el usuario=%@"},
    {"ADF-MF-16169", "Conexi\u00F3n de nivel de aplicaci\u00F3n correcta."},
    {"ADF-MF-16170", "OMCredentialStore no ha devuelto la propiedad para kSecAttrLabel."},
    {"ADF-MF-16171", "Los objetos de usuario de la aplicaci\u00F3n se recuperan del almac\u00E9n de credenciales: %@"},
    {"ADF-MF-16172", "La prueba de autenticaci\u00F3n del usuario devuelve %@"},
    {"ADF-MF-16173", "Fallo de conexi\u00F3n de nivel de funci\u00F3n debido a una condici\u00F3n inesperada."},
    {"ADF-MF-16174", "Intento de conexi\u00F3n de nivel de funci\u00F3n para el usuario=%@."},
    {"ADF-MF-16175", "Intento de desconexi\u00F3n de nivel de funci\u00F3n."},
    {"ADF-MF-16176", "Los objetos de usuario se est\u00E1n extrayendo porque se trata de una conexi\u00F3n de funci\u00F3n remota."},
    {"ADF-MF-16177", "Autenticaci\u00F3n correcta."},
    {"ADF-MF-16178", "respuesta de los objetos de usuario devueltos=%@"},
    {"ADF-MF-16179", "privilegios de los objetos de usuario devueltos=%@ roles=%@"},
    {"ADF-MF-16180", "Llamando a ACS con carga \u00FAtil=%@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: no se ha obtenido authContext."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: no se ha obtenido pausedFeature."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: no se ha obtenido authContext."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: no se ha obtenido pausedFeature."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: no se ha obtenido authContext."},
    {"ADF-MF-16186", "Error de Configuraci\u00F3n"},
    {"ADF-MF-16187", "No se ha definido la conexi\u00F3n de la aplicaci\u00F3n. Esta aplicaci\u00F3n no se puede ejecutar. P\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16188", "No se ha definido la conexi\u00F3n de la funci\u00F3n. No se puede acceder a esta funci\u00F3n. P\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16189", "Desconexi\u00F3n"},
    {"ADF-MF-16190", "Se ha iniciado la desconexi\u00F3n. La aplicaci\u00F3n terminar\u00E1."},
    {"ADF-MF-16191", "Error de configuraci\u00F3n de conexi\u00F3n de inicio de sesi\u00F3n. {0} P\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16192", "No se ha especificado la clave de almac\u00E9n de credenciales."},
    {"ADF-MF-16193", "Falta el nombre de usuario y/o la contrase\u00F1a o no son v\u00E1lidos."},
    {"ADF-MF-16195", "Error al componer la clave del almac\u00E9n de credenciales."},
    {"ADF-MF-16196", "URL de servicio de control de acceso no v\u00E1lida."},
    {"ADF-MF-16197", "URL de desconexi\u00F3n no v\u00E1lida."},
    {"ADF-MF-16198", "URL de inicio de sesi\u00F3n no v\u00E1lida."},
    {"ADF-MF-16199", "No se ha especificado ninguna cookie."},
    {"ADF-MF-16200", "El valor de timeout de inactividad debe ser 10 como m\u00EDnimo; el valor de timeout de sesi\u00F3n debe ser 30 como m\u00EDnimo y ser mayor que el valor de timeout de inactividad."},
    {"ADF-MF-16201", "Error de configuraci\u00F3n de conexi\u00F3n de inicio de sesi\u00F3n."},
    {"ADF-MF-16202", "La URL de autenticaci\u00F3n ha respondido con un c\u00F3digo de respuesta HTTP no v\u00E1lido. No es un punto final de autenticaci\u00F3n b\u00E1sica. P\u00F3ngase en contacto con el administrador."},
    {"ADF-MF-16203", "No se ha encontrado el archivo: %@"},
    {"ADF-MF-16204", "El mensaje de correo electr\u00F3nico no se ha guardado ni puesto en cola, probablemente debido a un error."},
    {"ADF-MF-16205", "Se ha producido un error al intentar guardar el mensaje de correo electr\u00F3nico en la carpeta Borradores."},
    {"ADF-MF-16206", "Se ha producido un error al intentar poner en cola o enviar el mensaje de correo electr\u00F3nico."},
    {"ADF-MF-16207", "Se ha producido un error desconocido al intentar redactar o enviar un mensaje de correo electr\u00F3nico."},
    {"ADF-MF-16208", "Se ha producido un error desconocido al intentar redactar o enviar un mensaje de texto."},
    {"ADF-MF-16209", "Archivo no encontrado"},
    {"ADF-MF-16210", "Se ha encontrado un prefijo no v\u00E1lido en la asignaci\u00F3n de URI. El prefijo: %@ ya se ha asignado al URI: %@ y no se puede volver a asignar el prefijo al URI: %@"},
    {"ADF-MF-16211", "Se ha encontrado un prefijo no v\u00E1lido en la asignaci\u00F3n de URI. El URI: %@ ya se ha asignado al prefijo: %@ y no se puede volver a asignar el URI al prefijo: %@"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
