// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_fi extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "Luokka %@ loi virheen, kun se varattiin ja alustettiin - keskeytet\u00E4\u00E4n sovelluksen elinkaarikuuntelijan lis\u00E4ys, VIRHE: %@"},
    {"ADF-MF-16002", "Virheellinen k\u00E4ytt\u00F6"},
    {"ADF-MF-16003", "T\u00E4t\u00E4 funktiota on kutsuttava p\u00E4\u00E4s\u00E4ikeess\u00E4."},
    {"ADF-MF-16004", "T\u00E4t\u00E4 funktiota EI saa kutsua p\u00E4\u00E4s\u00E4ikeess\u00E4."},
    {"ADF-MF-16005", "Virheellinen kokoonpanotiedosto"},
    {"ADF-MF-16006", "Virheellinen kokoonpano"},
    {"ADF-MF-16007", "AdfmfContainerUtilities-implementoijaa ei m\u00E4\u00E4ritetty."},
    {"ADF-MF-16008", "AdfmfContainerUtilities-implementoijan luokkaa ei l\u00F6ytynyt."},
    {"ADF-MF-16009", "AdfmfContainerUtilities-implementoijaa ei voitu luoda."},
    {"ADF-MF-16010", "Virheellinen pyynt\u00F6"},
    {"ADF-MF-16011", "Tiedostoa ei voi noutaa, syy: 400: virheellinen pyynt\u00F6."},
    {"ADF-MF-16012", "Ei valtuuksia"},
    {"ADF-MF-16013", "Tiedostoa ei voi noutaa, syy: 401: ei valtuuksia (v\u00E4\u00E4r\u00E4 k\u00E4ytt\u00E4j\u00E4tunnus tai salasana)."},
    {"ADF-MF-16014", "Kielletty"},
    {"ADF-MF-16015", "Tiedostoa ei voi noutaa, syy: 403: kielletty."},
    {"ADF-MF-16016", "Ei l\u00F6ydy"},
    {"ADF-MF-16017", "Tiedostoa ei voi noutaa, syy: 404: ei l\u00F6ydy."},
    {"ADF-MF-16018", "Virheellinen yhdysk\u00E4yt\u00E4v\u00E4"},
    {"ADF-MF-16019", "Tiedostoa ei voi noutaa, syy: 502: virheellinen yhdysk\u00E4yt\u00E4v\u00E4."},
    {"ADF-MF-16020", "Palvelu ei ole k\u00E4ytett\u00E4viss\u00E4"},
    {"ADF-MF-16021", "Tiedostoa ei voi noutaa, syy: 503: palvelu ei ole k\u00E4ytett\u00E4viss\u00E4."},
    {"ADF-MF-16022", "Argumentti ei kelpaa"},
    {"ADF-MF-16023", "Tyhj\u00E4 paketin nimi v\u00E4litettiin kohteeseen [oraADFLogger getLogger:]."},
    {"ADF-MF-16024", "Virhetiedoston URL ei voi olla tyhj\u00E4"},
    {"ADF-MF-16025", "Ominaisuuden nimi ei voi olla tyhj\u00E4."},
    {"ADF-MF-16026", "Liian v\u00E4h\u00E4n argumentteja."},
    {"ADF-MF-16027", "Puuttuva luokkanimi."},
    {"ADF-MF-16028", "Puuttuva menetelm\u00E4."},
    {"ADF-MF-16029", "Ominaisuuden tunnus puuttuu."},
    {"ADF-MF-16030", "Tuntematon yhteystyyppi"},
    {"ADF-MF-16031", "Kohdetta FeatureContext ei l\u00F6ydy."},
    {"ADF-MF-16032", "Odottamaton vastaus"},
    {"ADF-MF-16033", "CVM Response palautti tyhj\u00E4n vastauksen. "},
    {"ADF-MF-16034", "CVM Response palautti tyhj\u00E4n kohteen FeatureContextAccessor."},
    {"ADF-MF-16035", "JS Response palautti tyhj\u00E4n vastauksen."},
    {"ADF-MF-16036", "Ei voi l\u00E4hett\u00E4\u00E4 JavaScript-kutsuja kohteeseen _Control_Channel_."},
    {"ADF-MF-16037", "IO-virhe"},
    {"ADF-MF-16038", "Virhe tiedoston poistossa."},
    {"ADF-MF-16039", "Virhe tiedoston kopioinnissa."},
    {"ADF-MF-16040", "Odotettu tiedosto puuttuu."},
    {"ADF-MF-16041", "Virhe tiedoston siirrossa."},
    {"ADF-MF-16042", "Hakemiston luonti ei onnistu."},
    {"ADF-MF-16043", "Noutovirhe"},
    {"ADF-MF-16044", "Yhteyden luonti ei onnistu"},
    {"ADF-MF-16045", "Odottamaton virhe tiedoston noudossa."},
    {"ADF-MF-16046", "Todennusvirhe"},
    {"ADF-MF-16047", "Meill\u00E4 ei ole k\u00E4ytt\u00E4j\u00E4tunnusta tai salasanaa."},
    {"ADF-MF-16048", "Tiedostoa ei voi noutaa todennusvirheen vuoksi."},
    {"ADF-MF-16049", "Virheellinen s\u00E4il\u00F6asiakirja"},
    {"ADF-MF-16050", "Havaittiin feature-elementti aktiivista feature-ominaisuutta k\u00E4sitelt\u00E4ess\u00E4."},
    {"ADF-MF-16051", "Ominaisuuden tunnus _Control_Channel_ on ristiriidassa varatun VM-kanavan tunnusnimen kanssa."},
    {"ADF-MF-16052", "OracleAdfmfFeature-luokka alustettiin v\u00E4\u00E4r\u00E4ll\u00E4 elementtityypill\u00E4."},
    {"ADF-MF-16053", "V\u00E4\u00E4r\u00E4 tila"},
    {"ADF-MF-16054", "Tiedoston URL ei voi olla tyhj\u00E4"},
    {"ADF-MF-16055", "Yritettiin lis\u00E4t\u00E4 ASINetworkQueue-jonoon objekti, joka ei ollut ASIHTTPRequest-pyynt\u00F6"},
    {"ADF-MF-16056", "Yhteystiedon luonnin virhe"},
    {"ADF-MF-16057", "Yhteystiedon poiston virhe"},
    {"ADF-MF-16058", "Virheellisen m\u00E4\u00E4ritteen virhe"},
    {"ADF-MF-16059", "Aikakatkaisuvirhe"},
    {"ADF-MF-16060", "Odottavan toiminnon virhe"},
    {"ADF-MF-16061", "I/O-virhe."},
    {"ADF-MF-16062", "Ei tuetun virhe"},
    {"ADF-MF-16063", "K\u00E4ytt\u00F6oikeuden ep\u00E4\u00E4misen virhe"},
    {"ADF-MF-16064", "Tuntematon virhe"},
    {"ADF-MF-16066", "Virheellinen luokka"},
    {"ADF-MF-16067", "Luokasta puuttuu vaaditun funktion toteutus. Kirjaa luokkaa koskevat tiedot lokiin ottamalla virheenetsint\u00E4 k\u00E4ytt\u00F6\u00F6n."},
    {"ADF-MF-16068", "Ominaisuusn\u00E4kym\u00E4n luokkaa ei l\u00F6ydy."},
    {"ADF-MF-16069", "Ominaisuusn\u00E4kym\u00E4n luokkaa ei voitu luoda."},
    {"ADF-MF-16070", "N\u00E4kym\u00E4n ohjain tarjosi tyhj\u00E4n n\u00E4kym\u00E4n ominaisuusn\u00E4kym\u00E4lle."},
    {"ADF-MF-16071", "Luokka ei ole sallittu n\u00E4kym\u00E4tyyppi. T\u00E4ll\u00E4 hetkell\u00E4 tuetun aliluokan on oltava kohteesta UIView tai UIViewController."},
    {"ADF-MF-16072", "Ominaisuuden k\u00E4ytt\u00E4m\u00E4\u00E4 HttpURLConnection-yhteytt\u00E4 ei l\u00F6ytynyt."},
    {"ADF-MF-16073", "Ominaisuuden k\u00E4ytt\u00E4m\u00E4ll\u00E4 HttpURLConnection-yhteydell\u00E4 on tyhj\u00E4 URL."},
    {"ADF-MF-16074", "Virheellinen sanoma"},
    {"ADF-MF-16075", "Sanomassa m\u00E4\u00E4ritetty tuntematon sanomatyyppi."},
    {"ADF-MF-16076", "Sis\u00E4\u00E4nkirjausvirhe"},
    {"ADF-MF-16077", "Kokoonpanovirhe"},
    {"ADF-MF-16078", " UIWebView-latausvirhe"},
    {"ADF-MF-16079", " Ominaisuuden %@ lataus ep\u00E4onnistui, URL: %@"},
    {"ADF-MF-16080", "Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16081", "Sis\u00E4\u00E4nkirjauspalvelimeen ei saada yhteytt\u00E4."},
    {"ADF-MF-16082", "Virheellinen k\u00E4ytt\u00E4j\u00E4tunnus/salasana. Jos ongelma jatkuu, ota yhteys j\u00E4rjestelm\u00E4n p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16083", "Kokoonpanovirhe. Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n. "},
    {"ADF-MF-16084", "ACS ep\u00E4onnistui"},
    {"ADF-MF-16085", "Virheellinen ACS-kokoonpano. K\u00E4ytt\u00E4j\u00E4objektia ei haettu oikein ACS-kokoonpanovirheen vuoksi. K\u00E4ytt\u00E4j\u00E4 ei ehk\u00E4 ole rekister\u00F6itynyt ACS:\u00E4\u00E4n. Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16086", "Palvelimeen ei saada yhteytt\u00E4. Varmista, ett\u00E4 laitteella on yhteys Internetiin."},
    {"ADF-MF-16087", "Virheellinen k\u00E4ytt\u00E4j\u00E4tunnus tai salasana. Yrit\u00E4 uudelleen."},
    {"ADF-MF-16088", "Kokoonpanovirhe. K\u00E4yt\u00F6nvalvontapalvelun URL puuttuu. Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16089", "Sis\u00E4\u00E4nkirjausyritysten sallittu enimm\u00E4ism\u00E4\u00E4r\u00E4 on ylitetty. Sinut on lukittu ulos. Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16090", "Kokoonpanomuutosten tarkistusta ei voitu suorittaa. Tarkista verkkoyhteys tai ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16091", "Kokoonpanoja ei voi p\u00E4ivitt\u00E4\u00E4 kokoonpanopalvelusta."},
    {"ADF-MF-16092", "V\u00E4\u00E4rin muodostettu sanoma"},
    {"ADF-MF-16093", "Tyhj\u00E4\u00E4 pyynt\u00F6sanomaa ei sallita."},
    {"ADF-MF-16094", "Sanomaa ei tueta"},
    {"ADF-MF-16095", "J\u00E4rjestelm\u00E4sanomia ei tueta t\u00E4ss\u00E4 kanavassa"},
    {"ADF-MF-16096", "Virheellinen j\u00E4rjestelm\u00E4pyynt\u00F6 %@"},
    {"ADF-MF-16097", "Sovellussanomia ei tueta t\u00E4ss\u00E4 kanavassa"},
    {"ADF-MF-16098", "Virheellinen sovelluspyynt\u00F6 %@"},
    {"ADF-MF-16099", "K\u00E4sittelem\u00E4t\u00F6n sanoma"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d tyyppi: %d runko: %@"},
    {"ADF-MF-16101", "Vastaanotettiin ei-pyydetty vastaussanoma"},
    {"ADF-MF-16102", "Vastaanotettiin tuntematon sanomatyyppi"},
    {"ADF-MF-16103", "AdfChannel.handle - virhe VMChannel-sanoman k\u00E4sittelyss\u00E4: %@ - VIRHE: %@"},
    {"ADF-MF-16104", "Ei m\u00E4\u00E4ritetty\u00E4 kohdetta %@. Virhe poistettu: %@"},
    {"ADF-MF-16105", "Laite ei ole k\u00E4ytett\u00E4viss\u00E4 ominaisuutta %@ varten: url: %@, baseUrl: %@, msg: %@"},
    {"ADF-MF-16106", "URL ei ole sallittu laitteen k\u00E4ytt\u00F6\u00F6n ominaisuutta %@ varten: url: %@, baseUrl: %@, msg: %@"},
    {"ADF-MF-16107", "VIRHE valkoisen listan luonnissa: %@"},
    {"ADF-MF-16108", "P\u00E4ivitetty\u00E4 leveytt\u00E4/korkeutta ei voi l\u00E4hett\u00E4\u00E4 Java-puolelle"},
    {"ADF-MF-16109", "Rekister\u00F6inti verkon tilan muutostapahtumia varten ei onnistu. Verkon tila ei ole saatavilla."},
    {"ADF-MF-16110", "Oletusarvoista sis\u00E4\u00E4nkirjausyhteytt\u00E4 %@ ei ole m\u00E4\u00E4ritetty."},
    {"ADF-MF-16111", "Olemus %@ puuttuu perheest\u00E4. Ohitetaan."},
    {"ADF-MF-16112", "Aktiivinen olemusperhe %@ ei palauttanut olemusta."},
    {"ADF-MF-16113", "Liitett\u00E4 %@ ei l\u00F6ytynyt tai sit\u00E4 ei voi lukea"},
    {"ADF-MF-16114", "%@ ei tue kohdetta deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "Kohdetta %@ ei ole m\u00E4\u00E4ritetty web-n\u00E4kym\u00E4ss\u00E4. JavaScript-tuloksen kutsu keskeytetty."},
    {"ADF-MF-16116", "Funktion %@ kutsussa ilmeni ongelma: %@"},
    {"ADF-MF-16117", "VIRHE: poikkeus suoritettaessa kohteen %d vastakutsua: %@"},
    {"ADF-MF-16118", "Sovelluksen todennusvirhe. Syy = %@"},
    {"ADF-MF-16119", "Ominaisuuden todennusvirhe. Ominaisuus poistettu k\u00E4yt\u00F6st\u00E4. Syy = %@"},
    {"ADF-MF-16120", "Todennusvirhe. Yrit\u00E4 uudelleen."},
    {"ADF-MF-16121", "ACS palautti virheen: %@"},
    {"ADF-MF-16122", "ACS-kohdetta ei ole m\u00E4\u00E4ritetty yhteydelle %@. K\u00E4ytt\u00E4j\u00E4objekteja ei rekister\u00F6id\u00E4."},
    {"ADF-MF-16123", "Sovellustason sis\u00E4\u00E4nkirjaus ep\u00E4onnistui todennuskontekstin puuttumisen takia."},
    {"ADF-MF-16124", "Tiedosto on v\u00E4limuistin polussa"},
    {"ADF-MF-16125", "V\u00E4limuistille ei voi luoda hakemistoa kohteeseen %@, koska tiedosto on jo olemassa"},
    {"ADF-MF-16126", "V\u00E4limuistihakemiston luonti ep\u00E4onnistui"},
    {"ADF-MF-16127", "Hakemiston luonti v\u00E4limuistille kohteeseen %@ ep\u00E4onnistui"},
    {"ADF-MF-16128", "V\u00E4limuistihakemiston l\u00E4pik\u00E4ynti ep\u00E4onnistui"},
    {"ADF-MF-16129", "V\u00E4limuistihakemiston listaus ep\u00E4onnistui polussa %@"},
    {"ADF-MF-16130", "V\u00E4limuistitiedoston poisto ep\u00E4onnistui"},
    {"ADF-MF-16131", "V\u00E4limuistiin tallennettujen tietojen poisto polusta %@ ep\u00E4onnistui"},
    {"ADF-MF-16132", "Kaatuu nyt, koska kokoonpanoa ei voitu ladata."},
    {"ADF-MF-16133", "Ominaisuuden n\u00E4ytt\u00E4minen ep\u00E4onnistui"},
    {"ADF-MF-16134", "Ominaisuutta ei voitu n\u00E4ytt\u00E4\u00E4. Yritys n\u00E4ytt\u00E4\u00E4 ominaisuus %@ ep\u00E4onnistui.  VIRHE: %@"},
    {"ADF-MF-16135", "Sovellusohjaimen virhe"},
    {"ADF-MF-16136", "Sovellusohjaimen kansiota %@ ei ole."},
    {"ADF-MF-16137", "Ei voitu ladata .properties-tiedostoa: %@ - ERROR: %@"},
    {"ADF-MF-16138", "Virhe sarjoitettaessa palautusta: %@"},
    {"ADF-MF-16139", "FeatureId-tunnusta ei voitu m\u00E4\u00E4ritt\u00E4\u00E4. Peruutetaan Java-luokan kutsu."},
    {"ADF-MF-16140", "CVM-kanavan tarkistus ep\u00E4onnistui."},
    {"ADF-MF-16141", "CVM palautti odottamattoman objektityypin: %@"},
    {"ADF-MF-16142", "Sanomaa ei voi l\u00E4hett\u00E4\u00E4"},
    {"ADF-MF-16143", "Sanomaa ei voi l\u00E4hett\u00E4\u00E4, sill\u00E4 tekstiviestit eiv\u00E4t ole k\u00E4ytett\u00E4viss\u00E4 t\u00E4ss\u00E4 laitteessa."},
    {"ADF-MF-16144", "Sanomaa ei voi l\u00E4hett\u00E4\u00E4, sill\u00E4 tekstiviestin luontia ei saada."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - m\u00E4\u00E4ritett\u00E4 classname ei m\u00E4\u00E4ritetty"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - kutsu morphClassName aiheutti virheen: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - morphClassName classname ep\u00E4onnistui."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - m\u00E4\u00E4ritett\u00E4 method ei m\u00E4\u00E4ritetty"},
    {"ADF-MF-16149", "Luokkaa ei voi luoda: %@"},
    {"ADF-MF-16150", "Objektityypin Uusi-komento ep\u00E4onnistui: %@"},
    {"ADF-MF-16151", "Luokan %@ instanssi ei vastaa valitsinta %@."},
    {"ADF-MF-16152", "Kohteen %@ kutsu aiheutti virheen: %@"},
    {"ADF-MF-16153", "Kohteesta %@ saadun tyypin %@ tuloksen sarjoitus aiheutti virheen: %@"},
    {"ADF-MF-16154", "Kohteesta %@ saadun tyypin %@ tuloksen sarjoitus aiheutti tyhj\u00E4n arvon."},
    {"ADF-MF-16155", "Yhteyden %@ credentialStoreKey ei voi olla tyhj\u00E4"},
    {"ADF-MF-16156", "Yhteyden credentialStoreKey ei voi olla tyhj\u00E4"},
    {"ADF-MF-16157", "Yleinen kirjautumisvirhe. K\u00E4ytt\u00E4j\u00E4 on saattanut antaa virheelliset valtuudet tai kirjautumisyhteyden kokoonpanossa saattaa olla virhe. Esim. kirjautumisen URL ja/tai ev\u00E4steen nimi saattavat olla virheelliset tai puuttua kokonaan."},
    {"ADF-MF-16158", "Palvelimeen ei saada yhteytt\u00E4. Varmista, ett\u00E4 olet yhteydess\u00E4 Internetiin."},
    {"ADF-MF-16159", "Virhe kohteessa threadShellInitializationComplete: %@"},
    {"ADF-MF-16160", "Virhe kohteessa paintMirrorLoop: %@"},
    {"ADF-MF-16161", "ACS:lle ei ole m\u00E4\u00E4ritetty oletusyhteytt\u00E4 ja rajoitteiset toiminnot eiv\u00E4t ole k\u00E4ytett\u00E4viss\u00E4."},
    {"ADF-MF-16162", "Virhe k\u00E4ytt\u00E4j\u00E4tunnuksessa"},
    {"ADF-MF-16163", "K\u00E4ytetty k\u00E4ytt\u00E4j\u00E4nimi ja/tai olion nimi ei ole sama kuin alkuper\u00E4inen k\u00E4ytt\u00E4j\u00E4nimi ja/tai olion nimi. Korjaa k\u00E4ytt\u00E4j\u00E4nimi ja/tai olion nimi, jos annoit v\u00E4\u00E4r\u00E4n k\u00E4ytt\u00E4j\u00E4nimen ja/tai olion nimen. Jotta voit kirjautua uutena k\u00E4ytt\u00E4j\u00E4n\u00E4, poistu ensin sovelluksesta."},
    {"ADF-MF-16164", "Usean olion yl\u00E4tunnisteen nimi puuttuu"},
    {"ADF-MF-16165", "Ei voi todentaa, koska monioliosovelluksessa ei ole riitt\u00E4v\u00E4sti tietoja todennusta varten. Kokoonpano puuttuu monen olion otsikon nimest\u00E4. Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16166", "Olion nime\u00E4 ei sy\u00F6tetty"},
    {"ADF-MF-16167", "Todennusta ei voi suorittaa, koska olion nime\u00E4 ei annettu. Yrit\u00E4 uudelleen."},
    {"ADF-MF-16168", "Yritet\u00E4\u00E4n sovellustason sis\u00E4\u00E4nkirjausta. Palvelin=%@ k\u00E4ytt\u00E4j\u00E4lle=%@"},
    {"ADF-MF-16169", "Sovellustason sis\u00E4\u00E4nkirjaus onnistui."},
    {"ADF-MF-16170", "OMCredentialStore ei palauttanut ominaisuutta kohteelle kSecAttrLabel."},
    {"ADF-MF-16171", "Sovelluksen k\u00E4ytt\u00E4j\u00E4objektit haetaan valtuuss\u00E4il\u00F6st\u00E4: %@"},
    {"ADF-MF-16172", "K\u00E4ytt\u00E4j\u00E4n todennustesti palauttaa arvon %@."},
    {"ADF-MF-16173", "Ominaisuustason sis\u00E4\u00E4nkirjaus ep\u00E4onnistui odottamattoman tilan vuoksi."},
    {"ADF-MF-16174", "Ominaisuustason sis\u00E4\u00E4nkirjausyritys k\u00E4ytt\u00E4j\u00E4lle=%@."},
    {"ADF-MF-16175", "Ominaisuustason uloskirjausyritys."},
    {"ADF-MF-16176", "K\u00E4ytt\u00E4j\u00E4objekteja haetaan, koska kyseess\u00E4 on et\u00E4ominaisuuden sis\u00E4\u00E4nkirjaus."},
    {"ADF-MF-16177", "Todennus onnistui."},
    {"ADF-MF-16178", "palautti k\u00E4ytt\u00E4j\u00E4objektien vastauksen=%@"},
    {"ADF-MF-16179", "palautti k\u00E4ytt\u00E4j\u00E4objektien oikeudet=%@ roolit=%@"},
    {"ADF-MF-16180", "Kutsutaan ACS:\u00E4\u00E4 k\u00E4sitellyll\u00E4 tiedolla=%@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: authContext-kohdetta ei saatu."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: pausedFeature-kohdetta ei saatu."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: authContext-kohdetta ei saatu."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: pausedFeature-kohdetta ei saatu."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: authContext-kohdetta ei saatu."},
    {"ADF-MF-16186", "Kokoonpanovirhe"},
    {"ADF-MF-16187", "Sovelluksen kirjautumisyhteytt\u00E4 ei ole m\u00E4\u00E4ritetty. Sovellusta ei voi suorittaa. Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16188", "Toiminnon kirjautumisyhteytt\u00E4 ei ole m\u00E4\u00E4ritetty. Toimintoa ei voi k\u00E4ytt\u00E4\u00E4. Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16189", "Uloskirjaus"},
    {"ADF-MF-16190", "Uloskirjaus aloitettu. Sovellus lopetetaan."},
    {"ADF-MF-16191", "Sis\u00E4\u00E4nkirjausyhteyden kokoonpanovirhe. {0} Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16192", "Valtuuss\u00E4il\u00F6n avainta ei ole m\u00E4\u00E4ritetty."},
    {"ADF-MF-16193", "K\u00E4ytt\u00E4j\u00E4tunnus tai salasana on virheellinen tai puuttuu."},
    {"ADF-MF-16195", "Valtuusvaraston yhdistelm\u00E4avaimen virhe."},
    {"ADF-MF-16196", "Virheellinen k\u00E4yt\u00F6n valvontapalvelun URL."},
    {"ADF-MF-16197", "Virheellinen uloskirjauksen URL."},
    {"ADF-MF-16198", "Virheellinen sis\u00E4\u00E4nkirjauksen URL."},
    {"ADF-MF-16199", "Cookie-tiedostoa ei ole m\u00E4\u00E4ritetty."},
    {"ADF-MF-16200", "Odotuksen aikakatkaisuarvon on oltava v\u00E4hint\u00E4\u00E4n 10, ja istunnon aikakatkaisuarvon on oltava v\u00E4hint\u00E4\u00E4n 30 ja odotuksen aikakatkaisuarvoa suurempi."},
    {"ADF-MF-16201", "Sis\u00E4\u00E4nkirjausyhteyden kokoonpanovirhe"},
    {"ADF-MF-16202", "Todennuksen URL-osoitteesta saatiin vastaukseksi virheellinen HTTP-vastauskoodi. Se ei ole perustodennuksen loppupiste. Ota yhteys p\u00E4\u00E4k\u00E4ytt\u00E4j\u00E4\u00E4n."},
    {"ADF-MF-16203", "Tiedostoa ei l\u00F6ydy: %@"},
    {"ADF-MF-16204", "S\u00E4hk\u00F6postiviesti\u00E4 ei tallennettu tai siirretty jonoon todenn\u00E4k\u00F6isesti virheen vuoksi."},
    {"ADF-MF-16205", "Virhe tallennettaessa s\u00E4hk\u00F6postiviesti\u00E4 luonnosten kansioon."},
    {"ADF-MF-16206", "Virhe l\u00E4hetett\u00E4ess\u00E4 s\u00E4hk\u00F6postiviesti\u00E4 tai siirrett\u00E4ess\u00E4 sit\u00E4 jonoon."},
    {"ADF-MF-16207", "Tuntematon virhe luotaessa tai l\u00E4hetett\u00E4ess\u00E4 s\u00E4hk\u00F6postiviesti\u00E4"},
    {"ADF-MF-16208", "Tuntematon virhe luotaessa tai l\u00E4hetett\u00E4ess\u00E4 tekstiviesti\u00E4"},
    {"ADF-MF-16209", "Tiedostoa ei l\u00F6ydy"},
    {"ADF-MF-16210", "Virheellinen URI-m\u00E4\u00E4rityksen etuliite. Etuliite %@ on jo liitetty URI-tunnisteeseen %@, eik\u00E4 sen liitt\u00E4minen uudelleen URI-tunnisteeseen %@ ole sallittua"},
    {"ADF-MF-16211", "Virheellinen URI-m\u00E4\u00E4rityksen etuliite. URI %@ on jo liitetty etuliitteeseen %@, eik\u00E4 sen liitt\u00E4minen uudelleen etuliitteeseen %@ ole sallittua"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
