// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_de extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "Klasse %@ hat bei der Zuordnung und Initiierung einen Fehler generiert - Hinzuf\u00FCgen von Application Lifecycle Listener wird abgebrochen FEHLER: %@"},
    {"ADF-MF-16002", "Ung\u00FCltige Verwendung"},
    {"ADF-MF-16003", "Diese Funktion muss auf dem Hauptthread aufgerufen werden."},
    {"ADF-MF-16004", "Diese Funktion darf NICHT auf dem Hauptthread aufgerufen werden."},
    {"ADF-MF-16005", "Ung\u00FCltige Konfigurationsdatei"},
    {"ADF-MF-16006", "Ung\u00FCltige Konfiguration"},
    {"ADF-MF-16007", "AdfmfContainerUtilities-Implementierer nicht konfiguriert."},
    {"ADF-MF-16008", "AdfmfContainerUtilities-Implementiererklasse nicht gefunden."},
    {"ADF-MF-16009", "AdfmfContainerUtilities-Implementierer konnte nicht erstellt werden."},
    {"ADF-MF-16010", "Ung\u00FCltige Anforderung"},
    {"ADF-MF-16011", "Datei konnte wegen Fehlermeldung 400 \"Ung\u00FCltige Anforderung\" nicht heruntergeladen werden."},
    {"ADF-MF-16012", "Nicht autorisiert"},
    {"ADF-MF-16013", "Datei konnte wegen Fehlermeldung 401 \"Nicht autorisiert\" (ung\u00FCltiger Benutzername und ung\u00FCltiges Kennwort) nicht heruntergeladen werden."},
    {"ADF-MF-16014", "Untersagt"},
    {"ADF-MF-16015", "Datei konnte wegen Fehlermeldung 403 \"Untersagt\" nicht heruntergeladen werden."},
    {"ADF-MF-16016", "Nicht gefunden"},
    {"ADF-MF-16017", "Datei konnte wegen Fehlermeldung 404 \"Nicht gefunden\" nicht heruntergeladen werden."},
    {"ADF-MF-16018", "Ung\u00FCltiges Gateway"},
    {"ADF-MF-16019", "Datei konnte wegen Fehlermeldung 502 \"Ung\u00FCltiges Gateway\" nicht heruntergeladen werden."},
    {"ADF-MF-16020", "Dienst nicht verf\u00FCgbar"},
    {"ADF-MF-16021", "Datei konnte wegen Fehlermeldung 503 \"Dienst nicht verf\u00FCgbar\" nicht heruntergeladen werden."},
    {"ADF-MF-16022", "Ung\u00FCltiges Argument"},
    {"ADF-MF-16023", "Es wurde ein Null-Packagename an [oraADFLogger getLogger:] \u00FCbergeben."},
    {"ADF-MF-16024", "Fehlerdatei-URL darf nicht null sein"},
    {"ADF-MF-16025", "Eigenschaftsname darf nicht null sein."},
    {"ADF-MF-16026", "Zu wenige Argumente."},
    {"ADF-MF-16027", "Fehlender Klassenname."},
    {"ADF-MF-16028", "Fehlende Methode."},
    {"ADF-MF-16029", "Feature-ID fehlt."},
    {"ADF-MF-16030", "Nicht erkannter Aufruftyp"},
    {"ADF-MF-16031", "FeatureContext nicht gefunden."},
    {"ADF-MF-16032", "Unerwartete Antwort"},
    {"ADF-MF-16033", "CVM-Antwort hat einen Nullwert zur\u00FCckgegeben. "},
    {"ADF-MF-16034", "CVM-Antwort hat einen Nullwert f\u00FCr FeatureContextAccessor zur\u00FCckgegeben."},
    {"ADF-MF-16035", "JS-Antwort hat einen Nullwert zur\u00FCckgegeben."},
    {"ADF-MF-16036", "JavaScript-Aufrufe k\u00F6nnen nicht an den _Control_Channel_ gesendet werden."},
    {"ADF-MF-16037", "IO-Fehler"},
    {"ADF-MF-16038", "Fehler beim Entfernen der Datei."},
    {"ADF-MF-16039", "Fehler beim Kopieren der Datei."},
    {"ADF-MF-16040", "Erwartete Datei fehlt."},
    {"ADF-MF-16041", "Fehler beim Verschieben der Datei."},
    {"ADF-MF-16042", "Verzeichnis konnte nicht erstellt werden."},
    {"ADF-MF-16043", "Fehler beim Herunterladen"},
    {"ADF-MF-16044", "Verbindung konnte nicht hergestellt werden"},
    {"ADF-MF-16045", "Beim Herunterladen der Datei ist ein unerwarteter Fehler aufgetreten."},
    {"ADF-MF-16046", "Authentifizierung nicht erfolgreich"},
    {"ADF-MF-16047", "Es ist kein Benutzername oder Kennwort vorhanden."},
    {"ADF-MF-16048", "Datei konnte wegen einer nicht erfolgreichen Authentifizierung nicht heruntergeladen werden."},
    {"ADF-MF-16049", "Ung\u00FCltiges Containerdokument"},
    {"ADF-MF-16050", "Element \"Feature\" ist aufgetreten, w\u00E4hrend ein aktives \"Feature\" verarbeitet wurde."},
    {"ADF-MF-16051", "Die Feature-ID \\'_Control_Channel_\\' steht im Konflikt mit dem reservierten Identifier-Namen eines VM-Kanals"},
    {"ADF-MF-16052", "Klasse \\'OracleAdfmfFeature\\' wurde mit einem falschen Elementtyp initialisiert."},
    {"ADF-MF-16053", "Ung\u00FCltiger Status"},
    {"ADF-MF-16054", "Datei-URL darf nicht null sein"},
    {"ADF-MF-16055", "Es wurde versucht, ein Objekt hinzuzuf\u00FCgen, das kein ASIHTTPRequest an eine ASINetworkQueue war"},
    {"ADF-MF-16056", "Fehler beim Erstellen von Kontakt"},
    {"ADF-MF-16057", "Fehler beim Entfernen von Kontakt"},
    {"ADF-MF-16058", "Fehler: Ung\u00FCltiges Argument"},
    {"ADF-MF-16059", "Timeout-Fehler"},
    {"ADF-MF-16060", "Fehler: Ausstehender Vorgang"},
    {"ADF-MF-16061", "I/O-Fehler"},
    {"ADF-MF-16062", "Fehler: Nicht unterst\u00FCtzt"},
    {"ADF-MF-16063", "Fehler: Berechtigung abgelehnt"},
    {"ADF-MF-16064", "Unbekannter Fehler"},
    {"ADF-MF-16066", "Ung\u00FCltige Klasse"},
    {"ADF-MF-16067", "Der Klasse fehlt die Implementierung einer erforderlichen Funktion. Aktivieren Sie Debugging, um Informationen zu der Klasse zu protokollieren."},
    {"ADF-MF-16068", "Featureansichtsklasse nicht gefunden."},
    {"ADF-MF-16069", "Featureansichtsklasse konnte nicht erstellt werden."},
    {"ADF-MF-16070", "Ansicht-Controller hat eine Null-Ansicht f\u00FCr die Featureansicht bereitgestellt."},
    {"ADF-MF-16071", "Klasse ist kein g\u00FCltiger Ansichtstyp. Die derzeit unterst\u00FCtzte Unterklasse muss vom Typ UIView oder UIViewController sein"},
    {"ADF-MF-16072", "Eine von einem Feature verwendete HttpURLConnection wurde nicht gefunden."},
    {"ADF-MF-16073", "Eine von einem Feature verwendete HttpURLConnection weist eine Null-URL auf."},
    {"ADF-MF-16074", "Ung\u00FCltige Nachricht"},
    {"ADF-MF-16075", "Unbekannter Nachrichtentyp von Nachricht angegeben."},
    {"ADF-MF-16076", "Fehler bei der Anmeldung"},
    {"ADF-MF-16077", "Konfigurationsfehler"},
    {"ADF-MF-16078", " UIWebView-Ladefehler"},
    {"ADF-MF-16079", " Feature '%@' URL konnte nicht geladen werden: %@"},
    {"ADF-MF-16080", "Wenden Sie sich an Ihren Administrator."},
    {"ADF-MF-16081", " Der Anmeldeserver ist nicht erreichbar."},
    {"ADF-MF-16082", "Benutzername/Kennwort ung\u00FCltig. Wenn das Problem weiterhin auftritt, wenden Sie sich an den Systemadministrator."},
    {"ADF-MF-16083", "Konfigurationsfehler. Wenden Sie sich an den Administrator. "},
    {"ADF-MF-16084", "ACS nicht erfolgreich"},
    {"ADF-MF-16085", "Ung\u00FCltige ACS-Konfiguration. Benutzerobjekt wurde wegen ACS-Konfigurationsfehler nicht ordnungsgem\u00E4\u00DF abgerufen. M\u00F6glicherweise ist der Benutzer nicht bei ACS registriert. Wenden Sie sich an den Administrator. "},
    {"ADF-MF-16086", "Server ist nicht erreichbar. Stellen Sie sicher, dass Ihr Ger\u00E4t mit dem Internet verbunden ist."},
    {"ADF-MF-16087", "Benutzername/Kennwort ung\u00FCltig. Versuchen Sie es erneut."},
    {"ADF-MF-16088", "Konfigurationsfehler. Zugriffskontrolldienst-URL fehlt. Wenden Sie sich an den Administrator."},
    {"ADF-MF-16089", "Sie haben die maximal zul\u00E4ssigen Anmeldeversuche \u00FCberschritten. Sie wurden gesperrt. Wenden Sie sich an den Administrator."},
    {"ADF-MF-16090", "Die Pr\u00FCfung auf Konfigurations\u00E4nderungen konnte nicht ausgef\u00FChrt werden. Pr\u00FCfen Sie Ihre Netzwerkverbindung, oder wenden Sie sich an den Administrator."},
    {"ADF-MF-16091", "Konfigurationen konnten nicht vom Konfigurationsdienst aktualisiert werden."},
    {"ADF-MF-16092", "Fehlerhafte Nachricht"},
    {"ADF-MF-16093", "Leere Anforderungsnachricht ist nicht zul\u00E4ssig."},
    {"ADF-MF-16094", "Nicht unterst\u00FCtzte Meldung"},
    {"ADF-MF-16095", "Systemmeldungen werden auf diesem Kanal nicht unterst\u00FCtzt"},
    {"ADF-MF-16096", "Ung\u00FCltige Systemanforderung %@"},
    {"ADF-MF-16097", "Anwendungsmeldungen werden auf diesem Kanal nicht unterst\u00FCtzt"},
    {"ADF-MF-16098", "Ung\u00FCltige Anwendungsanforderung %@"},
    {"ADF-MF-16099", "Nicht verarbeitete Meldung"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Typ: %d Body: %@"},
    {"ADF-MF-16101", "Eine nicht abgerufene Antwortnachricht wurde empfangen"},
    {"ADF-MF-16102", "Ein unbekannter Nachrichtentyp wurde empfangen"},
    {"ADF-MF-16103", "AdfChannel.handle - Fehler beim Verarbeiten der VMChannel-Meldung: %@ - FEHLER: %@"},
    {"ADF-MF-16104", "'%@' nicht angegeben. Fehler gel\u00F6scht: '%@'"},
    {"ADF-MF-16105", "Ger\u00E4tezugriff f\u00FCr Feature \\'%@\\' deaktiviert: url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16106", "URL hat Ger\u00E4tezugriff f\u00FCr Feature '%@' nicht zugelassen: url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16107", "FEHLER bei Erstellung der wei\u00DFen Liste: %@"},
    {"ADF-MF-16108", "Aktualisierte Breite und H\u00F6he kann nicht zur Java-Seite gesendet werden"},
    {"ADF-MF-16109", "Registrierung f\u00FCr \u00C4nderungsereignisse des Netzwerkstatus nicht m\u00F6glich. Der Netzwerkstatus wird nicht verf\u00FCgbar sein"},
    {"ADF-MF-16110", "Die Standardanmeldeverbindung '%@' ist nicht definiert."},
    {"ADF-MF-16111", "Der Skin '%@' fehlt eine Familie. Wird ignoriert."},
    {"ADF-MF-16112", "Aktive Skin-Familie '%@' hat keine Skin zur\u00FCckgegeben."},
    {"ADF-MF-16113", "Anhang %@ wurde nicht gefunden oder konnte nicht gelesen werden"},
    {"ADF-MF-16114", "%@ unterst\u00FCtzt nicht deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "%@ ist in der Webview nicht definiert. JavaScript-Ergebnisaufruf abgebrochen."},
    {"ADF-MF-16116", "Es ist ein Problem beim Aufrufen der Funktion '%@' aufgetreten: %@"},
    {"ADF-MF-16117", "FEHLER: Es ist eine Exception beim Ausf\u00FChren des %d Callback aufgetreten: %@"},
    {"ADF-MF-16118", "Anwendungsauthentifizierungsfehler. Grund = %@"},
    {"ADF-MF-16119", "Featureauthentifizierungsfehler. Feature deaktiviert. Grund = %@"},
    {"ADF-MF-16120", "Authentifizierungsfehler. Wiederholen Sie den Vorgang."},
    {"ADF-MF-16121", "ACS hat Fehler zur\u00FCckgegeben: %@"},
    {"ADF-MF-16122", "ACS nicht f\u00FCr die Verbindung %@ konfiguriert. Benutzerobjekte sind nicht registriert."},
    {"ADF-MF-16123", "Anmeldung auf Anwendungsebene war wegen fehlendem Authentifizierungskontext nicht erfolgreich."},
    {"ADF-MF-16124", "Datei ist im Cachepfad vorhanden"},
    {"ADF-MF-16125", "Es kann kein Verzeichnis f\u00FCr den Cache unter '%@' erstellt werden, da bereits eine Datei vorhanden ist"},
    {"ADF-MF-16126", "Cacheverzeichnis konnte nicht erstellt werden"},
    {"ADF-MF-16127", "Es konnte kein Verzeichnis f\u00FCr den Cache unter '%@' erstellt werden"},
    {"ADF-MF-16128", "Cacheverzeichnis konnte nicht durchlaufen werden"},
    {"ADF-MF-16129", "Auflistung des Cacheverzeichnisses im Pfad '%@' nicht erfolgreich"},
    {"ADF-MF-16130", "Cachedatei konnte nicht entfernt werden"},
    {"ADF-MF-16131", "Gecachte Daten konnten im Pfad \\'%@\\' nicht entfernt werden"},
    {"ADF-MF-16132", "Absturz, weil Konfiguration nicht heruntergeladen werden konnte."},
    {"ADF-MF-16133", "Anzeigen des Features nicht erfolgreich"},
    {"ADF-MF-16134", "Feature konnte nicht angezeigt werden. Versuch, das Feature '%@' anzuzeigen, war nicht erfolgreich. FEHLER: %@"},
    {"ADF-MF-16135", "Anwendungscontrollerfehler"},
    {"ADF-MF-16136", "Der Anwendungscontrollerordner \"%@\" ist nicht vorhanden."},
    {"ADF-MF-16137", ".properties-Datei konnte nicht geladen werden: %@ - ERROR: %@"},
    {"ADF-MF-16138", "Fehler bei der Serialisierung von R\u00FCckgabe: %@"},
    {"ADF-MF-16139", "Feature-ID konnte nicht bestimmt werden. Aufruf von Java-Klasse wird abgebrochen."},
    {"ADF-MF-16140", "Pr\u00FCfung von CVM-Kanal nicht erfolgreich."},
    {"ADF-MF-16141", "CVM hat einen unerwarteten Objekttyp zur\u00FCckgegeben: %@"},
    {"ADF-MF-16142", "Nachricht kann nicht gesendet werden"},
    {"ADF-MF-16143", "Nachricht kann nicht gesendet werden, da mit diesem Ger\u00E4t keine SMS m\u00F6glich sind."},
    {"ADF-MF-16144", "Nachricht kann nicht gesendet werden, da der Textnachrichten-Composer nicht abgerufen werden kann."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Der \"Klassenname\" wurde nicht angegeben"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - Der morphClassName-Aufruf hat einen FEHLER verursacht: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Der \"Klassenname\" morphClassName war nicht erfolgreich."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - Die \"Methode\" wurde nicht angegeben"},
    {"ADF-MF-16149", "Klasse konnte nicht erstellt werden: %@"},
    {"ADF-MF-16150", "\"Neu\" f\u00FCr Objekttyp war nicht erfolgreich: %@"},
    {"ADF-MF-16151", "Instanz von %@-Klasse reagiert nicht auf \"%@\"-Selector."},
    {"ADF-MF-16152", "Aufruf von \"%@\" hat einen Fehler verursacht: %@"},
    {"ADF-MF-16153", "Serialisieren des Ergebnisses von \"%@\" auf Typ %@ hat einen FEHLER verursacht: %@"},
    {"ADF-MF-16154", "Serialisieren des Ergebnisses von \"%@\" auf Typ %@ hat nichts generiert."},
    {"ADF-MF-16155", "credentialStoreKey f\u00FCr Verbindung %@ darf nicht Null sein"},
    {"ADF-MF-16156", "credentialStoreKey f\u00FCr Verbindung darf nicht Null sein"},
    {"ADF-MF-16157", "Allgemeiner Anmeldefehler aufgetreten. Benutzer hat m\u00F6glicherweise ung\u00FCltige Zugangsdaten eingegeben, oder die Konfiguration der Anmeldeverbindung enth\u00E4lt einen Fehler. Beispiel: Anmelde-URL und/oder Cookiename fehlt oder ist falsch."},
    {"ADF-MF-16158", "Der Server ist nicht zug\u00E4nglich. Stellen Sie sicher, dass die Verbindung zum Internet hergestellt ist."},
    {"ADF-MF-16159", "Fehler bei threadShellInitializationComplete: %@"},
    {"ADF-MF-16160", "Fehler bei paintMirrorLoop: %@"},
    {"ADF-MF-16161", "ACS ist nicht f\u00FCr Standardverbindung konfiguriert und eingeschr\u00E4nkte Features werden nicht verf\u00FCgbar gemacht."},
    {"ADF-MF-16162", "Fehler in Benutzername"},
    {"ADF-MF-16163", "Benutzername und/oder Tenant-Name sind nicht identisch mit urspr\u00FCnglichem Benutzernamen oder Tenant-Namen. Sie m\u00FCssen den Benutzernamen und/oder Tenant-Namen \u00E4ndern, wenn Sie ihn falsch eingegeben haben. Zur Anmeldung als neuer Benutzer m\u00FCssen Sie zuerst die Anwendung beenden."},
    {"ADF-MF-16164", "Multi-Tenant-Headername fehlt"},
    {"ADF-MF-16165", "Authentifizierung ist nicht m\u00F6glich, da nicht gen\u00FCgend Informationen zur Authentifizierung in Multi-Tenant-Anwendung angegeben wurden. In der Konfiguration fehlt der Multi-Tenant-Header-Name. Wenden Sie sich an den Administrator."},
    {"ADF-MF-16166", "Mandantenname wurde nicht eingegeben"},
    {"ADF-MF-16167", "Authentifizierung ist nicht m\u00F6glich, da der Mandantenname nicht angegeben wurde. Wiederholen Sie den Vorgang."},
    {"ADF-MF-16168", "Anmeldung auf Anwendungsebene wird versucht. Server=%@ f\u00FCr Benutzer=%@"},
    {"ADF-MF-16169", "Anmeldung auf Anwendungsebene erfolgreich."},
    {"ADF-MF-16170", "OMCredentialStore hat Eigenschaft f\u00FCr kSecAttrLabel nicht zur\u00FCckgegeben."},
    {"ADF-MF-16171", "Anwendungsbenutzerobjekte werden aus Zugangsdatenspeicher abgerufen: %@"},
    {"ADF-MF-16172", "Benutzerauthentifizierungstest gibt %@ zur\u00FCck."},
    {"ADF-MF-16173", "Anmeldung auf Featureebene wegen unerwarteter Bedingung nicht erfolgreich."},
    {"ADF-MF-16174", "Anmeldung auf Featureebene f\u00FCr Benutzer=%@ versucht."},
    {"ADF-MF-16175", "Abmeldeversuch auf Featureebene."},
    {"ADF-MF-16176", "Benutzerobjekte werden mit Pull geholt, weil es sich um eine Anmeldung bei einem Remotefeature handelt."},
    {"ADF-MF-16177", "Authentifizierung erfolgreich."},
    {"ADF-MF-16178", "Benutzerobjekteantwort=%@ zur\u00FCckgegeben"},
    {"ADF-MF-16179", "Benutzerobjekteberechtigungen=%@ Rollen=%@ zur\u00FCckgegeben"},
    {"ADF-MF-16180", "ACS wird mit Payload=%@ aufgerufen."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: authContext wurde nicht abgerufen."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: pausedFeature wurde nicht abgerufen."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: authContext wurde nicht abgerufen."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: pausedFeature wurde nicht abgerufen."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: authContext wurde nicht abgerufen."},
    {"ADF-MF-16186", "Konfigurationsfehler"},
    {"ADF-MF-16187", "Verbindung f\u00FCr Anwendungsanmeldung wurde nicht definiert. Diese Anwendung kann nicht ausgef\u00FChrt werden. Wenden Sie sich an den Administrator."},
    {"ADF-MF-16188", "Verbindung f\u00FCr Featureanmeldung wurde nicht definiert. Dieses Feature kann nicht aufgerufen werden. Wenden Sie sich an den Administrator."},
    {"ADF-MF-16189", "Abmelden"},
    {"ADF-MF-16190", "Abmeldung wurde gestartet. Anwendung wird beendet."},
    {"ADF-MF-16191", "Konfigurationsfehler bei Anmeldeverbindung. {0} Wenden Sie sich an den Administrator."},
    {"ADF-MF-16192", "Schl\u00FCssel des Zugangsdatenspeichers wurde nicht angegeben."},
    {"ADF-MF-16193", "Benutzername und/oder Kennwort ist ung\u00FCltig oder fehlt."},
    {"ADF-MF-16195", "Fehler bei zusammengesetztem Zugangsdatenspeicherschl\u00FCssel."},
    {"ADF-MF-16196", "Ung\u00FCltige Access Control-Service-URL."},
    {"ADF-MF-16197", "Ung\u00FCltige Abmelde-URL."},
    {"ADF-MF-16198", "Ung\u00FCltige Anmelde-URL."},
    {"ADF-MF-16199", "Cookie wurde nicht angegeben."},
    {"ADF-MF-16200", "Timeout bei Inaktivit\u00E4t muss 10 oder h\u00F6her sein, Sessiontimeout muss 30 oder h\u00F6her und h\u00F6her als das Timeout bei Inaktivit\u00E4t sein."},
    {"ADF-MF-16201", "Konfigurationsfehler bei Anmeldeverbindung"},
    {"ADF-MF-16202", "Authentifizierungs-URL hat einen ung\u00FCltigen HTTP-Antwortcode zur\u00FCckgegeben. Es handelt sich nicht um einen Basisauthentifizierungs-Endpunkt. Wenden Sie sich an den Administrator."},
    {"ADF-MF-16203", "Datei nicht gefunden: %@"},
    {"ADF-MF-16204", "Die E-Mail-Nachricht wurde m\u00F6glicherweise aufgrund eines Fehlers nicht gespeichert oder in die Queue gestellt."},
    {"ADF-MF-16205", "Beim Versuch, die E-Mail-Nachricht im Entwurfsordner zu speichern, ist ein Fehler aufgetreten."},
    {"ADF-MF-16206", "Beim Versuch, die E-Mail-Nachricht in die Queue zu stellen oder zu senden, ist ein Fehler aufgetreten."},
    {"ADF-MF-16207", "Beim Versuch, eine E-Mail zu verfassen oder zu senden, ist ein unbekannter Fehler aufgetreten"},
    {"ADF-MF-16208", "Beim Versuch, eine SMS zu verfassen oder zu senden, ist ein unbekannter Fehler aufgetreten"},
    {"ADF-MF-16209", "Datei nicht gefunden"},
    {"ADF-MF-16210", "Ung\u00FCltige Zuordnung zwischen Pr\u00E4fix und URI gefunden. Pr\u00E4fix: %@ ist bereits der URI: %@ zugeordnet. Die Neuzuordnung des Pr\u00E4fix zu URI: %@ ist nicht zul\u00E4ssig"},
    {"ADF-MF-16211", "Ung\u00FCltige Zuordnung zwischen Pr\u00E4fix und URI gefunden. URI: %@ ist bereits dem Pr\u00E4fix: %@ zugeordnet. Die Neuzuordnung der URI zu Pr\u00E4fix: %@ ist nicht zul\u00E4ssig"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
