// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_da extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "Klassen %@ genererede en fejl under alloc og init - Afbryder tilf\u00F8jelse af livscyklus-listener for applikation, FEJL: %@"},
    {"ADF-MF-16002", "Ugyldig brug"},
    {"ADF-MF-16003", "Denne funktion skal kaldes i hovedtr\u00E5den."},
    {"ADF-MF-16004", "Denne funktion m\u00E5 IKKE kaldes i hovedtr\u00E5den."},
    {"ADF-MF-16005", "Forkert konfigurationsfil"},
    {"ADF-MF-16006", "Ugyldig konfiguration"},
    {"ADF-MF-16007", "AdfmfContainerUtilities-implementator blev ikke konfigureret."},
    {"ADF-MF-16008", "AdfmfContainerUtilities-implementatorklasse blev ikke fundet."},
    {"ADF-MF-16009", "AdfmfContainerUtilities-implementator kunne ikke oprettes."},
    {"ADF-MF-16010", "Ugyldig anmodning"},
    {"ADF-MF-16011", "Kunne ikke downloade fil p\u00E5 grund af 400 Forkert anmodning."},
    {"ADF-MF-16012", "Uautoriseret"},
    {"ADF-MF-16013", "Kunne ikke downloade fil p\u00E5 grund af 401 Uautoriseret (forkert brugernavn eller adgangskode)."},
    {"ADF-MF-16014", "Forbudt"},
    {"ADF-MF-16015", "Kunne ikke downloade fil p\u00E5 grund af 403 Forbudt."},
    {"ADF-MF-16016", "Ikke fundet"},
    {"ADF-MF-16017", "Kunne ikke downloade fil p\u00E5 grund af 404 Ikke fundet."},
    {"ADF-MF-16018", "Forkert gateway"},
    {"ADF-MF-16019", "Kunne ikke downloade fil p\u00E5 grund af 502 Forkert gateway."},
    {"ADF-MF-16020", "Service ikke tilg\u00E6ngelig"},
    {"ADF-MF-16021", "Kunne ikke downloade fil p\u00E5 grund af 503 Service ikke tilg\u00E6ngelig."},
    {"ADF-MF-16022", "Ugyldigt argument"},
    {"ADF-MF-16023", "Et nulpakkenavn blev videregivet til [oraADFLogger getLogger:]."},
    {"ADF-MF-16024", "Fejl: Fil-URL kan ikke v\u00E6re nul"},
    {"ADF-MF-16025", "Egenskabsnavn kan ikke v\u00E6re nul."},
    {"ADF-MF-16026", "For f\u00E5 argumenter."},
    {"ADF-MF-16027", "Manglende klassenavn."},
    {"ADF-MF-16028", "Manglende metode."},
    {"ADF-MF-16029", "Facilitets-ID mangler."},
    {"ADF-MF-16030", "Ikke-genkendt kaldtype"},
    {"ADF-MF-16031", "FeatureContext blev ikke fundet."},
    {"ADF-MF-16032", "Uventet svar"},
    {"ADF-MF-16033", "CVM-svar returnerede et nulsvar. "},
    {"ADF-MF-16034", "CVM-svar returnerede en nul-FeatureContextAccessor."},
    {"ADF-MF-16035", "JS-svar returnerede et nulsvar."},
    {"ADF-MF-16036", "Kan ikke sende JavaScript-kald til _Control_Channel_."},
    {"ADF-MF-16037", "IO-fejl"},
    {"ADF-MF-16038", "Fejl under fjernelse af fil."},
    {"ADF-MF-16039", "Fejl under kopiering af fil."},
    {"ADF-MF-16040", "Forventet fil mangler."},
    {"ADF-MF-16041", "Fejl under flytning af fil."},
    {"ADF-MF-16042", "Kunne ikke oprette katalog."},
    {"ADF-MF-16043", "Download-fejl"},
    {"ADF-MF-16044", "Kunne ikke oprette forbindelse"},
    {"ADF-MF-16045", "Der opstod en uventet fejl under download af filen."},
    {"ADF-MF-16046", "Autentificeringsfejl"},
    {"ADF-MF-16047", "Vi har intet brugernavn og ingen adgangskode."},
    {"ADF-MF-16048", "Kunne ikke downloade fil p\u00E5 grund af autentificeringsfejl."},
    {"ADF-MF-16049", "Ugyldigt containerdokument"},
    {"ADF-MF-16050", "Elementet 'facilitet' blev fundet, mens en aktiv 'facilitet' blev behandlet."},
    {"ADF-MF-16051", "Facilitets-ID''et \\'_Control_Channel_\\' er i konflikt med et reserveret VM-kanalidentifikatornavn."},
    {"ADF-MF-16052", "Klassen 'OracleAdfmfFeature' blev initialiseret med en forkert elementtype."},
    {"ADF-MF-16053", "Forkert tilstand"},
    {"ADF-MF-16054", "Fil-URL kan ikke v\u00E6re nul"},
    {"ADF-MF-16055", "Fors\u00F8gte at f\u00F8je et objekt, der ikke var en ASIHTTPRequest, til en ASINetworkQueue"},
    {"ADF-MF-16056", "Fejl under oprettelse af kontaktperson"},
    {"ADF-MF-16057", "Fejl under fjernelse af kontaktperson"},
    {"ADF-MF-16058", "Fejl: Ugyldigt argument"},
    {"ADF-MF-16059", "Timeoutfejl"},
    {"ADF-MF-16060", "Fejl: Ventende operation"},
    {"ADF-MF-16061", "I/O-fejl"},
    {"ADF-MF-16062", "Fejl: Underst\u00F8ttes ikke"},
    {"ADF-MF-16063", "Fejl: Tilladelse n\u00E6gtet"},
    {"ADF-MF-16064", "Ukendt fejl"},
    {"ADF-MF-16066", "Ugyldig klasse"},
    {"ADF-MF-16067", "Klasse mangler en implementering af en p\u00E5kr\u00E6vet funktion. Aktiv\u00E9r debugging for at logge oplysninger om klassen."},
    {"ADF-MF-16068", "Klasse for facilitets-view blev ikke fundet."},
    {"ADF-MF-16069", "Klasse for facilitets-view kunne ikke oprettes."},
    {"ADF-MF-16070", "View-controller angav et nul-view for facilitets-view."},
    {"ADF-MF-16071", "Klasse er ikke en gyldig view-type. Aktuelt underst\u00F8ttet underklasse skal v\u00E6re fra: UIView eller UIViewController"},
    {"ADF-MF-16072", "En HttpURLConnection, der blev brugt af en facilitet, blev ikke fundet."},
    {"ADF-MF-16073", "En HttpURLConnection, der blev brugt af en facilitet, har en nul-URL."},
    {"ADF-MF-16074", "Ugyldig meddelelse"},
    {"ADF-MF-16075", "Ukendt meddelelsestype blev angivet af meddelelse."},
    {"ADF-MF-16076", "Log p\u00E5-fejl"},
    {"ADF-MF-16077", "Konfigurationsfejl"},
    {"ADF-MF-16078", " UIWebView-indl\u00E6sningsfejl"},
    {"ADF-MF-16079", " Kunne ikke indl\u00E6se URL'en: %@ for faciliteten'%@'"},
    {"ADF-MF-16080", "Kontakt administratoren."},
    {"ADF-MF-16081", "Logon-serveren er ikke tilg\u00E6ngelig."},
    {"ADF-MF-16082", "Ugyldigt brugernavn/ugyldig adgangskode. Hvis problemet varer ved, skal du kontakte systemadministratoren."},
    {"ADF-MF-16083", "Konfigurationsfejl. Kontakt administratoren. "},
    {"ADF-MF-16084", "ACS fejlede"},
    {"ADF-MF-16085", "Ugyldig ACS-konfiguration. Brugerobjekt blev ikke hentet korrekt p\u00E5 grund af fejl i ACS-konfiguration. Bruger er muligvis ikke registreret i ACS. Kontakt administratoren."},
    {"ADF-MF-16086", "Server er ikke tilg\u00E6ngelig. Kontroll\u00E9r, at enheden har forbindelse til internettet."},
    {"ADF-MF-16087", "Ugyldigt brugernavn/ugyldig adgangskode. Pr\u00F8v igen."},
    {"ADF-MF-16088", "Konfigurationsfejl. URL for adgangskontrolservice mangler. Kontakt administratoren."},
    {"ADF-MF-16089", "Du har overskredet det maksimalt tilladte antal logon-fors\u00F8g. Du er lukket ude. Kontakt administratoren."},
    {"ADF-MF-16090", "Kontrollen af konfigurations\u00E6ndringer kunne ikke udf\u00F8res. Kontroll\u00E9r netv\u00E6rksforbindelsen, eller kontakt en administrator."},
    {"ADF-MF-16091", "Kunne ikke opdatere konfigurationer fra konfigurationsservice."},
    {"ADF-MF-16092", "Forkert udformet meddelelse"},
    {"ADF-MF-16093", "Tom anmodningsmeddelelse er ikke tilladt."},
    {"ADF-MF-16094", "Ikke-underst\u00F8ttet meddelelse"},
    {"ADF-MF-16095", "Systemmeddelelser underst\u00F8ttes ikke p\u00E5 denne kanal"},
    {"ADF-MF-16096", "Ugyldig systemanmodning %@"},
    {"ADF-MF-16097", "Applikationsmeddelelser underst\u00F8ttes ikke p\u00E5 denne kanal"},
    {"ADF-MF-16098", "Ugyldig applikationsanmodning %@"},
    {"ADF-MF-16099", "Ikke-h\u00E5ndteret meddelelse"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Type: %d Indhold: %@"},
    {"ADF-MF-16101", "Modtog en uanmodet svarmeddelelse"},
    {"ADF-MF-16102", "Modtog en ukendt meddelelsestype"},
    {"ADF-MF-16103", "AdfChannel.handle - Fejl under h\u00E5ndtering af VMChannel-meddelelsen: %@ - FEJL: %@"},
    {"ADF-MF-16104", "Ingen '%@' er angivet. Fejl droppet: '%@'"},
    {"ADF-MF-16105", "Enhedsadgang er deaktiveret for faciliteten '%@': URL: %@, basis-URL: %@, meddelelse: %@"},
    {"ADF-MF-16106", "URL har ikke enhedsadgang for faciliteten '%@': URL: %@, basis-URL: %@, meddelelse: %@"},
    {"ADF-MF-16107", "FEJL under tilf\u00F8jelse til hvidliste: %@"},
    {"ADF-MF-16108", "Kan ikke sende opdateret bredde/h\u00F8jde til Java-side"},
    {"ADF-MF-16109", "Kan ikke udf\u00F8re registrering for \u00E6ndringsbegivenheder for netv\u00E6rksstatus. Netv\u00E6rksstatussen bliver ikke-tilg\u00E6ngelig"},
    {"ADF-MF-16110", "Standard-logon-forbindelsen '%@' er ikke defineret."},
    {"ADF-MF-16111", "Temaet '%@' mangler en gruppe. Ignoreres."},
    {"ADF-MF-16112", "Den aktive temagruppe '%@' returnerede intet tema."},
    {"ADF-MF-16113", "Den vedh\u00E6ftede fil %@ blev ikke fundet eller kunne ikke l\u00E6ses"},
    {"ADF-MF-16114", "%@ underst\u00F8tter ikke deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "%@ er ikke defineret i webvisningen. Kald af JavaScript-resultat blev afbrudt."},
    {"ADF-MF-16116", "Der opstod et problem under kald af funktionen '%@': %@"},
    {"ADF-MF-16117", "FEJL: En undtagelse opstod under udf\u00F8relse af %d-callback: %@"},
    {"ADF-MF-16118", "Fejl under autentificering af applikation. \u00C5rsag = %@"},
    {"ADF-MF-16119", "Fejl under autentificering af facilitet. Facilitet er deaktiveret. \u00C5rsag = %@"},
    {"ADF-MF-16120", "Autentificeringsfejl. Pr\u00F8v igen."},
    {"ADF-MF-16121", "ACS returnerede fejl: %@"},
    {"ADF-MF-16122", "ACS er ikke konfigureret til forbindelsen %@. Brugerobjekter er ikke registreret."},
    {"ADF-MF-16123", "Logon p\u00E5 applikationsniveau fejlede p\u00E5 grund af manglende autentificeringskontekst."},
    {"ADF-MF-16124", "Fil findes i cachesti"},
    {"ADF-MF-16125", "Kan ikke oprette et katalog til cachen i '%@', fordi en fil allerede findes"},
    {"ADF-MF-16126", "Kunne ikke oprette cachekatalog"},
    {"ADF-MF-16127", "Kunne ikke oprette et katalog til cachen i '%@'"},
    {"ADF-MF-16128", "Kunne ikke krydse cachekatalog"},
    {"ADF-MF-16129", "Visning af cachekatalog fejlede i stien '%@'"},
    {"ADF-MF-16130", "Kunne ikke fjerne cachefil"},
    {"ADF-MF-16131", "Kunne ikke fjerne cachede data i stien '%@'"},
    {"ADF-MF-16132", "G\u00E5r ned nu, fordi konfiguration ikke kunne downloades."},
    {"ADF-MF-16133", "Visning af facilitet fejlede"},
    {"ADF-MF-16134", "Kunne ikke vise facilitet. Fors\u00F8g p\u00E5 at vise faciliteten '%@' fejlede. FEJL: %@"},
    {"ADF-MF-16135", "Fejl i applikations-controller"},
    {"ADF-MF-16136", "Applikations-controller-mappen '%@' findes ikke."},
    {"ADF-MF-16137", "Kunne ikke indl\u00E6se .properties-filen: %@ - FEJL: %@"},
    {"ADF-MF-16138", "Fejl under serialisering af retur: %@"},
    {"ADF-MF-16139", "FeatureId kunne ikke bestemmes. Afbryder kald til Java-klasse."},
    {"ADF-MF-16140", "Verificering af CVM-kanal fejlede."},
    {"ADF-MF-16141", "CVM returnerede en uventet objekttype: %@"},
    {"ADF-MF-16142", "Kan ikke sende meddelelse"},
    {"ADF-MF-16143", "Kunne ikke sende meddelelse, da tekstmeddelelser ikke er tilg\u00E6ngelige p\u00E5 denne enhed."},
    {"ADF-MF-16144", "Kan ikke sende meddelelse, da tekstmeddelelsesopretter ikke kan hentes."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - 'klassenavn' blev ikke angivet"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - morphClassName-kaldet for\u00E5rsagede en FEJL: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - 'klassenavnet' morphClassName fejlede."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - 'metode' blev ikke angivet"},
    {"ADF-MF-16149", "Kunne ikke oprette klasse: %@"},
    {"ADF-MF-16150", "Ny for objekttype fejlede: %@"},
    {"ADF-MF-16151", "Instans af klassen %@ svarer ikke p\u00E5 v\u00E6lgeren '%@'."},
    {"ADF-MF-16152", "Kald af '%@' for\u00E5rsagede fejl: %@"},
    {"ADF-MF-16153", "Serialisering af resultat fra '%@' i typen %@ for\u00E5rsagede FEJL: %@"},
    {"ADF-MF-16154", "Serialisering af resultat fra '%@' i typen %@ genererede nul."},
    {"ADF-MF-16155", "credentialStoreKey for forbindelsen %@ kan ikke v\u00E6re nul"},
    {"ADF-MF-16156", "credentialStoreKey for forbindelse kan ikke v\u00E6re nul"},
    {"ADF-MF-16157", "Generel logon-fejl opstod. Bruger har muligvis indtastet ugyldige ID-oplysninger, eller konfiguration af logon-forbindelse kan indeholde fejl. For eksempel mangler logon-URL og/eller cookie-navn eller er forkert."},
    {"ADF-MF-16158", "Der kan ikke oprettes forbindelse til serveren. Kontroll\u00E9r, at du har forbindelse til internettet."},
    {"ADF-MF-16159", "Fejl i threadShellInitializationComplete: %@"},
    {"ADF-MF-16160", "Fejl i paintMirrorLoop: %@"},
    {"ADF-MF-16161", "ACS er ikke konfigureret til standardforbindelse, og begr\u00E6nsede faciliteter er ikke gjort tilg\u00E6ngelige."},
    {"ADF-MF-16162", "Fejl i brugernavn"},
    {"ADF-MF-16163", "Det anvendte bruger- og/eller tenant-navn er forskelligt fra det oprindelige bruger- og/eller tenant-navn. Du skal korrigere bruger- og/eller tenant-navnet, hvis du har indtastet det forkerte bruger- og/eller tenant-navn. Hvis du skal logge p\u00E5 som en ny bruger, skal du f\u00F8rst afslutte applikationen."},
    {"ADF-MF-16164", "Navn p\u00E5 multi-tenant-overskrift mangler"},
    {"ADF-MF-16165", "Kan ikke autentificere, da der ikke er angivet tilstr\u00E6kkelige oplysninger til autentificering i multi-tenant-applikation. Konfiguration mangler navn p\u00E5 multi-tenant-overskrift. Kontakt administratoren."},
    {"ADF-MF-16166", "Tenant-navn blev ikke indtastet"},
    {"ADF-MF-16167", "Kan ikke autentificere, da tenant-navn ikke blev angivet. Pr\u00F8v igen."},
    {"ADF-MF-16168", "Logon p\u00E5 applikationsniveau fors\u00F8ges. Serveren=%@ for brugeren=%@"},
    {"ADF-MF-16169", "Logon p\u00E5 applikationsniveau er udf\u00F8rt."},
    {"ADF-MF-16170", "OMCredentialStore returnerede ikke egenskab for kSecAttrLabel."},
    {"ADF-MF-16171", "Applikationsbrugerobjekter blev hentet i lager med ID-oplysninger: %@"},
    {"ADF-MF-16172", "Brugerautentificeringstest returnerer %@."},
    {"ADF-MF-16173", "Logon p\u00E5 facilitetsniveau fejlede p\u00E5 grund af uventet betingelse."},
    {"ADF-MF-16174", "Logon-fors\u00F8g p\u00E5 facilitetsniveau for brugeren=%@."},
    {"ADF-MF-16175", "Logout-fors\u00F8g p\u00E5 facilitetsniveau."},
    {"ADF-MF-16176", "Brugerobjekter tr\u00E6kkes, da det er et eksternt facilitets-logon."},
    {"ADF-MF-16177", "Autentificering er udf\u00F8rt."},
    {"ADF-MF-16178", "returnerede brugerobjektsvar=%@"},
    {"ADF-MF-16179", "returnerede brugerobjektprivilegier=%@ roller=%@"},
    {"ADF-MF-16180", "Kalder ACS med payload=%@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: authContext blev ikke hentet."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: pausedFeature blev ikke hentet."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: authContext blev ikke hentet."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: pausedFeature blev ikke hentet."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: authContext blev ikke hentet."},
    {"ADF-MF-16186", "Konfigurationsfejl"},
    {"ADF-MF-16187", "Applikations-logon-forbindelse er ikke defineret. Denne applikation kan ikke k\u00F8re. Kontakt administratoren."},
    {"ADF-MF-16188", "Facilitets-logon-forbindelse er ikke defineret. Der kan ikke oprettes adgang til denne facilitet. Kontakt administratoren."},
    {"ADF-MF-16189", "Logout"},
    {"ADF-MF-16190", "Logout blev initieret. Applikationen afsluttes."},
    {"ADF-MF-16191", "Konfigurationsfejl for logon-forbindelse. {0} Kontakt administratoren."},
    {"ADF-MF-16192", "N\u00F8gle til lager med ID-oplysninger er ikke angivet."},
    {"ADF-MF-16193", "Ugyldig(t) eller manglende brugernavn og/eller adgangskode."},
    {"ADF-MF-16195", "Fejl i sammensat n\u00F8gle til lager med ID-oplysninger."},
    {"ADF-MF-16196", "Ugyldig URL for adgangskontrolservice."},
    {"ADF-MF-16197", "Ugyldig logout-URL."},
    {"ADF-MF-16198", "Ugyldig logon-URL."},
    {"ADF-MF-16199", "Cookie er ikke angivet."},
    {"ADF-MF-16200", "Ledighedstimeout skal v\u00E6re 10 eller st\u00F8rre, sessionstimeout skal v\u00E6re 30 eller st\u00F8rre og st\u00F8rre end ledighedstimeout."},
    {"ADF-MF-16201", "Konfigurationsfejl for logon-forbindelse"},
    {"ADF-MF-16202", "Autentificerings-URL svarede med ulovlig HTTP-svarkode. Det er ikke et slutpunkt for basisautentificering. Kontakt administratoren."},
    {"ADF-MF-16203", "Fil blev ikke fundet: %@"},
    {"ADF-MF-16204", "E-mail-meddelelsen blev ikke sendt eller sat i k\u00F8, muligvis p\u00E5 grund af en fejl."},
    {"ADF-MF-16205", "En fejl opstod under fors\u00F8g p\u00E5 at gemme e-mail-meddelelsen i mappen Kladder."},
    {"ADF-MF-16206", "En fejl opstod under fors\u00F8g p\u00E5 at sende eller s\u00E6tte e-mail-meddelelsen i k\u00F8."},
    {"ADF-MF-16207", "En ukendt fejl opstod under fors\u00F8g p\u00E5 at oprette eller sende en e-mail"},
    {"ADF-MF-16208", "En ukendt fejl opstod under fors\u00F8g p\u00E5 at oprette eller sende en tekstmeddelelse"},
    {"ADF-MF-16209", "Fil blev ikke fundet"},
    {"ADF-MF-16210", "Fandt en ugyldig pr\u00E6fiks til URI-mapping. Pr\u00E6fikset: %@ er allerede mappet til URI'en: %@, gen-mapping af pr\u00E6fikset til URI'en: %@ er ikke tilladt"},
    {"ADF-MF-16211", "Fandt en ugyldig pr\u00E6fiks til URI-mapping. URI'en: %@ er allerede mappet til pr\u00E6fikset: %@, gen-mapping af URI'en til pr\u00E6fikset: %@ er ikke tilladt"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
