// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_hu extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "A(z) %@ oszt\u00E1ly hib\u00E1t id\u00E9zett el\u0151 az alloc \u00E9s init m\u0171veletn\u00E9l - \u00C9letciklus-figyel\u0151 alkalmaz\u00E1s hozz\u00E1ad\u00E1s\u00E1nak megszak\u00EDt\u00E1sa HIBA: %@"},
    {"ADF-MF-16002", "\u00C9rv\u00E9nytelen haszn\u00E1lat"},
    {"ADF-MF-16003", "Ezt a f\u00FCggv\u00E9nyt a f\u0151sz\u00E1lon kell h\u00EDvni."},
    {"ADF-MF-16004", "Ezt a f\u00FCggv\u00E9nyt NEM szabad a f\u0151sz\u00E1lon h\u00EDvni."},
    {"ADF-MF-16005", "Hib\u00E1s konfigur\u00E1ci\u00F3s f\u00E1jl"},
    {"ADF-MF-16006", "\u00C9rv\u00E9nytelen konfigur\u00E1ci\u00F3"},
    {"ADF-MF-16007", "Az AdfmfContainerUtilities megval\u00F3s\u00EDt\u00F3 nincs konfigur\u00E1lva."},
    {"ADF-MF-16008", "Nem tal\u00E1lhat\u00F3 az AdfmfContainerUtilities megval\u00F3s\u00EDt\u00F3 oszt\u00E1lya."},
    {"ADF-MF-16009", "Nem hozhat\u00F3 l\u00E9tre az AdfmfContainerUtilities megval\u00F3s\u00EDt\u00F3."},
    {"ADF-MF-16010", "Hib\u00E1s k\u00E9relem"},
    {"ADF-MF-16011", "Nem t\u00F6lthet\u0151 le f\u00E1jl a 400: Hib\u00E1s k\u00E9relem hiba miatt."},
    {"ADF-MF-16012", "Jogosulatlan"},
    {"ADF-MF-16013", "Nem t\u00F6lthet\u0151 le f\u00E1jl a 401: Jogosulatlan hiba miatt (\u00E9rv\u00E9nytelen felhaszn\u00E1l\u00F3n\u00E9v vagy jelsz\u00F3)."},
    {"ADF-MF-16014", "Tiltott"},
    {"ADF-MF-16015", "Nem t\u00F6lthet\u0151 le f\u00E1jl a 403: Tiltott hiba miatt."},
    {"ADF-MF-16016", "Nem tal\u00E1lhat\u00F3"},
    {"ADF-MF-16017", "Nem t\u00F6lthet\u0151 le f\u00E1jl a 404: Nem tal\u00E1lhat\u00F3 hiba miatt."},
    {"ADF-MF-16018", "Hib\u00E1s \u00E1tj\u00E1r\u00F3"},
    {"ADF-MF-16019", "Nem t\u00F6lthet\u0151 le f\u00E1jl az 502: Hib\u00E1s \u00E1tj\u00E1r\u00F3 hiba miatt."},
    {"ADF-MF-16020", "A szolg\u00E1ltat\u00E1s nem \u00E9rhet\u0151 el"},
    {"ADF-MF-16021", "Nem t\u00F6lthet\u0151 le f\u00E1jl az 503: A szolg\u00E1ltat\u00E1s nem \u00E9rhet\u0151 el hiba miatt."},
    {"ADF-MF-16022", "\u00C9rv\u00E9nytelen argumentum"},
    {"ADF-MF-16023", "\u00DCres csomagn\u00E9v lett \u00E1tadva [oraADFLogger getLogger:] sz\u00E1m\u00E1ra."},
    {"ADF-MF-16024", "Hiba: f\u00E1jl-URL nem lehet \u00FCres"},
    {"ADF-MF-16025", "Tulajdons\u00E1gn\u00E9v nem lehet \u00FCres."},
    {"ADF-MF-16026", "T\u00FAl kev\u00E9s argumentum."},
    {"ADF-MF-16027", "Hi\u00E1nyz\u00F3 oszt\u00E1lyn\u00E9v."},
    {"ADF-MF-16028", "Hi\u00E1nyz\u00F3 met\u00F3dus."},
    {"ADF-MF-16029", "Szolg\u00E1ltat\u00E1s azonos\u00EDt\u00F3ja hi\u00E1nyzik."},
    {"ADF-MF-16030", "Ismeretlen h\u00EDv\u00E1st\u00EDpus"},
    {"ADF-MF-16031", "FeatureContext nem tal\u00E1lhat\u00F3."},
    {"ADF-MF-16032", "V\u00E1ratlan v\u00E1lasz"},
    {"ADF-MF-16033", "A CVM Response \u00FCres v\u00E1laszt adott vissza. "},
    {"ADF-MF-16034", "A CVM Response \u00FCres FeatureContextAccessor \u00E9rt\u00E9ket adott vissza."},
    {"ADF-MF-16035", "A JS Response \u00FCres v\u00E1laszt adott vissza."},
    {"ADF-MF-16036", "Nem k\u00FCldhet\u0151k JavaScript h\u00EDv\u00E1sok a _Control_Channel_ sz\u00E1m\u00E1ra."},
    {"ADF-MF-16037", "Kimeneti-bemeneti hiba"},
    {"ADF-MF-16038", "Hiba f\u00E1jl elt\u00E1vol\u00EDt\u00E1sakor."},
    {"ADF-MF-16039", "Hiba f\u00E1jl m\u00E1sol\u00E1sakor."},
    {"ADF-MF-16040", "V\u00E1rt f\u00E1jl hi\u00E1nyzik."},
    {"ADF-MF-16041", "Hiba f\u00E1jl \u00E1thelyez\u00E9sekor."},
    {"ADF-MF-16042", "Nem hozhat\u00F3 l\u00E9tre k\u00F6nyvt\u00E1r."},
    {"ADF-MF-16043", "Let\u00F6lt\u00E9si hiba"},
    {"ADF-MF-16044", "Nem hozhat\u00F3 l\u00E9tre kapcsolat"},
    {"ADF-MF-16045", "V\u00E1ratlan hiba t\u00F6rt\u00E9nt a f\u00E1jl let\u00F6lt\u00E9sekor."},
    {"ADF-MF-16046", "Hiteles\u00EDt\u00E9si hiba"},
    {"ADF-MF-16047", "Nincs megadva felhaszn\u00E1l\u00F3n\u00E9v vagy jelsz\u00F3."},
    {"ADF-MF-16048", "Hiteles\u00EDt\u00E9si hiba miatt nem t\u00F6lthet\u0151 le f\u00E1jl."},
    {"ADF-MF-16049", "\u00C9rv\u00E9nytelen t\u00E1rol\u00F3dokumentum"},
    {"ADF-MF-16050", "Egy \"feature\" elem fordult el\u0151 akt\u00EDv \"feature\" feldolgoz\u00E1sakor."},
    {"ADF-MF-16051", "A \"_Control_Channel_\" szolg\u00E1ltat\u00E1sazonos\u00EDt\u00F3 \u00FCtk\u00F6zik a VM csatorna fenntartott azonos\u00EDt\u00F3nev\u00E9vel"},
    {"ADF-MF-16052", "Az \"OracleAdfmfFeature\" oszt\u00E1ly helytelen elemt\u00EDpussal lett inicializ\u00E1lva."},
    {"ADF-MF-16053", "Hib\u00E1s \u00E1llapot"},
    {"ADF-MF-16054", "F\u00E1jl-URL nem lehet \u00FCres"},
    {"ADF-MF-16055", "K\u00EDs\u00E9rlet olyan objektum hozz\u00E1ad\u00E1s\u00E1ra, amely nem ASIHTTPRequest egy ASINetworkQueue sz\u00E1m\u00E1ra"},
    {"ADF-MF-16056", "N\u00E9vjegy-l\u00E9trehoz\u00E1si hiba"},
    {"ADF-MF-16057", "N\u00E9vjegy-elt\u00E1vol\u00EDt\u00E1si hiba"},
    {"ADF-MF-16058", "\u00C9rv\u00E9nytelen argumentum hiba"},
    {"ADF-MF-16059", "Id\u0151t\u00FAll\u00E9p\u00E9si hiba"},
    {"ADF-MF-16060", "F\u00FCgg\u0151ben l\u00E9v\u0151 m\u0171velet hiba"},
    {"ADF-MF-16061", "\u00CDr\u00E1si-olvas\u00E1si hiba"},
    {"ADF-MF-16062", "Nem t\u00E1mogatott hiba"},
    {"ADF-MF-16063", "Enged\u00E9ly megtagadva hiba"},
    {"ADF-MF-16064", "Ismeretlen hiba"},
    {"ADF-MF-16066", "\u00C9rv\u00E9nytelen oszt\u00E1ly"},
    {"ADF-MF-16067", "Az oszt\u00E1lyb\u00F3l hi\u00E1nyzik egy el\u0151\u00EDrt f\u00FCggv\u00E9ny megval\u00F3s\u00EDt\u00E1sa. Az oszt\u00E1lyra vonatkoz\u00F3 adatok napl\u00F3z\u00E1s\u00E1hoz enged\u00E9lyezze a hibakeres\u00E9st."},
    {"ADF-MF-16068", "Nem tal\u00E1lhat\u00F3 a szolg\u00E1ltat\u00E1sn\u00E9zet oszt\u00E1lya."},
    {"ADF-MF-16069", "Nem hozhat\u00F3 l\u00E9tre a szolg\u00E1ltat\u00E1sn\u00E9zet oszt\u00E1lya."},
    {"ADF-MF-16070", "A n\u00E9zetvez\u00E9rl\u0151 \u00FCres n\u00E9zetet adott a szolg\u00E1ltat\u00E1sn\u00E9zethez."},
    {"ADF-MF-16071", "Az oszt\u00E1ly nem \u00E9rv\u00E9nyes n\u00E9zett\u00EDpus. A jelenleg t\u00E1mogatott r\u00E9szoszt\u00E1lyok eredete UIView vagy UIViewController lehet."},
    {"ADF-MF-16072", "Nem tal\u00E1lhat\u00F3 egy szolg\u00E1ltat\u00E1shoz tartoz\u00F3 HttpURLConnection."},
    {"ADF-MF-16073", "Egy szolg\u00E1ltat\u00E1shoz tartoz\u00F3 HttpURLConnection \u00FCres URL-c\u00EDmet tartalmaz."},
    {"ADF-MF-16074", "\u00C9rv\u00E9nytelen \u00FCzenet"},
    {"ADF-MF-16075", "Az \u00FCzenet ismeretlen \u00FCzenett\u00EDpust adott meg."},
    {"ADF-MF-16076", "Bejelentkez\u00E9si hiba"},
    {"ADF-MF-16077", "Konfigur\u00E1ci\u00F3s hiba"},
    {"ADF-MF-16078", " UIWebView bet\u00F6lt\u00E9si hib\u00E1ja"},
    {"ADF-MF-16079", " Sikertelen a(z) \"%@\" szolg\u00E1ltat\u00E1s bet\u00F6lt\u00E9se, URL: %@"},
    {"ADF-MF-16080", "Forduljon a rendszergazd\u00E1hoz."},
    {"ADF-MF-16081", "Nem \u00E9rhet\u0151 el a bejelentkez\u00E9si kiszolg\u00E1l\u00F3."},
    {"ADF-MF-16082", "\u00C9rv\u00E9nytelen felhaszn\u00E1l\u00F3n\u00E9v/jelsz\u00F3. Ha a hiba nem sz\u0171nik meg, l\u00E9pjen kapcsolatba a rendszergazd\u00E1val."},
    {"ADF-MF-16083", "Konfigur\u00E1l\u00E1si hiba. Forduljon a rendszergazd\u00E1hoz. "},
    {"ADF-MF-16084", "ACS sikertelen"},
    {"ADF-MF-16085", "\u00C9rv\u00E9nytelen ACS-konfigur\u00E1ci\u00F3. A felhaszn\u00E1l\u00F3i objektum nem lett megfelel\u0151en lek\u00E9rve az ACS konfigur\u00E1l\u00E1si hib\u00E1ja miatt. Lehet, hogy a felhaszn\u00E1l\u00F3 nem regisztr\u00E1lt az ACS kiszolg\u00E1l\u00F3n. Forduljon a rendszergazd\u00E1hoz."},
    {"ADF-MF-16086", "A kiszolg\u00E1l\u00F3 nem \u00E9rhet\u0151 el. \u00DCgyeljen arra, hogy k\u00E9sz\u00FCl\u00E9ke csatlakoztatva legyen az internethez."},
    {"ADF-MF-16087", "\u00C9rv\u00E9nytelen felhaszn\u00E1l\u00F3n\u00E9v/jelsz\u00F3. Pr\u00F3b\u00E1lja meg \u00FAjra."},
    {"ADF-MF-16088", "Konfigur\u00E1l\u00E1si hiba. Hi\u00E1nyzik a hozz\u00E1f\u00E9r\u00E9s-szab\u00E1lyoz\u00E1si szolg\u00E1ltat\u00E1s URL-c\u00EDme. Forduljon a rendszergazd\u00E1hoz."},
    {"ADF-MF-16089", "El\u00E9rte a bejelentkez\u00E9si k\u00EDs\u00E9rletek maxim\u00E1lis sz\u00E1m\u00E1t. Most ki lett z\u00E1rva. Forduljon a rendszergazd\u00E1hoz."},
    {"ADF-MF-16090", "Nem hajthat\u00F3 v\u00E9gre a konfigur\u00E1ci\u00F3s v\u00E1ltoztat\u00E1sok keres\u00E9se. Ellen\u0151rizze a h\u00E1l\u00F3zati kapcsolatot, vagy forduljon a rendszergazd\u00E1hoz."},
    {"ADF-MF-16091", "Nem friss\u00EDthet\u0151k a konfigur\u00E1ci\u00F3k a konfigur\u00E1l\u00E1si szolg\u00E1ltat\u00E1sb\u00F3l."},
    {"ADF-MF-16092", "Helytelen form\u00E1tum\u00FA \u00FCzenet"},
    {"ADF-MF-16093", "\u00DCres k\u00E9relem\u00FCzenet nem megengedett."},
    {"ADF-MF-16094", "Nem t\u00E1mogatott \u00FCzenet"},
    {"ADF-MF-16095", "Rendszer\u00FCzenetek nem haszn\u00E1lhat\u00F3k ezen a csatorn\u00E1n"},
    {"ADF-MF-16096", "\u00C9rv\u00E9nytelen rendszerk\u00E9relem: %@"},
    {"ADF-MF-16097", "Alkalmaz\u00E1s\u00FCzenetek nem haszn\u00E1lhat\u00F3k ezen a csatorn\u00E1n"},
    {"ADF-MF-16098", "\u00C9rv\u00E9nytelen alkalmaz\u00E1sk\u00E9relem: %@"},
    {"ADF-MF-16099", "Nem kezelt \u00FCzenet"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Type: %d Body: %@"},
    {"ADF-MF-16101", "K\u00E9retlen v\u00E1lasz\u00FCzenet \u00E9rkezett"},
    {"ADF-MF-16102", "Ismeretlen \u00FCzenett\u00EDpus \u00E9rkezett"},
    {"ADF-MF-16103", "AdfChannel.handle - Hiba a VMChannel \u00FCzenet kezel\u00E9sekor: %@ - HIBA: %@"},
    {"ADF-MF-16104", "Nem lett \"%@\" megadva. \u00C1tadott hiba: \"%@\""},
    {"ADF-MF-16105", "Eszk\u00F6zhozz\u00E1f\u00E9r\u00E9s letiltva a(z) \"%@\" szolg\u00E1ltat\u00E1sn\u00E1l: url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16106", "Nem enged\u00E9lyezett URL az eszk\u00F6zhozz\u00E1f\u00E9r\u00E9shez a(z) \"%@\" szolg\u00E1ltat\u00E1sn\u00E1l: url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16107", "HIBA a Whitelist sor\u00E1n: %@"},
    {"ADF-MF-16108", "Nem k\u00FCldhet\u0151 el a m\u00F3dos\u00EDtott sz\u00E9less\u00E9g/magass\u00E1g a Java oldalra"},
    {"ADF-MF-16109", "Nem lehet regisztr\u00E1lni v\u00E1ltoz\u00E1sesem\u00E9nyeket a h\u00E1l\u00F3zat \u00E1llapot\u00E1hoz. A h\u00E1l\u00F3zat \u00E1llapota nem lesz el\u00E9rhet\u0151"},
    {"ADF-MF-16110", "Nincs defini\u00E1lva az alap\u00E9rtelmez\u00E9s szerinti bejelentkez\u00E9si kapcsolat: \"%@\"."},
    {"ADF-MF-16111", "Hi\u00E1nyzik egy csal\u00E1d a(z) \"%@\" grafikus fel\u00FCletn\u00E9l. Figyelmen k\u00EDv\u00FCl hagyva."},
    {"ADF-MF-16112", "A grafikus fel\u00FClet akt\u00EDv \"%@\" csal\u00E1dja nem adott vissza grafikus fel\u00FCletet."},
    {"ADF-MF-16113", "A(z) %@ mell\u00E9klet nem tal\u00E1lhat\u00F3 vagy nem olvashat\u00F3"},
    {"ADF-MF-16114", "A(z) %@ nem t\u00E1mogatja a k\u00F6vetkez\u0151t: deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "%@ nincs defini\u00E1lva a WebView rendszerben. JavaScript eredm\u00E9nyh\u00EDv\u00E1s megszak\u00EDtva."},
    {"ADF-MF-16116", "Nem siker\u00FClt a(z) \"%@\" f\u00FCggv\u00E9ny h\u00EDv\u00E1sa: %@"},
    {"ADF-MF-16117", "HIBA: kiv\u00E9tel t\u00F6rt\u00E9nt a(z) %d visszah\u00EDv\u00E1s v\u00E9grehajt\u00E1sakor: %@"},
    {"ADF-MF-16118", "Alkalmaz\u00E1s hiteles\u00EDt\u00E9si hib\u00E1ja. Ok = %@"},
    {"ADF-MF-16119", "Szolg\u00E1ltat\u00E1s hiteles\u00EDt\u00E9si hib\u00E1ja. Szolg\u00E1ltat\u00E1s letiltva. Ok = %@"},
    {"ADF-MF-16120", "Hiteles\u00EDt\u00E9si hiba. Pr\u00F3b\u00E1lja \u00FAjra."},
    {"ADF-MF-16121", "Az ACS hib\u00E1t adott vissza: %@"},
    {"ADF-MF-16122", "Nincs ACS konfigur\u00E1lva ehhez a kapcsolathoz: %@. Nincsenek regisztr\u00E1lva felhaszn\u00E1l\u00F3i objektumok."},
    {"ADF-MF-16123", "Alkalmaz\u00E1sszint\u0171 bejelentkez\u00E9s hi\u00E1nyz\u00F3 hiteles\u00EDt\u00E9si k\u00F6rnyezet miatt sikertelen."},
    {"ADF-MF-16124", "M\u00E1r l\u00E9tezik f\u00E1jl a gyors\u00EDt\u00F3t\u00E1r el\u00E9r\u00E9si \u00FAtvonal\u00E1n"},
    {"ADF-MF-16125", "Nem hozhat\u00F3 l\u00E9tre k\u00F6nyvt\u00E1r a gyors\u00EDt\u00F3t\u00E1rhoz itt: \"%@\", mivel ott m\u00E1r l\u00E9tezik f\u00E1jl"},
    {"ADF-MF-16126", "Nem siker\u00FClt l\u00E9trehozni gyors\u00EDt\u00F3t\u00E1ri k\u00F6nyvt\u00E1rat"},
    {"ADF-MF-16127", "Nem siker\u00FClt k\u00F6nyvt\u00E1rat l\u00E9trehozni a gyors\u00EDt\u00F3t\u00E1rhoz itt: \"%@\""},
    {"ADF-MF-16128", "Nem siker\u00FClt bej\u00E1rni a gyors\u00EDt\u00F3t\u00E1r k\u00F6nyvt\u00E1r\u00E1t"},
    {"ADF-MF-16129", "Gyors\u00EDt\u00F3t\u00E1ri k\u00F6nyvt\u00E1r list\u00E1z\u00E1sa sikertelen ezen az el\u00E9r\u00E9si \u00FAtvonalon: \"%@\""},
    {"ADF-MF-16130", "Nem siker\u00FClt elt\u00E1vol\u00EDtani a gyors\u00EDt\u00F3t\u00E1ri f\u00E1jlt"},
    {"ADF-MF-16131", "Nem siker\u00FClt elt\u00E1vol\u00EDtani a gyors\u00EDt\u00F3t\u00E1razott adatokat ezen az el\u00E9r\u00E9si \u00FAtvonalon: \"%@\""},
    {"ADF-MF-16132", "\u00D6sszeoml\u00E1s, mivel nem t\u00F6lthet\u0151 le konfigur\u00E1ci\u00F3."},
    {"ADF-MF-16133", "Szolg\u00E1ltat\u00E1s megjelen\u00EDt\u00E9se sikertelen"},
    {"ADF-MF-16134", "Szolg\u00E1ltat\u00E1s nem jelen\u00EDthet\u0151 meg. A(z) \"%@\" szolg\u00E1ltat\u00E1s megjelen\u00EDt\u00E9si k\u00EDs\u00E9rlete sikertelen. HIBA: %@"},
    {"ADF-MF-16135", "Alkalmaz\u00E1svez\u00E9rl\u0151i hiba"},
    {"ADF-MF-16136", "Nem l\u00E9tezik az alkalmaz\u00E1svez\u00E9rl\u0151  '%@'  nev\u0171 mapp\u00E1ja."},
    {"ADF-MF-16137", "Nem siker\u00FClt bet\u00F6lteni a .properties f\u00E1jlt: %@ - HIBA: %@"},
    {"ADF-MF-16138", "Hiba a soros adatt\u00E1 alak\u00EDt\u00E1sakor, visszat\u00E9r\u00E9si \u00E9rt\u00E9k: %@"},
    {"ADF-MF-16139", "Nem \u00E1llap\u00EDthat\u00F3 meg a FeatureId. A Java oszt\u00E1ly h\u00EDv\u00E1sa megszakad."},
    {"ADF-MF-16140", "A CVM csatorna ellen\u0151rz\u00E9se sikertelen."},
    {"ADF-MF-16141", "A CVM v\u00E1ratlan objektumt\u00EDpust adott vissza: %@"},
    {"ADF-MF-16142", "\u00DCzenet k\u00FCld\u00E9se sikertelen"},
    {"ADF-MF-16143", "Nem lehet \u00FCzenetet k\u00FCldeni, mivel az \u00FCzenetk\u00FCld\u00E9s nem el\u00E9rhet\u0151 ezen a k\u00E9sz\u00FCl\u00E9ken."},
    {"ADF-MF-16144", "Nem lehet \u00FCzenetet k\u00FCldeni, mivel nem olvashat\u00F3 be a sz\u00F6veges\u00FCzenet-szerkeszt\u0151."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Az 'oszt\u00E1lyn\u00E9v' nem volt megadva"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - A morphClassName h\u00EDv\u00E1s HIB\u00C1T okozott: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - A morphClassName 'oszt\u00E1lyn\u00E9v' nem volt megfelel\u0151"},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - A 'met\u00F3dus' nem volt megadva"},
    {"ADF-MF-16149", "Nem hozhat\u00F3 l\u00E9tre az oszt\u00E1ly: %@"},
    {"ADF-MF-16150", "Sikertelen \u00FAj p\u00E9ld\u00E1ny l\u00E9trehoz\u00E1sa az objektumt\u00EDpusban: %@"},
    {"ADF-MF-16151", "A(z) %@ oszt\u00E1ly p\u00E9ld\u00E1nya nem v\u00E1laszol a(z) '%@' v\u00E1laszt\u00F3ra."},
    {"ADF-MF-16152", "'%@' megh\u00EDv\u00E1sa hib\u00E1t okozott: %@"},
    {"ADF-MF-16153", "A(z) '%@' eredm\u00E9ny\u00E9nek soros adatt\u00E1 alak\u00EDt\u00E1sa a(z) %@ t\u00EDpusban HIB\u00C1T okozott: %@"},
    {"ADF-MF-16154", "A(z) '%@' eredm\u00E9ny\u00E9nek soros adatt\u00E1 alak\u00EDt\u00E1sa a(z) %@ t\u00EDpusban \u00FCres \u00E9rt\u00E9ket gener\u00E1lt."},
    {"ADF-MF-16155", "A(z) %@ kapcsolat credentialStoreKey \u00E9rt\u00E9ke nem lehet \u00FCres"},
    {"ADF-MF-16156", "A kapcsolat credentialStoreKey \u00E9rt\u00E9ke nem lehet \u00FCres"},
    {"ADF-MF-16157", "\u00C1ltal\u00E1nos bejelentkez\u00E9si hiba t\u00F6rt\u00E9nt. Lehet, hogy a felhaszn\u00E1l\u00F3 \u00E9rv\u00E9nytelen azonos\u00EDt\u00F3adatokat adott meg, vagy a bejelentkez\u00E9si kapcsolat hib\u00E1t tartalmaz. P\u00E9ld\u00E1ul hi\u00E1nyzik vagy rossz a bejelentkez\u00E9si URL-c\u00EDm \u00E9s/vagy a cookie neve."},
    {"ADF-MF-16158", "A kiszolg\u00E1l\u00F3 nem \u00E9rhet\u0151 el. \u00DCgyeljen arra, hogy csatlakoztatva legyen az internethez."},
    {"ADF-MF-16159", "Hiba a threadShellInitializationComplete sz\u00E1lban: %@"},
    {"ADF-MF-16160", "Hiba itt: paintMirrorLoop: %@"},
    {"ADF-MF-16161", "Az ACS nem lett konfigur\u00E1lva az alap\u00E9rtelmezett kapcsolathoz, \u00E9s a korl\u00E1tozott szolg\u00E1ltat\u00E1sok nem lettek el\u00E9rhet\u0151v\u00E9 t\u00E9ve."},
    {"ADF-MF-16162", "Hiba a felhaszn\u00E1l\u00F3n\u00E9vben"},
    {"ADF-MF-16163", "A haszn\u00E1lt felhaszn\u00E1l\u00F3n\u00E9v \u00E9s/vagy b\u00E9rl\u0151n\u00E9v elt\u00E9r az eredeti felhaszn\u00E1l\u00F3n\u00E9vt\u0151l \u00E9s/vagy b\u00E9rl\u0151n\u00E9vt\u0151l. Ha rossz felhaszn\u00E1l\u00F3nevet \u00E9s/vagy b\u00E9rl\u0151nevet adott meg, akkor azt ki kell jav\u00EDtani. Az \u00FAj felhaszn\u00E1l\u00F3k\u00E9nt t\u00F6rt\u00E9n\u0151 bejelentkez\u00E9shez el\u0151sz\u00F6r ki kell l\u00E9pni az alkalmaz\u00E1sb\u00F3l."},
    {"ADF-MF-16164", "Hi\u00E1nyzik a t\u00F6bb csom\u00F3ponti p\u00E9ld\u00E1ny fejl\u00E9c\u00E9nek neve"},
    {"ADF-MF-16165", "Nem hiteles\u00EDthet\u0151, mivel nem adtak meg elegend\u0151 adatot a t\u00F6bb b\u00E9rl\u0151s alkalmaz\u00E1sban. A konfigur\u00E1l\u00E1sban hi\u00E1nyzik a t\u00F6bb b\u00E9rl\u0151s fejl\u00E9c neve. Forduljon a rendszergazd\u00E1hoz."},
    {"ADF-MF-16166", "A csom\u00F3ponti p\u00E9ld\u00E1ny neve nem lett megadva"},
    {"ADF-MF-16167", "Nem hiteles\u00EDthet\u0151, mivel rossz csom\u00F3ponti p\u00E9ld\u00E1ny lett megadva. Pr\u00F3b\u00E1lja meg \u00FAjra."},
    {"ADF-MF-16168", "Alkalmaz\u00E1s szint\u0171 bejelentkez\u00E9sre t\u00F6rt\u00E9nt k\u00EDs\u00E9rlet. Kiszolg\u00E1l\u00F3=%@ felhaszn\u00E1l\u00F3=%@"},
    {"ADF-MF-16169", "Sikeres az alkalmaz\u00E1sszint\u0171 bejelentkez\u00E9s."},
    {"ADF-MF-16170", "Az OMCredentialStore nem t\u00E9r\u00EDtett vissza tulajdons\u00E1got a kSecAttrLabel r\u00E9sz\u00E9re."},
    {"ADF-MF-16171", "Az alkalmaz\u00E1s felhaszn\u00E1l\u00F3i objektumai be lettek olvasva az azonos\u00EDt\u00F3adatok t\u00E1rol\u00F3j\u00E1b\u00F3l: %@"},
    {"ADF-MF-16172", "A felhaszn\u00E1l\u00F3 hiteles\u00EDt\u00E9si tesztj\u00E9nek visszat\u00E9r\u00E9si \u00E9rt\u00E9ke: %@."},
    {"ADF-MF-16173", "A szolg\u00E1ltat\u00E1s szint\u0171 bejelentkez\u00E9s v\u00E1ratlan felt\u00E9tel miatt sikertelen."},
    {"ADF-MF-16174", "Szolg\u00E1ltat\u00E1s szint\u0171 bejelentkez\u00E9si k\u00EDs\u00E9rlet, ha felhaszn\u00E1l\u00F3 %@."},
    {"ADF-MF-16175", "Szolg\u00E1ltat\u00E1s szint\u0171 kijelentkez\u00E9si k\u00EDs\u00E9rlet."},
    {"ADF-MF-16176", "A felhaszn\u00E1l\u00F3i objektumok tov\u00E1bbad\u00F3dnak, mivel ez bejelentkez\u00E9s t\u00E1voli szolg\u00E1ltat\u00E1sra."},
    {"ADF-MF-16177", "Sikeres a hiteles\u00EDt\u00E9s."},
    {"ADF-MF-16178", "felhaszn\u00E1l\u00F3i objektumok visszat\u00E9r\u00EDtett v\u00E1lasza=%@"},
    {"ADF-MF-16179", "felhaszn\u00E1l\u00F3i objektumok visszat\u00E9r\u00EDtett jogosults\u00E1gai=%@ szerepk\u00F6rei=%@"},
    {"ADF-MF-16180", "ACS megh\u00EDv\u00E1sa adatt\u00F6rzzsel=%@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: Az authContext megszerz\u00E9se nem siker\u00FClt."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: A pausedFeature megszerz\u00E9se nem siker\u00FClt."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: Az authContext megszerz\u00E9se nem siker\u00FClt."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: A pausedFeature megszerz\u00E9se nem siker\u00FClt."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: Az authContext megszerz\u00E9se nem siker\u00FClt."},
    {"ADF-MF-16186", "Konfigur\u00E1ci\u00F3s hiba"},
    {"ADF-MF-16187", "Az alkalmaz\u00E1s bejelentkez\u00E9si kapcsolata nincs meghat\u00E1rozva. Ezt az alkalmaz\u00E1st nem lehet futtatni. L\u00E9pjen kapcsolatba a rendszergazd\u00E1val."},
    {"ADF-MF-16188", "A szolg\u00E1ltat\u00E1s bejelentkez\u00E9si kapcsolata nincs meghat\u00E1rozva. Ezt a szolg\u00E1ltat\u00E1st nem lehet el\u00E9rni. L\u00E9pjen kapcsolatba a rendszergazd\u00E1val."},
    {"ADF-MF-16189", "Kijelentkez\u00E9s"},
    {"ADF-MF-16190", "Kijelentkez\u00E9st kezdem\u00E9nyeztek. Az alkalmaz\u00E1s le\u00E1ll."},
    {"ADF-MF-16191", "Bejelentkez\u00E9si kapcsolat konfigur\u00E1l\u00E1si hib\u00E1ja. {0} L\u00E9pjen kapcsolatba a rendszergazd\u00E1val."},
    {"ADF-MF-16192", "Az azonos\u00EDt\u00F3adat-t\u00E1r kulcs nincs megadva."},
    {"ADF-MF-16193", "\u00C9rv\u00E9nytelen vagy hi\u00E1nyzik a felhaszn\u00E1l\u00F3n\u00E9v \u00E9s/vagy a jelsz\u00F3."},
    {"ADF-MF-16195", "Hiba az \u00F6sszetett azonos\u00EDt\u00F3adat-t\u00E1r kulcsban."},
    {"ADF-MF-16196", "\u00C9rv\u00E9nytelen hozz\u00E1f\u00E9r\u00E9s-szab\u00E1lyoz\u00E1si szolg\u00E1ltat\u00E1s URL."},
    {"ADF-MF-16197", "\u00C9rv\u00E9nytelen kijelentkez\u00E9si URL."},
    {"ADF-MF-16198", "\u00C9rv\u00E9nytelen bejelentkez\u00E9si URL."},
    {"ADF-MF-16199", "Nincs megadva a cookie."},
    {"ADF-MF-16200", "Az \u00FCresj\u00E1rati id\u0151t\u00FAll\u00E9p\u00E9s 10 vagy nagyobb \u00E9rt\u00E9k lehet, a munkamenet id\u0151t\u00FAll\u00E9p\u00E9se 30 vagy nagyobb \u00E9rt\u00E9k lehet, \u00E9s nagyobbnak kell lennie az \u00FCresj\u00E1rati id\u0151t\u00FAll\u00E9p\u00E9sn\u00E9l."},
    {"ADF-MF-16201", "Bejelentkez\u00E9si kapcsolat konfigur\u00E1l\u00E1si hib\u00E1ja"},
    {"ADF-MF-16202", "A hiteles\u00EDt\u00E9si URL \u00E9rv\u00E9nytelen HTTP v\u00E1laszk\u00F3ddal v\u00E1laszolt. A c\u00EDm nem alapszint\u0171 hiteles\u00EDt\u00E9si v\u00E9gpont. L\u00E9pjen kapcsolatba a rendszergazd\u00E1val."},
    {"ADF-MF-16203", "Nem tal\u00E1lhat\u00F3 a f\u00E1jl: %@"},
    {"ADF-MF-16204", "Val\u00F3sz\u00EDn\u0171leg egy hiba miatt az e-mail \u00FCzenetet nem lehetett elmenteni vagy sorba \u00E1ll\u00EDtani."},
    {"ADF-MF-16205", "Hiba t\u00F6rt\u00E9nt az e-mail \u00FCzenet Piszkozatok mapp\u00E1ba val\u00F3 ment\u00E9sekor."},
    {"ADF-MF-16206", "Hiba t\u00F6rt\u00E9nt az e-mail \u00FCzenet sorba \u00E1ll\u00EDt\u00E1sa vagy k\u00FCld\u00E9se k\u00F6zben."},
    {"ADF-MF-16207", "Ismeretlen hiba t\u00F6rt\u00E9nt az e-mail \u00FCzenet \u00EDr\u00E1sa vagy k\u00FCld\u00E9se k\u00F6zben"},
    {"ADF-MF-16208", "Ismeretlen hiba t\u00F6rt\u00E9nt a sz\u00F6veges \u00FCzenet \u00EDr\u00E1sa vagy k\u00FCld\u00E9se k\u00F6zben"},
    {"ADF-MF-16209", "A f\u00E1jl nem tal\u00E1lhat\u00F3"},
    {"ADF-MF-16210", "A rendszer \u00E9rv\u00E9nytelen el\u0151tagot \u00E9szlelt az URI-hozz\u00E1rendel\u00E9sn\u00E9l. A(z) %@ el\u0151tag m\u00E1r hozz\u00E1 van rendelve a(z) %@ URI-hoz, az el\u0151tag %@ URI-hoz val\u00F3 hozz\u00E1rendel\u00E9se nem enged\u00E9lyezett"},
    {"ADF-MF-16211", "A rendszer \u00E9rv\u00E9nytelen el\u0151tagot \u00E9szlelt az URI-hozz\u00E1rendel\u00E9sn\u00E9l. A(z) %@ URI m\u00E1r hozz\u00E1 van rendelve a(z) %@ el\u0151taghoz, az URI %@ el\u0151taghoz val\u00F3 hozz\u00E1rendel\u00E9se nem enged\u00E9lyezett"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
