// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_no extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "Klassen %@ genererte en feil da den ble fordelt og initialisert - avbryter tilf\u00F8ying av Application Lifecycle Listener - FEIL: %@"},
    {"ADF-MF-16002", "Ugyldig bruk"},
    {"ADF-MF-16003", "Denne funksjonen m\u00E5 kalles p\u00E5 hovedtr\u00E5den."},
    {"ADF-MF-16004", "Denne funksjonen m\u00E5 IKKE kalles p\u00E5 hovedtr\u00E5den."},
    {"ADF-MF-16005", "Ugyldig konfigurasjonsfil"},
    {"ADF-MF-16006", "Ugyldig konfigurasjon"},
    {"ADF-MF-16007", "AdfmfContainerUtilities-implementereren er ikke konfigurert."},
    {"ADF-MF-16008", "Finner ikke klassen for AdfmfContainerUtilities-implementereren."},
    {"ADF-MF-16009", "Kan ikke opprette AdfmfContainerUtilities-implementereren."},
    {"ADF-MF-16010", "Ugyldig foresp\u00F8rsel"},
    {"ADF-MF-16011", "Kan ikke laste ned filen p\u00E5 grunn av 400 - Ugyldig foresp\u00F8rsel."},
    {"ADF-MF-16012", "Uautorisert"},
    {"ADF-MF-16013", "Kan ikke laste ned filen p\u00E5 grunn av 401 - Uautorisert (ugyldig brukernavn eller passord)."},
    {"ADF-MF-16014", "Forbudt"},
    {"ADF-MF-16015", "Kan ikke laste ned filen p\u00E5 grunn av 403 - Forbudt."},
    {"ADF-MF-16016", "Ikke funnet"},
    {"ADF-MF-16017", "Kan ikke laste ned filen p\u00E5 grunn av 404 - Ikke funnet."},
    {"ADF-MF-16018", "Ugyldig innfallsport"},
    {"ADF-MF-16019", "Kan ikke laste ned filen p\u00E5 grunn av 502 - Ugyldig innfallsport."},
    {"ADF-MF-16020", "Tjenesten er utilgjengelig"},
    {"ADF-MF-16021", "Kan ikke laste ned filen p\u00E5 grunn av 503 - Tjenesten er utilgjengelig."},
    {"ADF-MF-16022", "Ugyldig argument"},
    {"ADF-MF-16023", "Et nullpakkenavn ble sendt til [oraADFLogger getLogger:]."},
    {"ADF-MF-16024", "URL-adressen til feilfilen kan ikke v\u00E6re null"},
    {"ADF-MF-16025", "Egenskapsnavnet kan ikke v\u00E6re null."},
    {"ADF-MF-16026", "For f\u00E5 argumenter."},
    {"ADF-MF-16027", "Manglende klassenavn."},
    {"ADF-MF-16028", "Manglende metode."},
    {"ADF-MF-16029", "Funksjons-ID mangler."},
    {"ADF-MF-16030", "Ukjent type kall"},
    {"ADF-MF-16031", "Finner ikke FeatureContext."},
    {"ADF-MF-16032", "Uventet svar"},
    {"ADF-MF-16033", "CVM-svaret returnerte et nullsvar. "},
    {"ADF-MF-16034", "CVM-svaret returnerte null FeatureContextAccessor."},
    {"ADF-MF-16035", "JS-svaret returnerte null svar."},
    {"ADF-MF-16036", "Kan ikke sende JavaScript-kall til _Control_Channel_."},
    {"ADF-MF-16037", "I/U-feil"},
    {"ADF-MF-16038", "Feil ved fjerning av fil."},
    {"ADF-MF-16039", "Feil ved kopiering av fil."},
    {"ADF-MF-16040", "Forventet fil mangler."},
    {"ADF-MF-16041", "Feil ved flytting av fil."},
    {"ADF-MF-16042", "Kan ikke opprette katalogen."},
    {"ADF-MF-16043", "Nedlastingsfeil"},
    {"ADF-MF-16044", "Kan ikke opprette tilkoblingen"},
    {"ADF-MF-16045", "Det oppstod en uventet feil ved nedlasting av filen."},
    {"ADF-MF-16046", "Autentiseringsfeil"},
    {"ADF-MF-16047", "Brukernavn eller passord mangler."},
    {"ADF-MF-16048", "Kan ikke laste ned filen p\u00E5 grunn av autentiseringsfeil."},
    {"ADF-MF-16049", "Ugyldig beholderdokument"},
    {"ADF-MF-16050", "Fant elementet feature mens et aktivt feature-element var under behandling."},
    {"ADF-MF-16051", "Funksjons-ID-en, _Control_Channel_, er i konflikt med et reservert VM-kanalidentifikatornavn"},
    {"ADF-MF-16052", "Klassen OracleAdfmfFeature ble initialisert med en feil elementtype."},
    {"ADF-MF-16053", "Feil tilstand"},
    {"ADF-MF-16054", "URL-adressen til filen kan ikke v\u00E6re null"},
    {"ADF-MF-16055", "Fors\u00F8kte \u00E5 legge til et objekt som ikke var ASIHTTPRequest, i ASINetworkQueue"},
    {"ADF-MF-16056", "Feil ved opprettelse av kontaktperson"},
    {"ADF-MF-16057", "Feil ved fjerning av kontaktperson"},
    {"ADF-MF-16058", "Feil p\u00E5 grunn av ugyldig argument"},
    {"ADF-MF-16059", "Tidsavbruddsfeil"},
    {"ADF-MF-16060", "Feil i forbindelse med ventende operasjon"},
    {"ADF-MF-16061", "I/U-feil"},
    {"ADF-MF-16062", "Feil p\u00E5 grunn av manglende st\u00F8tte"},
    {"ADF-MF-16063", "Feil p\u00E5 grunn av manglende tillatelse"},
    {"ADF-MF-16064", "Ukjent feil"},
    {"ADF-MF-16066", "Ugyldig klasse"},
    {"ADF-MF-16067", "Klassen mangler en implementering av en n\u00F8dvendig funksjon. Aktiver feilleting hvis du vil logge opplysninger om klassen."},
    {"ADF-MF-16068", "Finner ikke funksjonsvisningsklassen."},
    {"ADF-MF-16069", "Kan ikke opprette funksjonsvisningsklassen."},
    {"ADF-MF-16070", "Visningskontrolleren gav en nullvisning for funksjonsvisningen."},
    {"ADF-MF-16071", "Klassen er ikke en gyldig visningstype. Underklasser som st\u00F8ttes for \u00F8yeblikket, m\u00E5 v\u00E6re fra UIView eller UIViewController"},
    {"ADF-MF-16072", "Finner ikke HttpURLConnection som brukes av en funksjon."},
    {"ADF-MF-16073", "HttpURLConnection som brukes av en funksjon, har en null-URL-adresse."},
    {"ADF-MF-16074", "Ugyldig melding"},
    {"ADF-MF-16075", "Ukjent meldingstype angitt av meldingen."},
    {"ADF-MF-16076", "P\u00E5loggingsfeil"},
    {"ADF-MF-16077", "Konfigurasjonsfeil"},
    {"ADF-MF-16078", " Feil ved innlasting av UIWebView"},
    {"ADF-MF-16079", " Kan ikke laste funksjonen %@, URL-adresse: %@"},
    {"ADF-MF-16080", "Kontakt administratoren."},
    {"ADF-MF-16081", "P\u00E5loggingstjeneren kan ikke n\u00E5s."},
    {"ADF-MF-16082", "Ugyldig brukernavn/passord. Kontakt systemansvarlig hvis problemet vedvarer."},
    {"ADF-MF-16083", "Konfigurasjonsfeil. Kontakt administratoren. "},
    {"ADF-MF-16084", "ACS mislyktes"},
    {"ADF-MF-16085", "Ugyldig ACS-konfigurasjon. Brukerobjektet ble ikke hentet p\u00E5 riktig m\u00E5te p\u00E5 grunn av en ACS-konfigurasjonsfeil. Det kan hende at brukeren ikke er registrert for ACS. Kontakt administratoren."},
    {"ADF-MF-16086", "Tjeneren kan ikke n\u00E5s. Kontroller at enheten er koblet til Internett."},
    {"ADF-MF-16087", "Ugyldig brukernavn/passord. Pr\u00F8v p\u00E5 nytt."},
    {"ADF-MF-16088", "Konfigurasjonsfeil. URL-adressen til tilgangskontrolltjenesten mangler. Kontakt administratoren."},
    {"ADF-MF-16089", "Du overskred det maksimale antallet p\u00E5loggingsfors\u00F8k som er tillatt. Du er l\u00E5st ute. Kontakt administratoren."},
    {"ADF-MF-16090", "Kan ikke utf\u00F8re kontrollen for konfigurasjonsendringer. Kontroller nettverkstilkoblingen, eller kontakt en administrator."},
    {"ADF-MF-16091", "Kan ikke oppdatere konfigurasjoner fra konfigurasjonstjenesten."},
    {"ADF-MF-16092", "Misformet melding"},
    {"ADF-MF-16093", "Tom foresp\u00F8rselsmelding er ikke tillatt."},
    {"ADF-MF-16094", "Melding som ikke st\u00F8ttes"},
    {"ADF-MF-16095", "Systemmeldinger st\u00F8ttes ikke p\u00E5 denne kanalen"},
    {"ADF-MF-16096", "Ugyldig systemforesp\u00F8rsel, %@"},
    {"ADF-MF-16097", "Applikasjonsmeldinger st\u00F8ttes ikke p\u00E5 denne kanalen"},
    {"ADF-MF-16098", "Ugyldig applikasjonsforesp\u00F8rsel, %@"},
    {"ADF-MF-16099", "Ubehandlet melding"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Type: %d Hoveddel: %@"},
    {"ADF-MF-16101", "Mottok en uanmodet svarmelding"},
    {"ADF-MF-16102", "Mottok en ukjent meldingstype"},
    {"ADF-MF-16103", "AdfChannel.handle - feil ved behandling av VMChannel-meldingen: %@ - FEIL: %@"},
    {"ADF-MF-16104", "%@ ikke angitt. Feil fjernet: %@"},
    {"ADF-MF-16105", "Enhetstilgang er deaktivert for funksjonen %@: url: %@, baseUrl: %@, msg: %@"},
    {"ADF-MF-16106", "URL-adressen har ikke enhetstilgang for funksjonen %@: url: %@, baseUrl: %@, msg: %@"},
    {"ADF-MF-16107", "FEIL under hvitelisting: %@"},
    {"ADF-MF-16108", "Kan ikke sende oppdatert bredde/h\u00F8yde til Java-side"},
    {"ADF-MF-16109", "Kan ikke registrere for endringshendelser for nettverksstatus. Nettverksstatusen vil v\u00E6re utilgjengelig"},
    {"ADF-MF-16110", "Standard p\u00E5loggingstilkobling, %@, er ikke definert."},
    {"ADF-MF-16111", "Skallet %@ mangler familie. Ignoreres."},
    {"ADF-MF-16112", "Den aktive skallfamilien, %@, returnerte ikke noe skall."},
    {"ADF-MF-16113", "Finner ikke vedlegget %@, eller det kan ikke leses"},
    {"ADF-MF-16114", "%@ st\u00F8tter ikke deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "%@ er ikke definert i Web-visningen. JavaScript-resultatkallet ble avbrutt."},
    {"ADF-MF-16116", "Det oppstod et problem ved kall til funksjonen %@: %@"},
    {"ADF-MF-16117", "FEIL: Det oppstod et unntak ved utf\u00F8relse av tilbakekallet for %d: %@"},
    {"ADF-MF-16118", "Feil ved applikasjonsautentisering. \u00C5rsak = %@"},
    {"ADF-MF-16119", "Feil ved funksjonsautentisering. Funksjonen er deaktivert. \u00C5rsak = %@"},
    {"ADF-MF-16120", "Autentiseringsfeil. Pr\u00F8v p\u00E5 nytt."},
    {"ADF-MF-16121", "ACS returnerte feil: %@"},
    {"ADF-MF-16122", "ACS er ikke konfigurert for tilkoblingen %@. Brukerobjekter er ikke registrert."},
    {"ADF-MF-16123", "P\u00E5logging p\u00E5 applikasjonsniv\u00E5 mislyktes p\u00E5 grunn av manglende autentiseringskontekst."},
    {"ADF-MF-16124", "Filen finnes i hurtigbufferbanen"},
    {"ADF-MF-16125", "Kan ikke opprette en katalog for hurtigbufferen p\u00E5 %@ fordi en fil allerede finnes"},
    {"ADF-MF-16126", "Kan ikke opprette hurtigbufferkatalog"},
    {"ADF-MF-16127", "Kan ikke opprette en katalog for hurtigbufferen p\u00E5 %@"},
    {"ADF-MF-16128", "Kan ikke bla gjennom hurtigbufferkatalog"},
    {"ADF-MF-16129", "Visning av hurtigbufferkatalog mislyktes i banen %@"},
    {"ADF-MF-16130", "Kan ikke fjerne hurtigbufferfil"},
    {"ADF-MF-16131", "Kan ikke fjerne mellomlagrede data i banen %@"},
    {"ADF-MF-16132", "Krasjer n\u00E5 fordi konfigurasjonen ikke kunne lastes ned."},
    {"ADF-MF-16133", "Visning av funksjon mislyktes"},
    {"ADF-MF-16134", "Kan ikke vise funksjonen. Fors\u00F8ket p\u00E5 \u00E5 vise funksjonen %@ mislyktes. FEIL: %@"},
    {"ADF-MF-16135", "Feil ved applikasjonskontroller"},
    {"ADF-MF-16136", "Applikasjonskontrollermappen %@ finnes ikke."},
    {"ADF-MF-16137", "Kan ikke laste egenskapsfil: %@ - FEIL: %@"},
    {"ADF-MF-16138", "Feil ved serialisering av retur: %@"},
    {"ADF-MF-16139", "FeatureId kan ikke fastsettes. Avbryter kall til Java-klasse."},
    {"ADF-MF-16140", "Verifisering av CVM-kanal mislyktes."},
    {"ADF-MF-16141", "CVM returnerte en uventet objekttype: %@"},
    {"ADF-MF-16142", "Kan ikke sende meldingen"},
    {"ADF-MF-16143", "Kan ikke sende meldinger fordi det ikke er noen tilgjengelig tekstmeldingsfunksjon p\u00E5 denne enheten."},
    {"ADF-MF-16144", "Kan ikke sende meldingen fordi tekstmeldingsforfatteren ikke kan hentes."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - klassenavnet ble ikke angitt"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - kallet morphClassName for\u00E5rsaket en FEIL: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - klassenavnet morphClassName mislyktes."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - metoden ble ikke angitt"},
    {"ADF-MF-16149", "Kan ikke opprette klassen %@"},
    {"ADF-MF-16150", "Opprettelse av en ny forekomst av et objekt mislyktes: %@"},
    {"ADF-MF-16151", "En forekomst av klassen %@ svarer ikke til velgeren %@."},
    {"ADF-MF-16152", "Start av %@ for\u00E5rsaket feilen %@"},
    {"ADF-MF-16153", "Serialisering av resultat fra %@ p\u00E5 typen %@ for\u00E5rsaket FEIL: %@"},
    {"ADF-MF-16154", "Serialisering av resultat fra %@ p\u00E5 typen %@ genererte null."},
    {"ADF-MF-16155", "credentialStoreKey for tilkoblingen %@ kan ikke v\u00E6re null"},
    {"ADF-MF-16156", "credentialStoreKey for tilkoblingen kan ikke v\u00E6re null"},
    {"ADF-MF-16157", "Det oppstod en generell p\u00E5loggingsfeil. Det kan hende at brukeren har angitt ugyldig p\u00E5loggingsinformasjon, eller at konfigurasjonen av p\u00E5loggingstilkoblingen inneholder feil. Eksempler: P\u00E5loggings-URL-adressen og/eller navnet p\u00E5 en informasjonskapsel mangler eller er feil."},
    {"ADF-MF-16158", "Tjeneren kan ikke n\u00E5s. Kontroller at du er koblet til Internett."},
    {"ADF-MF-16159", "Feil i threadShellInitializationComplete: %@"},
    {"ADF-MF-16160", "Feil i paintMirrorLoop: %@"},
    {"ADF-MF-16161", "ACS er ikke konfigurert for standardtilkobling, og begrensede funksjoner gj\u00F8res ikke tilgjengelige."},
    {"ADF-MF-16162", "Feil i brukernavn"},
    {"ADF-MF-16163", "Brukernavnet og/eller klientnavnet som brukes, er forskjellig fra det opprinnelige brukernavnet og/eller klientnavnet. Du m\u00E5 rette opp brukernavnet og/eller klientnavnet hvis du oppgav feil brukernavn og/eller klientnavn. Hvis du vil logge p\u00E5 som ny bruker, m\u00E5 du f\u00F8rst avslutte applikasjonen."},
    {"ADF-MF-16164", "Hodenavn for flere klienter mangler"},
    {"ADF-MF-16165", "Kan ikke autentisere ettersom det ikke er angitt nok opplysninger for autentisering i applikasjonen med st\u00F8tte for flere klienter. Konfigurasjonen mangler hodenavn for flere klienter. Kontakt administratoren."},
    {"ADF-MF-16166", "Klientnavn er ikke angitt"},
    {"ADF-MF-16167", "Kan ikke autentisere fordi klientnavn ikke er angitt. Pr\u00F8v p\u00E5 nytt."},
    {"ADF-MF-16168", "P\u00E5logging p\u00E5 applikasjonsniv\u00E5 fors\u00F8kes. Tjener = %@ for bruker = %@"},
    {"ADF-MF-16169", "P\u00E5logging p\u00E5 applikasjonsniv\u00E5 ble utf\u00F8rt."},
    {"ADF-MF-16170", "OMCredentialStore returnerte ikke egenskap for kSecAttrLabel."},
    {"ADF-MF-16171", "Applikasjonsbrukerobjekter hentes fra lageret for p\u00E5loggingsinformasjon: %@"},
    {"ADF-MF-16172", "Brukerautentiseringstest returnerer %@."},
    {"ADF-MF-16173", "P\u00E5logging p\u00E5 funksjonsniv\u00E5 mislyktes p\u00E5 grunn av en uventet tilstand."},
    {"ADF-MF-16174", "Fors\u00F8k p\u00E5 p\u00E5logging p\u00E5 funksjonsniv\u00E5 for bruker = %@."},
    {"ADF-MF-16175", "Fors\u00F8k p\u00E5 avlogging p\u00E5 funksjonsniv\u00E5."},
    {"ADF-MF-16176", "Brukerobjekter er i ferd med \u00E5 bli hentet ettersom p\u00E5loggingen er knyttet til en ekstern funksjon."},
    {"ADF-MF-16177", "Autentiseringen var vellykket."},
    {"ADF-MF-16178", "returnerte brukerobjektsvar = %@"},
    {"ADF-MF-16179", "returnerte brukerobjektprivilegier = %@ roller = %@"},
    {"ADF-MF-16180", "Starter ACS med nyttelast = %@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: authContext ble ikke hentet."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: pausedFeature ble ikke hentet."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: authContext ble ikke hentet."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: pausedFeature ble ikke hentet."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: authContext ble ikke hentet."},
    {"ADF-MF-16186", "Konfigurasjonsfeil"},
    {"ADF-MF-16187", "Applikasjonsp\u00E5loggingstilkoblingen er ikke definert. Denne applikasjonen kan ikke kj\u00F8res. Kontakt administratoren."},
    {"ADF-MF-16188", "Tilkobling for funksjonsp\u00E5logging er ikke definert. Ingen tilgang til denne funksjonen. Kontakt administratoren."},
    {"ADF-MF-16189", "Logg av"},
    {"ADF-MF-16190", "Avlogging ble startet. Applikasjonen avsluttes."},
    {"ADF-MF-16191", "Feil ved konfigurasjon av p\u00E5loggingstilkobling. {0} Kontakt administratoren."},
    {"ADF-MF-16192", "Lagringsn\u00F8kkel for p\u00E5loggingsinformasjon er ikke angitt."},
    {"ADF-MF-16193", "Ugyldig eller manglende brukernavn og/eller passord."},
    {"ADF-MF-16195", "Feil i sammensatt lagringsn\u00F8kkel for p\u00E5loggingsinformasjon"},
    {"ADF-MF-16196", "Ugyldig URL-adresse til tilgangskontrolltjeneste."},
    {"ADF-MF-16197", "Ugyldig avloggings-URL-adresse."},
    {"ADF-MF-16198", "Ugyldig p\u00E5loggings-URL-adresse."},
    {"ADF-MF-16199", "Informasjonskapsel er ikke angitt."},
    {"ADF-MF-16200", "Uvirksomt tidsavbrudd m\u00E5 v\u00E6re 10 eller st\u00F8rre, tidsavbrudd for \u00F8kt m\u00E5 v\u00E6re 30 eller st\u00F8rre og st\u00F8rre enn uvirksomt tidsavbrudd."},
    {"ADF-MF-16201", "Feil ved konfigurasjon av p\u00E5loggingstilkobling"},
    {"ADF-MF-16202", "URL-adressen for autentisering svarte med en ugyldig HTTP-svarkode. Den er ikke et sluttpunkt for grunnleggende autentisering. Kontakt administratoren."},
    {"ADF-MF-16203", "Finner ikke filen: %@"},
    {"ADF-MF-16204", "E-postmeldingen ble ikke lagret eller lagt i k\u00F8. Dette kan skyldes en feil."},
    {"ADF-MF-16205", "Det oppstod en feil ved fors\u00F8k p\u00E5 \u00E5 lagre e-postmeldingen i utkastmappen."},
    {"ADF-MF-16206", "Det oppstod en feil ved fors\u00F8k p\u00E5 \u00E5 legge e-postmeldingen i k\u00F8 eller sende den."},
    {"ADF-MF-16207", "Det oppstod en ukjent feil ved fors\u00F8k p\u00E5 \u00E5 skrive eller sende en e-post"},
    {"ADF-MF-16208", "Det oppstod en ukjent feil ved fors\u00F8k p\u00E5 \u00E5 skrive eller sende en tekstmelding"},
    {"ADF-MF-16209", "Finner ikke filen"},
    {"ADF-MF-16210", "Fant en ugyldig tilordning mellom prefiks og URI. Prefikset %@ er allerede tilordnet til URI-en %@, og ny tilordning av prefikset til URI-en %@ er ikke tillatt"},
    {"ADF-MF-16211", "Fant en ugyldig tilordning mellom prefiks og URI. URI-en %@ er allerede tilordnet til prefikset %@, og ny tilordning av URI-en til prefikset %@ er ikke tillatt"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
