// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_pt_BR extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "A classe %@ gerou um erro quando foi alocada e iniciada - Abortando a adi\u00E7\u00E3o do Listener do Ciclo de Vida da Aplica\u00E7\u00E3o ERRO: %@"},
    {"ADF-MF-16002", "Uso Inv\u00E1lido"},
    {"ADF-MF-16003", "Esta fun\u00E7\u00E3o deve ser chamada no thread principal."},
    {"ADF-MF-16004", "Esta fun\u00E7\u00E3o N\u00C3O deve ser chamada no thread principal."},
    {"ADF-MF-16005", "Arquivo de Configura\u00E7\u00E3o Inv\u00E1lido"},
    {"ADF-MF-16006", "Configura\u00E7\u00E3o Inv\u00E1lida"},
    {"ADF-MF-16007", "Implementador AdfmfContainerUtilities n\u00E3o configurado."},
    {"ADF-MF-16008", "Classe do implementador AdfmfContainerUtilities n\u00E3o encontrada."},
    {"ADF-MF-16009", "N\u00E3o foi poss\u00EDvel criar o implementador AdfmfContainerUtilities."},
    {"ADF-MF-16010", "Solicita\u00E7\u00E3o Inv\u00E1lida"},
    {"ADF-MF-16011", "N\u00E3o foi poss\u00EDvel fazer download do arquivo em decorr\u00EAncia de 400 - Solicita\u00E7\u00E3o Inv\u00E1lida."},
    {"ADF-MF-16012", "N\u00E3o Autorizado"},
    {"ADF-MF-16013", "N\u00E3o foi poss\u00EDvel fazer download do arquivo em decorr\u00EAncia de 401 - N\u00E3o Autorizado (senha ou nome do usu\u00E1rio inv\u00E1lido)."},
    {"ADF-MF-16014", "Proibido"},
    {"ADF-MF-16015", "N\u00E3o foi poss\u00EDvel fazer download do arquivo em decorr\u00EAncia de 403 - Proibido."},
    {"ADF-MF-16016", "N\u00E3o Encontrado"},
    {"ADF-MF-16017", "N\u00E3o foi poss\u00EDvel fazer download do arquivo em decorr\u00EAncia de 404 - N\u00E3o Encontrado."},
    {"ADF-MF-16018", "Gateway Incorreto"},
    {"ADF-MF-16019", "N\u00E3o foi poss\u00EDvel fazer download do arquivo em decorr\u00EAncia de 502 - Gateway Inv\u00E1lido."},
    {"ADF-MF-16020", "Servi\u00E7o Indispon\u00EDvel"},
    {"ADF-MF-16021", "N\u00E3o foi poss\u00EDvel fazer download do arquivo em decorr\u00EAncia de 503 - Servi\u00E7o Indispon\u00EDvel."},
    {"ADF-MF-16022", "Argumento Inv\u00E1lido"},
    {"ADF-MF-16023", "Um nome de pacote nulo foi informado para [oraADFLogger getLogger:]."},
    {"ADF-MF-16024", "O url do arquivo de erro n\u00E3o pode ser nulo"},
    {"ADF-MF-16025", "O nome da propriedade n\u00E3o pode ser nulo."},
    {"ADF-MF-16026", "Poucos argumentos."},
    {"ADF-MF-16027", "Classname n\u00E3o encontrado."},
    {"ADF-MF-16028", "M\u00E9todo n\u00E3o encontrado."},
    {"ADF-MF-16029", "Id do Recurso n\u00E3o encontrado."},
    {"ADF-MF-16030", "Tipo de Chamada N\u00E3o Reconhecido"},
    {"ADF-MF-16031", "FeatureContext n\u00E3o encontrado."},
    {"ADF-MF-16032", "Resposta Inesperada"},
    {"ADF-MF-16033", "A Resposta CVM retornou uma resposta nula. "},
    {"ADF-MF-16034", "A Resposta CVM retornou um FeatureContextAccessor nulo."},
    {"ADF-MF-16035", "A Resposta JS retornou uma resposta nula."},
    {"ADF-MF-16036", "N\u00E3o \u00E9 poss\u00EDvel enviar chamadas JavaScript para o _Control_Channel_."},
    {"ADF-MF-16037", "Erro de ES"},
    {"ADF-MF-16038", "Erro ao remover o arquivo."},
    {"ADF-MF-16039", "Erro ao copiar o arquivo."},
    {"ADF-MF-16040", "Arquivo inesperado n\u00E3o encontrado."},
    {"ADF-MF-16041", "Erro ao mover o arquivo."},
    {"ADF-MF-16042", "N\u00E3o foi poss\u00EDvel criar o diret\u00F3rio."},
    {"ADF-MF-16043", "Erro de Download"},
    {"ADF-MF-16044", "N\u00E3o foi poss\u00EDvel criar a conex\u00E3o"},
    {"ADF-MF-16045", "Houve um erro inesperado ao fazer download do arquivo."},
    {"ADF-MF-16046", "Falha na Autentica\u00E7\u00E3o"},
    {"ADF-MF-16047", "N\u00E3o temos nome do usu\u00E1rio ou senha."},
    {"ADF-MF-16048", "N\u00E3o foi poss\u00EDvel fazer download do arquivo em decorr\u00EAncia falha de autentica\u00E7\u00E3o."},
    {"ADF-MF-16049", "Documento de Container Inv\u00E1lido"},
    {"ADF-MF-16050", "O elemento \\'feature\\' foi encontrado quando um \\'feature\\' ativo estava sendo processado."},
    {"ADF-MF-16051", "O Id do Recurso \\'_Control_Channel_\\' est\u00E1 em conflito com um Nome do Identificador do Canal VM reservado"},
    {"ADF-MF-16052", "A classe \\'OracleAdfmfFeature\\' foi inicializada com um tipo de elemento incorreto."},
    {"ADF-MF-16053", "Estado Inv\u00E1lido"},
    {"ADF-MF-16054", "O url do arquivo n\u00E3o pode ser nulo"},
    {"ADF-MF-16055", "Tentativa de adicionar um objeto que n\u00E3o era uma ASIHTTPRequest para uma ASINetworkQueue"},
    {"ADF-MF-16056", "Erro na Cria\u00E7\u00E3o do Contato"},
    {"ADF-MF-16057", "Erro na Remo\u00E7\u00E3o do Contato"},
    {"ADF-MF-16058", "Erro de argumento Inv\u00E1lido"},
    {"ADF-MF-16059", "Erro de Timeout"},
    {"ADF-MF-16060", "Erro de opera\u00E7\u00E3o Pendente"},
    {"ADF-MF-16061", "Erro de E/S"},
    {"ADF-MF-16062", "Erro N\u00E3o Suportado"},
    {"ADF-MF-16063", "Erro de Permiss\u00E3o Negada"},
    {"ADF-MF-16064", "Erro Desconhecido"},
    {"ADF-MF-16066", "Classe Inv\u00E1lida"},
    {"ADF-MF-16067", "A classe n\u00E3o encontrou uma implementa\u00E7\u00E3o de uma fun\u00E7\u00E3o obrigat\u00F3ria. Ativar depura\u00E7\u00E3o para registrar informa\u00E7\u00F5es sobre a classe."},
    {"ADF-MF-16068", "Classe da view do recurso n\u00E3o encontrada."},
    {"ADF-MF-16069", "N\u00E3o foi poss\u00EDvel criar a classe da view do recurso."},
    {"ADF-MF-16070", "O controlador da view forneceu uma view nula para a view do recurso."},
    {"ADF-MF-16071", "A classe n\u00E3o \u00E9 um tipo de view v\u00E1lido. A subclasse suportada atualmente deve ser de: UIView ou UIViewController"},
    {"ADF-MF-16072", "Uma HttpURLConnection usada por um recurso n\u00E3o foi encontrada."},
    {"ADF-MF-16073", "Uma HttpURLConnection usada por um recurso tem um url nil."},
    {"ADF-MF-16074", "Mensagem inv\u00E1lida"},
    {"ADF-MF-16075", "Tipo de Mensagem Desconhecido especificado pela mensagem."},
    {"ADF-MF-16076", "Erro de Log-in"},
    {"ADF-MF-16077", "Erro de Configura\u00E7\u00E3o"},
    {"ADF-MF-16078", " Falha ao Carregar a UIWebView"},
    {"ADF-MF-16079", " Falha ao carregar o recurso '%@' URL: %@"},
    {"ADF-MF-16080", "Entre em contato com o administrador."},
    {"ADF-MF-16081", "O servidor de log-in n\u00E3o \u00E9 acess\u00EDvel."},
    {"ADF-MF-16082", "Nome de usu\u00E1rio/senha inv\u00E1lido. Se o problema continuar, entre em contato com o administrador do sistema."},
    {"ADF-MF-16083", "Erro de configura\u00E7\u00E3o. Entre em contato com o administrador. "},
    {"ADF-MF-16084", "Falha de ACS"},
    {"ADF-MF-16085", "Configura\u00E7\u00E3o inv\u00E1lida do ACS. O objeto do usu\u00E1rio n\u00E3o foi recuperado corretamente devido a um erro de configura\u00E7\u00E3o do ACS. Pode ser que o usu\u00E1rio n\u00E3o esteja registrado no ACS. Entre em contato com o administrador."},
    {"ADF-MF-16086", "O servidor n\u00E3o \u00E9 acess\u00EDvel. Certifique-se de que seu dispositivo est\u00E1 conectado \u00E0 Internet."},
    {"ADF-MF-16087", "Senha/nome do usu\u00E1rio inv\u00E1lido. Tente novamente."},
    {"ADF-MF-16088", "Erro de configura\u00E7\u00E3o. O URL do servi\u00E7o de controle de acesso n\u00E3o foi encontrado. Entre em contato com o administrador."},
    {"ADF-MF-16089", "Voc\u00EA excedeu o n\u00FAmero m\u00E1ximo de tentativas de log-in permitidas e foi bloqueado. Entre em contato com o administrador."},
    {"ADF-MF-16090", "N\u00E3o foi poss\u00EDvel executar a verifica\u00E7\u00E3o de altera\u00E7\u00F5es da configura\u00E7\u00E3o. Verifique a conex\u00E3o de rede ou entre em contato com um administrador."},
    {"ADF-MF-16091", "N\u00E3o foi poss\u00EDvel atualizar as configura\u00E7\u00F5es do servi\u00E7o de configura\u00E7\u00E3o."},
    {"ADF-MF-16092", "Mensagem Incorreta"},
    {"ADF-MF-16093", "Mensagem de solicita\u00E7\u00E3o vazia n\u00E3o permitida."},
    {"ADF-MF-16094", "Mensagem N\u00E3o Suportada"},
    {"ADF-MF-16095", "As mensagens do sistema n\u00E3o s\u00E3o suportadas neste canal"},
    {"ADF-MF-16096", "Solicita\u00E7\u00E3o %@ do sistema inv\u00E1lida"},
    {"ADF-MF-16097", "As mensagens da aplica\u00E7\u00E3o n\u00E3o s\u00E3o suportadas neste canal"},
    {"ADF-MF-16098", "Solicita\u00E7\u00E3o %@ da aplica\u00E7\u00E3o inv\u00E1lida"},
    {"ADF-MF-16099", "Mensagem N\u00E3o Tratada"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Tipo: %d Corpo: %@"},
    {"ADF-MF-16101", "Recebeu uma mensagem de resposta n\u00E3o solicitada"},
    {"ADF-MF-16102", "Recebeu um tipo de mensagem desconhecido"},
    {"ADF-MF-16103", "AdfChannel.handle - Erro ao tratar a mensagem VMChannel: %@ - ERRO: %@"},
    {"ADF-MF-16104", "Nenhum '%@' especificado. Erro eliminado: '%@'"},
    {"ADF-MF-16105", "Acesso ao dispositivo desativado para o recurso \\'%@\\': url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16106", "O URL n\u00E3o permitiu o acesso ao dispositivo ao recurso \\'%@\\': url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16107", "ERRO Durante Whitelist: %@"},
    {"ADF-MF-16108", "N\u00E3o \u00E9 poss\u00EDvel enviar a largura/peso atualizados para Java"},
    {"ADF-MF-16109", "N\u00E3o \u00E9 poss\u00EDvel registrar eventos de altera\u00E7\u00E3o de status da rede. O status da rede ficar\u00E1 indispon\u00EDvel"},
    {"ADF-MF-16110", "A conex\u00E3o de log-in default \\'%@\\' n\u00E3o foi definida."},
    {"ADF-MF-16111", "Skin \\'%@\\' n\u00E3o encontrado em uma fam\u00EDlia. Ignorado."},
    {"ADF-MF-16112", "Fam\u00EDlia skin \\'%@\\' ativa retornada sem skin."},
    {"ADF-MF-16113", "O anexo %@ n\u00E3o foi encontrado ou n\u00E3o p\u00F4de ser lido"},
    {"ADF-MF-16114", "%@ n\u00E3o suporta deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "%@ n\u00E3o definido na webview. Chamada resultante de JavaScript abortada."},
    {"ADF-MF-16116", "Houve um problema ao chamar a fun\u00E7\u00E3o '%@': %@"},
    {"ADF-MF-16117", "ERRO: foi encontrada uma exce\u00E7\u00E3o ao executar o callback %d: %@"},
    {"ADF-MF-16118", "Erro de Autentica\u00E7\u00E3o da Aplica\u00E7\u00E3o. Motivo = %@"},
    {"ADF-MF-16119", "Erro de Autentica\u00E7\u00E3o do Recurso. Recurso Desativado. Motivo = %@"},
    {"ADF-MF-16120", "Erro de Autentica\u00E7\u00E3o. Tente de novo."},
    {"ADF-MF-16121", "ACS retornou o erro: %@"},
    {"ADF-MF-16122", "ACS n\u00E3o configurado para a conex\u00E3o %@. Os objetos do usu\u00E1rio n\u00E3o foram registrados."},
    {"ADF-MF-16123", "Falha no log-in em n\u00EDvel de aplica\u00E7\u00E3o em decorr\u00EAncia de contexto de autentica\u00E7\u00E3o n\u00E3o encontrado."},
    {"ADF-MF-16124", "O Arquivo Existe no Caminho do Cache"},
    {"ADF-MF-16125", "N\u00E3o \u00E9 poss\u00EDvel criar um diret\u00F3rio para o cache em \\'%@\\' porque j\u00E1 existe um arquivo"},
    {"ADF-MF-16126", "Falha ao Criar o Diret\u00F3rio de Cache"},
    {"ADF-MF-16127", "Falha ao criar um diret\u00F3rio de cache em \\'%@\\'"},
    {"ADF-MF-16128", "Falha ao Atravessar o Diret\u00F3rio de Cache"},
    {"ADF-MF-16129", "Falha ao listar o diret\u00F3rio de cache no caminho '%@'"},
    {"ADF-MF-16130", "Falha ao Remover o Arquivo de Cache"},
    {"ADF-MF-16131", "Falha ao remover os dados armazenados em cache no caminho '%@'"},
    {"ADF-MF-16132", "Desativando Agora porque n\u00E3o foi poss\u00EDvel fazer download da configura\u00E7\u00E3o."},
    {"ADF-MF-16133", "Falha ao Mostrar o Recurso"},
    {"ADF-MF-16134", "N\u00E3o foi poss\u00EDvel mostrar o recurso. Falha na tentativa de mostrar o recurso '%@'. ERRO: %@"},
    {"ADF-MF-16135", "Erro do Controlador de Aplica\u00E7\u00F5es"},
    {"ADF-MF-16136", "A pasta do controlador de aplica\u00E7\u00F5es '%@' n\u00E3o existe."},
    {"ADF-MF-16137", "N\u00E3o foi poss\u00EDvel carregar o arquivo .properties: %@ - ERRO: %@"},
    {"ADF-MF-16138", "Erro ao serializar retorno: %@"},
    {"ADF-MF-16139", "N\u00E3o foi poss\u00EDvel determinar o FeatureId. Abortando a chamada para a Classe Java."},
    {"ADF-MF-16140", "Falha na verifica\u00E7\u00E3o do Canal CVM."},
    {"ADF-MF-16141", "O CVM retornou um tipo de objeto inesperado: %@"},
    {"ADF-MF-16142", "N\u00E3o \u00C9 Poss\u00EDvel Enviar a Mensagem"},
    {"ADF-MF-16143", "N\u00E3o \u00E9 poss\u00EDvel enviar mensagem porque mensagem de texto n\u00E3o est\u00E1 dispon\u00EDvel neste dispositivo."},
    {"ADF-MF-16144", "N\u00E3o \u00E9 poss\u00EDvel enviar uma mensagem nem obter o criador da mensagem de texto."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - O 'nome da classe' n\u00E3o foi especificado"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - A chamada morphClassName causou um ERRO: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Falha do 'nome da classe' morphClassName."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - O 'm\u00E9todo' n\u00E3o foi especificado"},
    {"ADF-MF-16149", "N\u00E3o foi poss\u00EDvel criar a classe: %@"},
    {"ADF-MF-16150", "Falha no novo no tipo de objeto: %@"},
    {"ADF-MF-16151", "Inst\u00E2ncia da classe %@ n\u00E3o responde ao seletor '%@'."},
    {"ADF-MF-16152", "Chamar '%@' causou um erro: %@"},
    {"ADF-MF-16153", "A serializa\u00E7\u00E3o do resultado de '%@' no tipo %@ causou um erro ERRO: %@"},
    {"ADF-MF-16154", "A serializa\u00E7\u00E3o do resultado de '%@' no tipo %@ gerou nulo."},
    {"ADF-MF-16155", "credentialStoreKey para a conex\u00E3o %@ n\u00E3o pode ser nulo"},
    {"ADF-MF-16156", "credentialStoreKey para a conex\u00E3o n\u00E3o pode ser nulo"},
    {"ADF-MF-16157", "Ocorreu um erro geral de log-in. Pode ser que o usu\u00E1rio tenha informado credenciais inv\u00E1lidas ou que a configura\u00E7\u00E3o de conex\u00E3o de log-in contenha um erro. Por exemplo, pode ser que o URL de log-in e/ou o nome do cookie esteja faltando ou seja incorreto."},
    {"ADF-MF-16158", "N\u00E3o \u00E9 poss\u00EDvel acessar o servidor. Certifique-se de que voc\u00EA esteja conectado \u00E0 internet."},
    {"ADF-MF-16159", "Erro em threadShellInitializationComplete: %@"},
    {"ADF-MF-16160", "Erro em paintMirrorLoop: %@"},
    {"ADF-MF-16161", "O ACS n\u00E3o est\u00E1 configurado para a conex\u00E3o default, e recursos limitados n\u00E3o ser\u00E3o disponibilizados."},
    {"ADF-MF-16162", "Erro no Nome do usu\u00E1rio"},
    {"ADF-MF-16163", "O nome de usu\u00E1rio e/ou o nome do tenant usado(s) \u00E9(s\u00E3o) diferente(s) do nome de usu\u00E1rio original e/ou do nome do tenant. Corrija o nome de usu\u00E1rio e/ou nome do tenant se tiver informado um nome incorreto. Para efetuar log-in como novo usu\u00E1rio, primeiro saia da aplica\u00E7\u00E3o."},
    {"ADF-MF-16164", "O nome do cabe\u00E7alho multitenant n\u00E3o foi encontrado"},
    {"ADF-MF-16165", "N\u00E3o autentica porque n\u00E3o foram fornecidas informa\u00E7\u00F5es suficientes para autentica\u00E7\u00E3o na aplica\u00E7\u00E3o multitenant. O nome do cabe\u00E7alho multitenant n\u00E3o foi encontrado na configura\u00E7\u00E3o. Entre em contato com o administrador."},
    {"ADF-MF-16166", "O nome do tenant n\u00E3o foi informado"},
    {"ADF-MF-16167", "N\u00E3o \u00E9 poss\u00EDvel fazer a autentica\u00E7\u00E3o porque o nome do tenant n\u00E3o foi fornecido. Tente novamente."},
    {"ADF-MF-16168", "O log-in no n\u00EDvel da aplica\u00E7\u00E3o ser\u00E1 tentando novamente. Server=%@ para user=%@"},
    {"ADF-MF-16169", "O log-in no n\u00EDvel da aplica\u00E7\u00E3o foi bem-sucedido."},
    {"ADF-MF-16170", "OMCredentialStore n\u00E3o retornou uma propriedade para kSecAttrLabel."},
    {"ADF-MF-16171", "Objetos de usu\u00E1rios da aplica\u00E7\u00E3o s\u00E3o extra\u00EDdos da \u00E1rea de armazenamento de credenciais: %@"},
    {"ADF-MF-16172", "O teste de autentica\u00E7\u00E3o do usu\u00E1rio retorna %@."},
    {"ADF-MF-16173", "Falha no log-in no n\u00EDvel do recurso devido a uma condi\u00E7\u00E3o inesperada."},
    {"ADF-MF-16174", "Tentativa de log-in no n\u00EDvel do recurso para user=%@."},
    {"ADF-MF-16175", "Tentativa de log-out no n\u00EDvel do recurso."},
    {"ADF-MF-16176", "Objetos de usu\u00E1rio est\u00E3o sendo removidos porque se trata de um log-in de recurso remoto."},
    {"ADF-MF-16177", "Autentica\u00E7\u00E3o bem-sucedida."},
    {"ADF-MF-16178", "retornou objetos de usu\u00E1rio com response=%@"},
    {"ADF-MF-16179", "retornou objetos de usu\u00E1rio com privileges=%@ roles=%@"},
    {"ADF-MF-16180", "Chamando ACS com payload=%@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: authContext n\u00E3o foi obtido."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: pausedFeature n\u00E3o foi obtido."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: authContext n\u00E3o foi obtido."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: pausedFeature n\u00E3o foi obtido."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: authContext n\u00E3o foi obtido."},
    {"ADF-MF-16186", "Erro de Configura\u00E7\u00E3o"},
    {"ADF-MF-16187", "A conex\u00E3o de log-in da aplica\u00E7\u00E3o n\u00E3o foi definida. Essa aplica\u00E7\u00E3o n\u00E3o pode ser executada. Entre em contato com o administrador."},
    {"ADF-MF-16188", "A conex\u00E3o de log-in do recurso n\u00E3o foi definida. Esse recurso n\u00E3o pode ser acessado. Entre em contato com o administrador."},
    {"ADF-MF-16189", "Efetuar Log-out"},
    {"ADF-MF-16190", "O log-out foi iniciado. A aplica\u00E7\u00E3o ser\u00E1 finalizada."},
    {"ADF-MF-16191", "Erro de configura\u00E7\u00E3o da conex\u00E3o de log-in: {0}. Entre em contato com o administrador."},
    {"ADF-MF-16192", "A Chave da \u00C1rea de Armazenamento de Credenciais n\u00E3o foi especificada."},
    {"ADF-MF-16193", "Nome de usu\u00E1rio e/ou senha inv\u00E1lido ou inexistente."},
    {"ADF-MF-16195", "Erro na chave da \u00E1rea de armazenamento de credenciais composta"},
    {"ADF-MF-16196", "URL do Servi\u00E7o de Controle de Acesso Inv\u00E1lido."},
    {"ADF-MF-16197", "URL de Log-out Inv\u00E1lido."},
    {"ADF-MF-16198", "URL de Log-in Inv\u00E1lido."},
    {"ADF-MF-16199", "Cookie n\u00E3o especificado."},
    {"ADF-MF-16200", "O time-out de inatividade deve ser 10 ou mais. O time-out de sess\u00E3o de deve ser 30 ou mais e maior que o time-out de inatividade."},
    {"ADF-MF-16201", "Erro de Configura\u00E7\u00E3o de Conex\u00E3o de Log-in"},
    {"ADF-MF-16202", "O URL de autentica\u00E7\u00E3o respondeu com um c\u00F3digo de resposta HTTP inv\u00E1lido. Ele n\u00E3o \u00E9 um ponto final de autentica\u00E7\u00E3o b\u00E1sica. Entre em contato com o administrador."},
    {"ADF-MF-16203", "Arquivo n\u00E3o encontrado: %@"},
    {"ADF-MF-16204", "A mensagem de e-mail n\u00E3o foi salva nem colocada na fila, provavelmente devido a um erro."},
    {"ADF-MF-16205", "Ocorreu um erro ao tentar salvar a mensagem de email na pasta Rascunhos."},
    {"ADF-MF-16206", "Ocorreu um erro ao tentar enviar ou colocar a mensagem de e-mail na fila."},
    {"ADF-MF-16207", "Ocorreu um erro desconhecido ao tentar compor ou enviar um e-mail"},
    {"ADF-MF-16208", "Ocorreu um erro desconhecido ao tentar compor ou enviar uma mensagem de texto"},
    {"ADF-MF-16209", "Arquivo n\u00E3o encontrado"},
    {"ADF-MF-16210", "Foi encontrado um prefixo inv\u00E1lido para o mapeamento URI. O prefixo %@ j\u00E1 est\u00E1 mapeado para o URI %@. O remapeamento do prefixo para o URI %@ n\u00E3o \u00E9 permitido"},
    {"ADF-MF-16211", "Foi encontrado um prefixo inv\u00E1lido para o mapeamento URI. O URI %@ j\u00E1 est\u00E1 mapeado para o prefixo %@. O remapeamento do URI para o prefixo %@ n\u00E3o \u00E9 permitido"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
