// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_sv extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "Klassen %@ genererade ett fel n\u00E4r den tilldelades och initierades - Avbryter till\u00E4ggningen av applikationslivscykelavlyssnare FEL: %@"},
    {"ADF-MF-16002", "Ogiltig anv\u00E4ndning"},
    {"ADF-MF-16003", "Den h\u00E4r funktionen m\u00E5ste anropas i huvudtr\u00E5den."},
    {"ADF-MF-16004", "Den h\u00E4r funktionen f\u00E5r INTE anropas i huvudtr\u00E5den."},
    {"ADF-MF-16005", "Felaktig konfigurationsfil"},
    {"ADF-MF-16006", "Ogiltig konfiguration"},
    {"ADF-MF-16007", "Implementeraren f\u00F6r AdfmfContainerUtilities \u00E4r inte konfigurerad."},
    {"ADF-MF-16008", "Implementerarklassen f\u00F6r AdfmfContainerUtilities kan inte hittas."},
    {"ADF-MF-16009", "Implementeraren f\u00F6r AdfmfContainerUtilities kan inte skapas."},
    {"ADF-MF-16010", "Felaktig beg\u00E4ran"},
    {"ADF-MF-16011", "Kunde inte h\u00E4mta filen pga. 400 Felaktig beg\u00E4ran."},
    {"ADF-MF-16012", "Obeh\u00F6rig"},
    {"ADF-MF-16013", "Kunde inte h\u00E4mta filen pga. 401 Obeh\u00F6rig (felaktigt anv\u00E4ndarnamn eller l\u00F6senord)."},
    {"ADF-MF-16014", "F\u00F6rbjuden"},
    {"ADF-MF-16015", "Kunde inte h\u00E4mta filen pga. 403 F\u00F6rbjuden"},
    {"ADF-MF-16016", "Hittades inte"},
    {"ADF-MF-16017", "Kunde inte h\u00E4mta filen pga. 404 Hittades inte."},
    {"ADF-MF-16018", "Felaktig gateway"},
    {"ADF-MF-16019", "Kunde inte h\u00E4mta filen pga. 502 Felaktig n\u00E4tsluss."},
    {"ADF-MF-16020", "Tj\u00E4nsten \u00E4r inte tillg\u00E4nglig"},
    {"ADF-MF-16021", "Kunde inte h\u00E4mta filen pga. 503 Tj\u00E4nst otillg\u00E4nglig."},
    {"ADF-MF-16022", "Ogiltigt argument"},
    {"ADF-MF-16023", "Ett noll-paketnamn skickades till [oraADFLogger getLogger:]."},
    {"ADF-MF-16024", "Felfilens url f\u00E5r inte vara noll"},
    {"ADF-MF-16025", "Egenskapsnamnet f\u00E5r inte vara noll"},
    {"ADF-MF-16026", "F\u00F6r f\u00E5 argument."},
    {"ADF-MF-16027", "Klassnamn saknas."},
    {"ADF-MF-16028", "Metod saknas."},
    {"ADF-MF-16029", "Egenskaps-id saknas."},
    {"ADF-MF-16030", "Ok\u00E4nd anropstyp"},
    {"ADF-MF-16031", "FeatureContext hittades inte."},
    {"ADF-MF-16032", "Ov\u00E4ntat svar"},
    {"ADF-MF-16033", "CVM-svar returnerade ett noll-svar. "},
    {"ADF-MF-16034", "CVM-svar returnerade en noll-FeatureContextAccessor."},
    {"ADF-MF-16035", "JS-svar returnerade ett noll-svar."},
    {"ADF-MF-16036", "Kan inte skicka JavaScript-anrop till _Control_Channel_."},
    {"ADF-MF-16037", "IO-fel"},
    {"ADF-MF-16038", "Fel vid borttagning av fil."},
    {"ADF-MF-16039", "Fel vid kopiering av fil."},
    {"ADF-MF-16040", "Den f\u00F6rv\u00E4ntade filen saknas."},
    {"ADF-MF-16041", "Fel vid flytt av fil."},
    {"ADF-MF-16042", "Kunde inte skapa katalog."},
    {"ADF-MF-16043", "Nedladdningsfel"},
    {"ADF-MF-16044", "Kunde inte skapa anslutning"},
    {"ADF-MF-16045", "Ett ov\u00E4ntat fel intr\u00E4ffande vid h\u00E4mtning av filen."},
    {"ADF-MF-16046", "Autentiseringsfel"},
    {"ADF-MF-16047", "Vi har inget anv\u00E4ndarnamn eller l\u00F6senord."},
    {"ADF-MF-16048", "Kunde inte h\u00E4mta filen pga. ett autentiseringsfel."},
    {"ADF-MF-16049", "Ogiltigt containerdokument"},
    {"ADF-MF-16050", "Elementet 'feature' p\u00E5tr\u00E4ffades medan en aktiv 'feature' bearbetades."},
    {"ADF-MF-16051", "Funktions-id '_Control_Channel_' st\u00E5r i konflikt med ett reserverat namn f\u00F6r VM-kanalsidentifierare."},
    {"ADF-MF-16052", "Klassen 'OracleAdfmfFeature' initierades med fel elementtyp."},
    {"ADF-MF-16053", "Felaktigt l\u00E4ge"},
    {"ADF-MF-16054", "Filens url f\u00E5r inte vara noll"},
    {"ADF-MF-16055", "F\u00F6rs\u00F6kte l\u00E4gga till ett objekt som inte var en ASIHTTPRequest till en ASINetworkQueue"},
    {"ADF-MF-16056", "Fel: skapa kontakt"},
    {"ADF-MF-16057", "Fel: ta bort kontakt"},
    {"ADF-MF-16058", "Fel: ogiltigt argument"},
    {"ADF-MF-16059", "Fel: timeout"},
    {"ADF-MF-16060", "Fel: v\u00E4ntande \u00E5tg\u00E4rd"},
    {"ADF-MF-16061", "I/O-fel"},
    {"ADF-MF-16062", "Fel: st\u00F6ds inte"},
    {"ADF-MF-16063", "Fel: \u00E5tkomst nekad"},
    {"ADF-MF-16064", "Ok\u00E4nt fel"},
    {"ADF-MF-16066", "Ogiltig klass"},
    {"ADF-MF-16067", "Klassen saknar en implementering av en obligatorisk funktion. Aktivera fels\u00F6kning f\u00F6r att logga information om klassen."},
    {"ADF-MF-16068", "Funktionsvyklassen hittades inte."},
    {"ADF-MF-16069", "Funktionsvyklassen kunde inte skapas."},
    {"ADF-MF-16070", "Vykontrollanten tillhandah\u00F6ll en noll-vy f\u00F6r funktionsvyn."},
    {"ADF-MF-16071", "Klassen \u00E4r inte en giltig vytyp. Aktuell giltig underklass m\u00E5ste vara fr\u00E5n: UIView eller UIViewController"},
    {"ADF-MF-16072", "En HttpURLConnection anv\u00E4nd av en funktion hittades inte."},
    {"ADF-MF-16073", "En HttpURLConnection anv\u00E4nd av en funktion har en noll-url."},
    {"ADF-MF-16074", "Ogiltigt meddelande"},
    {"ADF-MF-16075", "Ok\u00E4nd meddelandetyp angavs av meddelande"},
    {"ADF-MF-16076", "Ett fel intr\u00E4ffade vid inloggning"},
    {"ADF-MF-16077", "Konfigurationsfel"},
    {"ADF-MF-16078", " Fel vid laddning av UIWebView"},
    {"ADF-MF-16079", " Kunde inte ladda funktionen '%@' URL: %@"},
    {"ADF-MF-16080", "Kontakta administrat\u00F6ren."},
    {"ADF-MF-16081", "Inloggningsservern kan inte n\u00E5s."},
    {"ADF-MF-16082", "Ogiltigt anv\u00E4ndarnamn/l\u00F6senord. Kontakta systemadministrat\u00F6ren om problemet kvarst\u00E5r."},
    {"ADF-MF-16083", "Konfigurationsfel. Kontakta administrat\u00F6ren. "},
    {"ADF-MF-16084", "ACS utf\u00F6rdes inte"},
    {"ADF-MF-16085", "Ogiltig ACS-konfiguration. Anv\u00E4ndarobjekt h\u00E4mtades inte p\u00E5 r\u00E4tt s\u00E4tt pga. ACS-konfigurationsfel. Anv\u00E4ndaren kanske inte \u00E4r registrerad p\u00E5 ACS. Kontakta administrat\u00F6ren."},
    {"ADF-MF-16086", "Servern kan inte n\u00E5s. Kontrollera att enheten \u00E4r ansluten till Internet."},
    {"ADF-MF-16087", "Ogiltigt anv\u00E4ndarnamn/l\u00F6senord. F\u00F6rs\u00F6k igen."},
    {"ADF-MF-16088", "Konfigurationsfel. \u00C5tkomstkontrolltj\u00E4nstens URL saknas. Kontakta administrat\u00F6ren."},
    {"ADF-MF-16089", "Du har \u00F6verskridit h\u00F6gsta antal till\u00E5tna inloggningsf\u00F6rs\u00F6k. Du \u00E4r utel\u00E5st. Kontakta administrat\u00F6ren."},
    {"ADF-MF-16090", "Kontrollen f\u00F6r konfigurations\u00E4ndringar kunde inte utf\u00F6ras. Kontrollera n\u00E4tverksanslutningen eller kontakta en administrat\u00F6r."},
    {"ADF-MF-16091", "Kunde inte uppdatera konfigurationer fr\u00E5n konfigurationstj\u00E4nsten."},
    {"ADF-MF-16092", "Felaktigt utformat meddelande"},
    {"ADF-MF-16093", "Tomt meddelande om beg\u00E4ran \u00E4r inte till\u00E5tet."},
    {"ADF-MF-16094", "Meddelandet st\u00F6ds inte"},
    {"ADF-MF-16095", "Systemmeddelanden st\u00F6ds inte i den h\u00E4r kanalen"},
    {"ADF-MF-16096", "Ogiltig systembeg\u00E4ran %@"},
    {"ADF-MF-16097", "Applikationsmeddelanden st\u00F6ds inte i den h\u00E4r kanalen"},
    {"ADF-MF-16098", "Ogiltig applikationsbeg\u00E4ran %@"},
    {"ADF-MF-16099", "Meddelandet hanteras inte"},
    {"ADF-MF-16100", "Adf-meddelandet hanteras inte - Referens-id: %d Typ: %d Text: %@"},
    {"ADF-MF-16101", "Tog emot ett o\u00F6nskat svarsmeddelande"},
    {"ADF-MF-16102", "Tog emot en ok\u00E4nd meddelandetyp"},
    {"ADF-MF-16103", "AdfChannel.handle - Felhantering av VMChannel.meddelandet: %@ - FEL: %@"},
    {"ADF-MF-16104", "Ingen '%@' angivet. Felet sl\u00E4pps: '%@'"},
    {"ADF-MF-16105", "Enhets\u00E5tkomst avaktiverad f\u00F6r funktion '%@': url:%@, bas-Url:%@, medd:%@"},
    {"ADF-MF-16106", "URL till\u00E5ter inte enhets\u00E5tkomst avaktiverad f\u00F6r funktion '%@': url:%@, bas-Url:%@, medd:%@"},
    {"ADF-MF-16107", "FEL under vitlista: %@"},
    {"ADF-MF-16108", "Kan inte skicka uppdaterad bredd/h\u00F6jd till Java-sidan"},
    {"ADF-MF-16109", "Kan inte registrera f\u00F6r \u00E4ndringsh\u00E4ndelser f\u00F6r n\u00E4tverksstatus. N\u00E4tverksstatusen \u00E4r inte tillg\u00E4nglig"},
    {"ADF-MF-16110", "Standardinloggningsanslutningen, '%@', \u00E4r inte definierad."},
    {"ADF-MF-16111", "Skalet '%@' saknar en familj. Ignoreras."},
    {"ADF-MF-16112", "Aktiv skalfamilj '%@' returnerade inget skal."},
    {"ADF-MF-16113", "Bilaga %@ hittades inte eller kunde inte l\u00E4sas"},
    {"ADF-MF-16114", "%@ st\u00F6der inte deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "%@ \u00E4r inte definierat i webbvyn. Anropet f\u00F6r JavaScript-resultat avbr\u00F6ts."},
    {"ADF-MF-16116", "Kunde inte anropa funktionen '%@': %@"},
    {"ADF-MF-16117", "FEL: p\u00E5tr\u00E4ffade ett undantag vid k\u00F6rning av %d \u00E5teranrop: %@"},
    {"ADF-MF-16118", "Applikationsautentiseringsfel. Orsak = %@"},
    {"ADF-MF-16119", "Funktionsautentiseringsfel. Funktionen avaktiverad. Orsak = %@"},
    {"ADF-MF-16120", "Autentiseringsfel. F\u00F6rs\u00F6k igen."},
    {"ADF-MF-16121", "ACS returnerade fel: %@"},
    {"ADF-MF-16122", "ACS har inte konfigurerats f\u00F6r anslutning %@. Anv\u00E4ndarobjekt har inte registrerats."},
    {"ADF-MF-16123", "Applikationsniv\u00E5inloggning utf\u00F6rdes inte p\u00E5 grund av saknad autentiseringskontext."},
    {"ADF-MF-16124", "Filen finns i caches\u00F6kv\u00E4gen"},
    {"ADF-MF-16125", "Kan inte skapa en katalog f\u00F6r cachen p\u00E5 '%@', efter det redan finns en fil"},
    {"ADF-MF-16126", "Kunde inte skapa cachekatalogen"},
    {"ADF-MF-16127", "Kunde inte traversera en katalog f\u00F6r cachen p\u00E5 '%@'"},
    {"ADF-MF-16128", "Kunde inte traversera cachekatalogen"},
    {"ADF-MF-16129", "Kunde inte visa inneh\u00E5llet i cachekatalogen i s\u00F6kv\u00E4g '%@'"},
    {"ADF-MF-16130", "Kunde inte ta bort cachefilen"},
    {"ADF-MF-16131", "Kunde inte ta bort cachade data i s\u00F6kv\u00E4g '%@'"},
    {"ADF-MF-16132", "Kraschar nu eftersom konfigurationen inte kunde h\u00E4mtas."},
    {"ADF-MF-16133", "Kunde inte visa funktionen"},
    {"ADF-MF-16134", "Kunde inte visa funktionen. F\u00F6rs\u00F6k att visa funktionen '%@' utf\u00F6rdes inte. FEL: %@"},
    {"ADF-MF-16135", "Fel i applikationskontroll"},
    {"ADF-MF-16136", "Applikationskontrollmappen '%@' finns inte."},
    {"ADF-MF-16137", "Kunde inte ladda .properties-filen: %@ - FEL: %@"},
    {"ADF-MF-16138", "Fel vid serialisering av returnering: %@"},
    {"ADF-MF-16139", "FeatureId kunde inte fastst\u00E4llas. Avbryter anrop till Javaklass."},
    {"ADF-MF-16140", "Verifiering av CVM-kanal utf\u00F6rdes inte."},
    {"ADF-MF-16141", "CVM returnerade en ov\u00E4ntad objektstyp: %@"},
    {"ADF-MF-16142", "Kan inte skicka meddelande"},
    {"ADF-MF-16143", "Det g\u00E5r inte att skicka meddelanden eftersom det inte finns n\u00E5gon sms-tj\u00E4nst p\u00E5 den h\u00E4r enheten."},
    {"ADF-MF-16144", "Kan inte skicka meddelandet eftersom sammanst\u00E4llningen f\u00F6r textmeddelanden inte g\u00E5r att h\u00E4mta."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - 'klassnamnet' angavs inte"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - morphClassName-anropet orsakade ett FEL: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - 'klassnamnet' morphClassName underk\u00E4ndes,"},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - 'metoden' angavs inte"},
    {"ADF-MF-16149", "Kunde inte skapa klassen: %@"},
    {"ADF-MF-16150", "Ny objekttyp underk\u00E4ndes: %@"},
    {"ADF-MF-16151", "Instansen i klassen %@ svarar inte p\u00E5 v\u00E4ljaren '%@'."},
    {"ADF-MF-16152", "Anrop av '%@' orsakade felet: %@"},
    {"ADF-MF-16153", "Serialisering av resultat fr\u00E5n '%@' f\u00F6r typen %@ orsakade FELET: %@"},
    {"ADF-MF-16154", "Serialisering av resultat fr\u00E5n '%@' f\u00F6r typen %@ genererade noll."},
    {"ADF-MF-16155", "credentialStoreKey f\u00F6r anslutningen %@ f\u00E5r inte vara noll"},
    {"ADF-MF-16156", "credentialStoreKey f\u00F6r anslutningen f\u00E5r inte vara noll"},
    {"ADF-MF-16157", "Allm\u00E4nt inloggningsfel intr\u00E4ffade. Anv\u00E4ndaren kan ha angett ogiltiga inloggningsuppgifter eller konfigurationen f\u00F6r inloggningsanslutningen kan inneh\u00E5lla fel. Exempelvis kan inloggnings-URL:en och/eller cookienamnet saknas eller vara fel."},
    {"ADF-MF-16158", "Servern kan inte n\u00E5s. Kontrollera att du \u00E4r ansluten till internet."},
    {"ADF-MF-16159", "Fel i threadShellInitializationComplete: %@"},
    {"ADF-MF-16160", "Fel i paintMirrorLoop: %@"},
    {"ADF-MF-16161", "ACS \u00E4r inte konfigurerat f\u00F6r standardanslutning och begr\u00E4nsade funktioner har inte gjorts tillg\u00E4ngliga."},
    {"ADF-MF-16162", "Fel i anv\u00E4ndarnamn"},
    {"ADF-MF-16163", "Anv\u00E4ndarnamnet och/eller objektnamnet som anv\u00E4nds skiljer sig fr\u00E5n det ursprungliga anv\u00E4ndarnamnet och/eller objektnamnet. Du m\u00E5ste ange r\u00E4tt anv\u00E4ndarnamn och/eller objektnamn om du har angett fel anv\u00E4ndarnamn och/eller objektnamn. Om du vill logga in som en ny anv\u00E4ndare m\u00E5ste du f\u00F6rst avsluta applikationen."},
    {"ADF-MF-16164", "Namn p\u00E5 flerobjektshuvud saknas"},
    {"ADF-MF-16165", "Det g\u00E5r inte att utf\u00F6ra en autentisering eftersom det inte har angetts tillr\u00E4ckligt med information i flerobjektsapplikationen. Konfigurationen saknar namnet p\u00E5 flerobjektshuvudet. Kontakta administrat\u00F6ren."},
    {"ADF-MF-16166", "Objektnamn angavs inte"},
    {"ADF-MF-16167", "Kan inte autentisera eftersom inget objektnamn angavs. F\u00F6rs\u00F6k igen."},
    {"ADF-MF-16168", "F\u00F6rs\u00F6k kommer att g\u00F6ras till inloggning p\u00E5 applikationsniv\u00E5. Server=%@ f\u00F6r anv\u00E4ndare=%@"},
    {"ADF-MF-16169", "Inloggning p\u00E5 applikationsniv\u00E5 utf\u00F6rdes."},
    {"ADF-MF-16170", "OMCredentialStore returnerade inte egenskap f\u00F6r kSecAttrLabel."},
    {"ADF-MF-16171", "Applikationsanv\u00E4ndarobjekt h\u00E4mtas fr\u00E5n lagret f\u00F6r inloggningsuppgifter: %@"},
    {"ADF-MF-16172", "Anv\u00E4ndarautentiseringstest returnerar %@."},
    {"ADF-MF-16173", "Inloggning p\u00E5 funktionsniv\u00E5 utf\u00F6rdes inte pga. ov\u00E4ntat villkor."},
    {"ADF-MF-16174", "F\u00F6rs\u00F6k till inloggning p\u00E5 funktionsniv\u00E5 f\u00F6r anv\u00E4ndare=%@."},
    {"ADF-MF-16175", "F\u00F6rs\u00F6k till utloggning p\u00E5 funktionsniv\u00E5."},
    {"ADF-MF-16176", "Anv\u00E4ndarobjekt h\u00E4mtas eftersom det \u00E4r en fj\u00E4rrinloggning p\u00E5 funktionsniv\u00E5."},
    {"ADF-MF-16177", "Autentiseringen utf\u00F6rdes."},
    {"ADF-MF-16178", "svar f\u00F6r returnerade anv\u00E4ndarobjekt=%@"},
    {"ADF-MF-16179", "beh\u00F6righet f\u00F6r returnerade anv\u00E4ndarobjekt=%@ roller=%@"},
    {"ADF-MF-16180", "Anropar ACS med nyttolast=%@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: authContext h\u00E4mtades inte."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: pausedFeature h\u00E4mtades inte."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: authContext h\u00E4mtades inte."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: pausedFeature h\u00E4mtades inte."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: authContext h\u00E4mtades inte."},
    {"ADF-MF-16186", "Konfigurationsfel"},
    {"ADF-MF-16187", "Applikationens inloggningsanslutning \u00E4r odefinierad. Det g\u00E5r inte att k\u00F6ra applikationen. Kontakta administrat\u00F6ren."},
    {"ADF-MF-16188", "Inloggningsanslutningen p\u00E5 funktionsniv\u00E5 har inte definierats. Det g\u00E5r inte att komma \u00E5t den h\u00E4r funktionen. Kontakta administrat\u00F6ren."},
    {"ADF-MF-16189", "Utloggning"},
    {"ADF-MF-16190", "Utloggning initierades. Applikationen avslutas."},
    {"ADF-MF-16191", "Konfigurationsfel i inloggningsanslutningen. {0} Kontakta administrat\u00F6ren."},
    {"ADF-MF-16192", "Nyckeln till lagret f\u00F6r inloggningsuppgifter har inte angetts."},
    {"ADF-MF-16193", "Ogiltigt eller saknat anv\u00E4ndarnamn och/eller l\u00F6senord."},
    {"ADF-MF-16195", "Fel i den sammansatta nyckeln till lagret f\u00F6r inloggningsuppgifter."},
    {"ADF-MF-16196", "Ogiltig URL till tj\u00E4nsten f\u00F6r \u00E5tkomstkontroll."},
    {"ADF-MF-16197", "Ogiltig utloggnings-URL."},
    {"ADF-MF-16198", "Ogiltig inloggnings-URL."},
    {"ADF-MF-16199", "Ingen cookie har angetts."},
    {"ADF-MF-16200", "Tidsgr\u00E4nsen f\u00F6r inaktivitet m\u00E5ste vara 10 eller h\u00F6gre, tidsgr\u00E4nsen f\u00F6r sessionen m\u00E5ste vara 30 eller h\u00F6gre och h\u00F6gre \u00E4n tidsgr\u00E4nsen f\u00F6r inaktivitet."},
    {"ADF-MF-16201", "Fel i inloggningsanslutningens konfiguration"},
    {"ADF-MF-16202", "Autentiserings-URL:en svarade med otill\u00E5ten HTTP-svarskod. Den \u00E4r inte en grundl\u00E4ggande autentiseringsslutpunkt. Kontakta administrat\u00F6ren."},
    {"ADF-MF-16203", "Filen hittades inte: %@"},
    {"ADF-MF-16204", "E-postmeddelandet sparades eller k\u00F6ades inte, troligen p\u00E5 grund av ett fel."},
    {"ADF-MF-16205", "Ett fel intr\u00E4ffade vid f\u00F6rs\u00F6k att spara e-postmeddelandet i mappen Utkast."},
    {"ADF-MF-16206", "Ett fel intr\u00E4ffade vid f\u00F6rs\u00F6k att k\u00F6a eller skicka e-postmeddelandet."},
    {"ADF-MF-16207", "Ett ok\u00E4nt fel intr\u00E4ffade vid f\u00F6rs\u00F6k att skapa eller skicka ett e-postmeddelande"},
    {"ADF-MF-16208", "Ett ok\u00E4nt fel intr\u00E4ffade vid f\u00F6rs\u00F6k att skapa eller skicka ett textmeddelande"},
    {"ADF-MF-16209", "Filen hittades inte"},
    {"ADF-MF-16210", "P\u00E5tr\u00E4ffade ett ogiltigt prefix till URI-mappning. Prefixet: %@ har redan mappats till URI: %@, ommappning av prefixet till URI: %@ \u00E4r inte till\u00E5tet"},
    {"ADF-MF-16211", "P\u00E5tr\u00E4ffade ett ogiltigt prefix till URI-mappning. URI: %@ har redan mappats till prefixet: %@, ommappning av URI till prefixet: %@ \u00E4r inte till\u00E5tet"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
