// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_ro extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "Clasa %@ a generat o eroare la opera\u0163iile alloc \u015Fi init - Se abandoneaz\u0103 ad\u0103ugarea Application Lifecycle Listener, EROARE: %@"},
    {"ADF-MF-16002", "Utilizare nevalid\u0103"},
    {"ADF-MF-16003", "Aceast\u0103 func\u0163ie trebuie apelat\u0103 \u00EEn firul principal."},
    {"ADF-MF-16004", "Aceast\u0103 func\u0163ie NU trebuie apelat\u0103 \u00EEn firul principal."},
    {"ADF-MF-16005", "Fi\u015Fier de configura\u0163ie nevalid"},
    {"ADF-MF-16006", "Configura\u0163ie nevalid\u0103"},
    {"ADF-MF-16007", "Implementatorul AdfmfContainerUtilities nu este configurat."},
    {"ADF-MF-16008", "Clasa implementatorului AdfmfContainerUtilities nu a fost g\u0103sit\u0103."},
    {"ADF-MF-16009", "Implementatorul AdfmfContainerUtilities nu a putut fi creat."},
    {"ADF-MF-16010", "Cerere formatat\u0103 gre\u015Fit"},
    {"ADF-MF-16011", "Fi\u015Fierul nu a putut fi desc\u0103rcat, eroarea returnat\u0103 fiind: 400 - Cerere formatat\u0103 gre\u015Fit."},
    {"ADF-MF-16012", "Neautorizat"},
    {"ADF-MF-16013", "Fi\u015Fierul nu a putut fi desc\u0103rcat, eroarea returnat\u0103 fiind: 401 - Neautorizat (nume de utilizator sau parol\u0103 gre\u015Fit\u0103)."},
    {"ADF-MF-16014", "Acces interzis"},
    {"ADF-MF-16015", "Fi\u015Fierul nu a putut fi desc\u0103rcat, eroarea returnat\u0103 fiind: 403 - Acces interzis."},
    {"ADF-MF-16016", "Nu a fost g\u0103sit"},
    {"ADF-MF-16017", "Fi\u015Fierul nu a putut fi desc\u0103rcat, eroarea returnat\u0103 fiind: 404 - Nu a fost g\u0103sit"},
    {"ADF-MF-16018", "Gateway eronat"},
    {"ADF-MF-16019", "Fi\u015Fierul nu a putut fi desc\u0103rcat, eroarea returnat\u0103 fiind: 502 - Gateway eronat."},
    {"ADF-MF-16020", "Serviciu indisponibil"},
    {"ADF-MF-16021", "Fi\u015Fierul nu a putut fi desc\u0103rcat, eroarea returnat\u0103 fiind: 503 - Serviciu indisponibil."},
    {"ADF-MF-16022", "Argument nevalid"},
    {"ADF-MF-16023", "A fost transmis un pachet cu un nume nul c\u0103tre [oraADFLogger getLogger:]."},
    {"ADF-MF-16024", "URL-ul fi\u015Fierului de eroare nu poate fi nul"},
    {"ADF-MF-16025", "Numele propriet\u0103\u0163ii nu poate fi nul."},
    {"ADF-MF-16026", "Prea pu\u0163ine argumente."},
    {"ADF-MF-16027", "Lipse\u015Fte numele clasei."},
    {"ADF-MF-16028", "Lipse\u015Fte metoda."},
    {"ADF-MF-16029", "Lipse\u015Fte ID-ul caracteristicii."},
    {"ADF-MF-16030", "Tip de apelare nerecunoscut"},
    {"ADF-MF-16031", "FeatureContext nu a fost g\u0103sit."},
    {"ADF-MF-16032", "R\u0103spuns nea\u015Fteptat"},
    {"ADF-MF-16033", "R\u0103spunsul CVM a returnat un r\u0103spuns nul."},
    {"ADF-MF-16034", "R\u0103spunsul CVM a returnat un FeatureContextAccessor nul."},
    {"ADF-MF-16035", "R\u0103spunsul JS returnat este nul."},
    {"ADF-MF-16036", "Nu se pot trimite apel\u0103ri JavaScript c\u0103tre _Control_Channel_."},
    {"ADF-MF-16037", "Eroare I/O"},
    {"ADF-MF-16038", "Eroare la eliminarea fi\u015Fierului."},
    {"ADF-MF-16039", "Eroare la copierea fi\u015Fierului."},
    {"ADF-MF-16040", "Lipse\u015Fte fi\u015Fierul a\u015Fteptat."},
    {"ADF-MF-16041", "Eroare la mutarea fi\u015Fierului."},
    {"ADF-MF-16042", "Directorul nu a putut fi creat."},
    {"ADF-MF-16043", "Eroare la desc\u0103rcare"},
    {"ADF-MF-16044", "Conexiunea nu a putut fi creat\u0103"},
    {"ADF-MF-16045", "A survenit o eroare nea\u015Fteptat\u0103 la desc\u0103rcarea fi\u015Fierului."},
    {"ADF-MF-16046", "Autentificare nereu\u015Fit\u0103"},
    {"ADF-MF-16047", "Nu au fost g\u0103site numele de utilizator \u015Fi parola."},
    {"ADF-MF-16048", "Fi\u015Fierul nu a putut fi desc\u0103rcat, din cauza unui e\u015Fec de autentificare."},
    {"ADF-MF-16049", "Document container nevalid"},
    {"ADF-MF-16050", "A fost \u00EEnt\u00E2lnit elementul 'feature' \u00EEn timpul proces\u0103rii unui 'feature' activ."},
    {"ADF-MF-16051", "ID-ul caracteristicii, '_Control_Channel_' este \u00EEn conflict cu un nume de identificator VM Channel rezervat"},
    {"ADF-MF-16052", "Clasa 'OracleAdfmfFeature' a fost ini\u0163ializat\u0103 cu un tip de element gre\u015Fit."},
    {"ADF-MF-16053", "Stare gre\u015Fit\u0103"},
    {"ADF-MF-16054", "URL-ul fi\u015Fierului nu poate fi nul"},
    {"ADF-MF-16055", "S-a \u00EEncercat ad\u0103ugarea unui obiect care nu era o cerere ASIHTTPRequest pt. ASINetworkQueue"},
    {"ADF-MF-16056", "Eroare la crearea contactului"},
    {"ADF-MF-16057", "Eroare la eliminarea contactului"},
    {"ADF-MF-16058", "Eroare - Argument nevalid"},
    {"ADF-MF-16059", "Eroare de expirare"},
    {"ADF-MF-16060", "Eroare la opera\u0163ia \u00EEn a\u015Fteptare"},
    {"ADF-MF-16061", "Eroare I/O"},
    {"ADF-MF-16062", "Eroare - Nu este acceptat"},
    {"ADF-MF-16063", "Eroare - Permisiune refuzat\u0103"},
    {"ADF-MF-16064", "Eroare necunoscut\u0103"},
    {"ADF-MF-16066", "Clas\u0103 nevalid\u0103"},
    {"ADF-MF-16067", "Lipse\u015Fte o implementare a unei func\u0163ii obligatorii. Activa\u0163i depanarea pt. a jurnaliza informa\u0163ii despre clas\u0103."},
    {"ADF-MF-16068", "Clasa pt. vizualizarea caracteristicii nu a fost g\u0103sit\u0103."},
    {"ADF-MF-16069", "Clasa pt. vizualizarea caracteristicii nu a putut fi creat\u0103."},
    {"ADF-MF-16070", "Controllerul de vizualizare a transmis o vizualizare de caracteristic\u0103 nul\u0103."},
    {"ADF-MF-16071", "Clasa nu reprezint\u0103 un tip de vizualizare valid. Subclasa acceptat\u0103 \u00EEn prezent trebuie s\u0103 fac\u0103 parte din UIView sau UIViewController"},
    {"ADF-MF-16072", "Nu a fost g\u0103sit\u0103 o conexiune HttpURLConnection utilizat\u0103 de o caracteristic\u0103."},
    {"ADF-MF-16073", "O conexiune HttpURLConnection utilizat\u0103 de o caracteristic\u0103 are un URL nul."},
    {"ADF-MF-16074", "Mesaj nevalid"},
    {"ADF-MF-16075", " Tipul de mesaj specificat este necunoscut."},
    {"ADF-MF-16076", "Eroare de conectare"},
    {"ADF-MF-16077", "Eroare de configurare"},
    {"ADF-MF-16078", " E\u015Fec la \u00EEnc\u0103rcarea UIWebView"},
    {"ADF-MF-16079", " E\u015Fec la \u00EEnc\u0103rcarea URL-ului '%@' pt. caracteristic\u0103: %@"},
    {"ADF-MF-16080", "Contacta\u0163i administratorul."},
    {"ADF-MF-16081", "Serverul de conectare nu poate fi contactat."},
    {"ADF-MF-16082", "Nume de utilizator sau parol\u0103 nevalide. Dac\u0103 problema persist\u0103, contacta\u0163i administratorul de sistem."},
    {"ADF-MF-16083", "Eroare de configurare. Contacta\u0163i administratorul."},
    {"ADF-MF-16084", "ACS a e\u015Fuat"},
    {"ADF-MF-16085", "Configura\u0163ie ACS nevalid\u0103. Obiectul de utilizator nu a fost preluat corect, din cauza unei erori de configurare ACS. Este posibil ca utilizatorul s\u0103 nu fie \u00EEnregistrat \u00EEn ACS. Contacta\u0163i administratorul."},
    {"ADF-MF-16086", "Serverul nu poate fi contactat. Asigura\u0163i-v\u0103 c\u0103 dispozitivul dvs. este conectat la internet."},
    {"ADF-MF-16087", "Nume de utilizator sau parol\u0103 nevalid\u0103. \u00CEncerca\u0163i din nou."},
    {"ADF-MF-16088", "Eroare de configurare. URL-ul serviciului de control al accesului lipse\u015Fte. Contacta\u0163i administratorul."},
    {"ADF-MF-16089", "A\u0163i dep\u0103\u015Fit num\u0103rul maxim de \u00EEncerc\u0103ri de conectare. Contul dvs. a fost blocat. Contacta\u0163i administratorul."},
    {"ADF-MF-16090", "Verificarea schimb\u0103rilor de configurare nu a putut fi efectuat\u0103. Verifica\u0163i-v\u0103 conexiunea la re\u0163ea sau contacta\u0163i un administrator."},
    {"ADF-MF-16091", "Configura\u0163iile nu au putut fi actualizate din serviciul de configurare."},
    {"ADF-MF-16092", "Mesaj formatat gre\u015Fit"},
    {"ADF-MF-16093", "Nu este permis un mesaj de cerere gol."},
    {"ADF-MF-16094", "Mesaj neacceptat"},
    {"ADF-MF-16095", "Mesajele de sistem nu sunt acceptate pe acest canal"},
    {"ADF-MF-16096", "Cerere de sistem nevalid\u0103 %@"},
    {"ADF-MF-16097", "Mesajele de aplica\u0163ie nu sunt acceptate pe acest canal"},
    {"ADF-MF-16098", "Cerere de aplica\u0163ie nevalid\u0103 %@"},
    {"ADF-MF-16099", "Mesaj netratat"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Tip: %d Corp: %@"},
    {"ADF-MF-16101", "S-a primit un mesaj de r\u0103spuns nesolicitat"},
    {"ADF-MF-16102", "S-a primit un tip de mesaj necunoscut"},
    {"ADF-MF-16103", "AdfChannel.handle - Eroare la tratarea mesajului VMChannel: %@ - EROARE: %@"},
    {"ADF-MF-16104", "Nu s-a fost '%@'. Eroarea generat\u0103 este: '%@'"},
    {"ADF-MF-16105", "Accesul la dispozitiv a fost dezactivat pt. caracteristica '%@': url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16106", "URL-ul nu are permisiunea de accesare a dispozitivului pt. caracteristica '%@': url:%@, baseUrl:%@, msg:%@"},
    {"ADF-MF-16107", "EROARE la whitelist: %@"},
    {"ADF-MF-16108", "L\u0103\u0163imea/\u00CEn\u0103l\u0163imea actualizat\u0103 nu a putut fi trimis\u0103 c\u0103tre Java"},
    {"ADF-MF-16109", "Nu s-a putut efectua \u00EEnregistrarea pt. evenimentele de schimbare a st\u0103rii re\u0163elei. Starea re\u0163elei nu va fi disponibil\u0103"},
    {"ADF-MF-16110", "Nu a fost definit\u0103 conexiunea prestabilit\u0103, '%@', pt. conectare."},
    {"ADF-MF-16111", "Din aspectul '%@' lipse\u015Fte o familie. Se ignor\u0103."},
    {"ADF-MF-16112", "Familia de aspecte active '%@' nu a returnat niciun aspect."},
    {"ADF-MF-16113", "Ata\u015Famentul %@ nu a putut fi g\u0103sit sau citit"},
    {"ADF-MF-16114", "%@ nu accept\u0103 deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "%@ nu este definit \u00EEn vizualizarea web. Apelarea pt. rezultatul JavaScript a fost abandonat."},
    {"ADF-MF-16116", "A survenit o problem\u0103 la apelarea func\u0163iei '%@': %@"},
    {"ADF-MF-16117", "EROARE: a survenit o excep\u0163ie la execu\u0163ia reapel\u0103rii %d: %@"},
    {"ADF-MF-16118", "Eroare de autentificare \u00EEn aplica\u0163ie. Motivul este: %@"},
    {"ADF-MF-16119", "Eroare de autentificare \u00EEn aplica\u0163ie. Caracteristica este dezactivat\u0103. Motivul este: %@"},
    {"ADF-MF-16120", "Eroare de autentificare. \u00CEncerca\u0163i din nou."},
    {"ADF-MF-16121", "ACS a returnat eroarea: %@"},
    {"ADF-MF-16122", "ACS nu este configurat pt. conexiunea %@. Obiectele pt. utilizatori nu sunt \u00EEnregistrate."},
    {"ADF-MF-16123", "E\u015Fec la conectarea la nivel de aplica\u0163ie, din cauza contextului de autentificare lips\u0103."},
    {"ADF-MF-16124", "Fi\u015Fierul exist\u0103 la calea din cache"},
    {"ADF-MF-16125", "Nu se poate crea un director pt. cache-ul de la '%@', deoarece exist\u0103 deja un fi\u015Fier"},
    {"ADF-MF-16126", "E\u015Fec la crearea directorului din cache"},
    {"ADF-MF-16127", "E\u015Fec la crearea unui director pt. cache-ul de la '%@'"},
    {"ADF-MF-16128", "E\u015Fec la traversarea directorului din cache"},
    {"ADF-MF-16129", "Listarea directorului din cache a e\u015Fuat la calea '%@'"},
    {"ADF-MF-16130", "E\u015Fec la eliminarea fi\u015Fierului din cache"},
    {"ADF-MF-16131", "E\u015Fec la eliminarea datelor din cache, de la calea '%@'"},
    {"ADF-MF-16132", "Acum va surveni e\u015Fecul, deoarece configura\u0163ia nu a putut fi desc\u0103rcat\u0103."},
    {"ADF-MF-16133", "Afi\u015Farea caracteristicii a e\u015Fuat"},
    {"ADF-MF-16134", "Caracteristica nu a putut fi afi\u015Fat\u0103. \u00CEncercarea de afi\u015Fare a caracteristicii '%@' a e\u015Fuat. EROARE: %@"},
    {"ADF-MF-16135", "Eroare la controller aplica\u0163ie"},
    {"ADF-MF-16136", "Folderul '%@' pt. controllerul aplica\u0163iei nu exist\u0103."},
    {"ADF-MF-16137", "Fi\u015Fierul de propriet\u0103\u0163i: %@ nu a putut fi \u00EEnc\u0103rcat - EROARE: %@"},
    {"ADF-MF-16138", "Eroare la serializarea return\u0103rii: %@"},
    {"ADF-MF-16139", "FeatureId nu a putut fi determinat. Se abandoneaz\u0103 apelul clasei Java."},
    {"ADF-MF-16140", "Verificarea canalului CVM a e\u015Fuat."},
    {"ADF-MF-16141", "CVM a returnat un tip de obiect nea\u015Fteptat: %@"},
    {"ADF-MF-16142", "Nu se poate trimite mesajul"},
    {"ADF-MF-16143", "Mesajul nu s-a putut trimite, deoarece pe acest dispozitiv nu sunt disponibile mesajele de text."},
    {"ADF-MF-16144", "Nu s-a putut trimite mesajul, pt. c\u0103 nu s-a putut prelua redactorul de mesaje text."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Nu s-a specificat 'classname'"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - Apelarea morphClassName a cauzat o eroare: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - 'classname' morphClassName a e\u015Fuat."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - Nu s-a specificat 'method'"},
    {"ADF-MF-16149", "Nu s-a putut crea clasa: %@"},
    {"ADF-MF-16150", "E\u015Fec la crearea tipului de obiect: %@"},
    {"ADF-MF-16151", "Instan\u0163a pt. clasa %@ nu r\u0103spunde pt. selectorul '%@'."},
    {"ADF-MF-16152", "La invocarea '%@' a survenit eroarea: %@"},
    {"ADF-MF-16153", "Serializarea rezultatului din '%@' \u00EEn tipul %@ a dus la o eroare: %@"},
    {"ADF-MF-16154", "Serializarea rezultatului din '%@' \u00EEn tipul %@ a generat valoarea zero."},
    {"ADF-MF-16155", "credentialStoreKey pt. conexiunea %@ nu poate avea valoarea zero"},
    {"ADF-MF-16156", "credentialStoreKey pt. conexiune nu poate avea valoarea zero"},
    {"ADF-MF-16157", "A survenit o eroare de conectare general\u0103. Probabil c\u0103 utilizatorul a introdus acredit\u0103ri nevalide sau configura\u0163ia conexiunii este eronat\u0103. De exemplu, e posibil ca URL-ul de conectare \u015Fi/sau numele cookie-ului s\u0103 fie gre\u015Fite sau s\u0103 lipseasc\u0103."},
    {"ADF-MF-16158", "Serverul nu a putut fi contactat. Asigura\u0163i-v\u0103 c\u0103 sunte\u0163i conectat la internet."},
    {"ADF-MF-16159", "Eroare la threadShellInitializationComplete: %@"},
    {"ADF-MF-16160", "Eroare la paintMirrorLoop: %@"},
    {"ADF-MF-16161", "ACS nu a fost configurat pt. conexiunea prestabilit\u0103 \u015Fi caracteristicile restr\u00E2nse nu sunt disponibile."},
    {"ADF-MF-16162", "Eroare la numele de utilizator"},
    {"ADF-MF-16163", "Numele de utilizator \u015Fi/sau numele clientului sunt diferite de cele ini\u0163iale. Trebuie s\u0103 corecta\u0163i numele de utilizator \u015Fi/sau numele clientului dac\u0103 le-a\u0163i introdus gre\u015Fit. Pentru a v\u0103 conecta drept utilizator nou, trebuie s\u0103 ie\u015Fi\u0163i mai \u00EEnt\u00E2i din aplica\u0163ie."},
    {"ADF-MF-16164", "Lipse\u015Fte numele antetului pt. mai mul\u0163i clien\u0163i"},
    {"ADF-MF-16165", "Nu se poate efectua autentificarea, deoarece nu exist\u0103 suficiente informa\u0163ii pt. autentificarea \u00EEntr-o aplica\u0163ie multi-tenant. Din configura\u0163ie lipse\u015Fte numele antetului multi-tenant. Contacta\u0163i administratorul."},
    {"ADF-MF-16166", "Nu a fost introdus numele clientului"},
    {"ADF-MF-16167", "Nu se poate autentifica, deoarece nu a fost furnizat numele clientului. \u00CEncerca\u0163i din nou."},
    {"ADF-MF-16168", "Se va \u00EEncerca o conectare la nivel de aplica\u0163ie. Server=%@ pt. utilizatorul=%@"},
    {"ADF-MF-16169", "Conectarea la nivel de aplica\u0163ie a reu\u015Fit"},
    {"ADF-MF-16170", "OMCredentialStore nu a returnat proprietatea pt. kSecAttrLabel."},
    {"ADF-MF-16171", "Obiectele de utilizator din aplica\u0163ie sunt preluate din baza de date de acredit\u0103ri: %@"},
    {"ADF-MF-16172", "Testarea autentific\u0103rii utilizatorului a returnat %@."},
    {"ADF-MF-16173", "Conectarea la nivel de caracteristic\u0103 a e\u015Fuat din cauza unei situa\u0163ii nea\u015Fteptate."},
    {"ADF-MF-16174", "\u00CEncercare de conectare la nivel de caracteristic\u0103 pt. utilizatorul=%@."},
    {"ADF-MF-16175", "\u00CEncercare de deconectare la nivel de caracteristic\u0103"},
    {"ADF-MF-16176", "Obiectele de utilizator sunt extrase ca \u015Fi cum ar fi o caracteristic\u0103 de conectare de la distan\u0163\u0103."},
    {"ADF-MF-16177", "Autentificare reu\u015Fit\u0103."},
    {"ADF-MF-16178", "R\u0103spuns returnat pt. obiecte utilizator=%@"},
    {"ADF-MF-16179", "Privilegii obiecte utilizator returnate=%@ roluri=%@"},
    {"ADF-MF-16180", "Se invoc\u0103 ACS cu payloadul=%@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout: authContext nu a putut fi ob\u0163inut."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated: pausedFeature nu a putut fi ob\u0163inut\u0103."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated: authContext nu a putut fi ob\u0163inut."},
    {"ADF-MF-16184", "CredentialStoreHandler.login: pausedFeature nu a putut fi ob\u0163inut\u0103."},
    {"ADF-MF-16185", "CredentialStoreHandler.login: authContext nu a putut fi ob\u0163inut."},
    {"ADF-MF-16186", "Eroare de configurare"},
    {"ADF-MF-16187", "Nu este definit\u0103 conexiunea pt. conectarea \u00EEn aplica\u0163ie. Aceast\u0103 aplica\u0163ie nu poate fi rulat\u0103. Contacta\u0163i administratorul."},
    {"ADF-MF-16188", "Conexiunea pt. conectarea la caracteristic\u0103 nu este definit\u0103. Aceast\u0103 caracteristic\u0103 nu poate fi accesat\u0103. Contacta\u0163i administratorul."},
    {"ADF-MF-16189", "Deconectare"},
    {"ADF-MF-16190", "S-a ini\u0163ializat deconectarea. Aplica\u0163ia se va \u00EEnchide."},
    {"ADF-MF-16191", "Eroare de configurare a conexiunii pt. conectare. {0}. Contacta\u0163i administratorul."},
    {"ADF-MF-16192", "Cheia bazei de date pt. acredit\u0103ri nu a fost specificat\u0103."},
    {"ADF-MF-16193", "Nume de utilizator \u015Fi/sau parol\u0103 lips\u0103"},
    {"ADF-MF-16195", "Eroare \u00EEn cheia bazei de date de acredit\u0103ri compozite"},
    {"ADF-MF-16196", "URL ACS nevalid"},
    {"ADF-MF-16197", "URL de deconectare nevalid"},
    {"ADF-MF-16198", "URL de conectare nevalid"},
    {"ADF-MF-16199", "Nu a fost specificat cookie-ul"},
    {"ADF-MF-16200", "Durata pt. expirarea de inactivitate trebuie s\u0103 fie de 10 sau mai mult, iar durata pt. expirarea sesiunii trebuie s\u0103 fie de 30 sau mai mult, \u015Fi mai mare dec\u00E2t durata pt. expirarea de inactivitate."},
    {"ADF-MF-16201", "Eroare de configurare a conexiunii pt. conectare"},
    {"ADF-MF-16202", "URL-ul de autentificare a r\u0103spuns cu un cod de r\u0103spuns HTTP ilegal. Nu este un punct final de autentificare de baz\u0103. Contacta\u0163i administratorul."},
    {"ADF-MF-16203", "Fi\u015Fierul nu a fost g\u0103sit: %@"},
    {"ADF-MF-16204", "Mesajul de e-mail nu a fost salvat \u015Fi nici plasat \u00EEn coad\u0103, probabil din cauza unei erori."},
    {"ADF-MF-16205", "A survenit o eroare la \u00EEncercarea de a salva mesajul de e-mail \u00EEn folderul cu ciorne."},
    {"ADF-MF-16206", "A survenit o eroare la \u00EEncercarea de a plasa \u00EEn coad\u0103 sau de a trimite mesajul de e-mail."},
    {"ADF-MF-16207", "A survenit o eroare necunoscut\u0103 la \u00EEncercarea de a redacta sau de a trimite un e-mail"},
    {"ADF-MF-16208", "A survenit o eroare necunoscut\u0103 la \u00EEncercarea de a redacta sau de a trimite un mesaj text"},
    {"ADF-MF-16209", "Fi\u015Fierul nu a fost g\u0103sit"},
    {"ADF-MF-16210", "A fost g\u0103sit un prefix nevalid pt. maparea URI. Prefixul %@ este deja mapat la URI-ul %@, iar re-maparea prefixului la URI-ul %@ nu este permis\u0103"},
    {"ADF-MF-16211", "A fost g\u0103sit un prefix nevalid pt. maparea URI. Prefixul %@ este deja mapat la URI-ul %@, iar re-maparea prefixului la URI-ul %@ nu este permis\u0103"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
