// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
import java.util.ListResourceBundle;

public class iOSErrorBundle_fr extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16001", "La classe %@ a g\u00E9n\u00E9r\u00E9 une erreur lors de l'allocation et de l'initialisation - Abandon de l'ajout du processus d'\u00E9coute de cycle de vie d'application - ERREUR : %@"},
    {"ADF-MF-16002", "Utilisation non valide"},
    {"ADF-MF-16003", "Cette fonction doit \u00EAtre appel\u00E9e sur le thread principal."},
    {"ADF-MF-16004", "Cette fonction ne doit PAS \u00EAtre appel\u00E9e sur le thread principal."},
    {"ADF-MF-16005", "Fichier de configuration incorrect"},
    {"ADF-MF-16006", "Configuration non valide"},
    {"ADF-MF-16007", "Impl\u00E9menteur AdfmfContainerUtilities non configur\u00E9."},
    {"ADF-MF-16008", "Classe de l'impl\u00E9menteur AdfmfContainerUtilities introuvable."},
    {"ADF-MF-16009", "Impossible de cr\u00E9er l'impl\u00E9menteur AdfmfContainerUtilities."},
    {"ADF-MF-16010", "Demande incorrecte"},
    {"ADF-MF-16011", "Impossible de t\u00E9l\u00E9charger le fichier : erreur 400 Demande incorrecte."},
    {"ADF-MF-16012", "Autorisation refus\u00E9e"},
    {"ADF-MF-16013", "Impossible de t\u00E9l\u00E9charger le fichier : erreur 401 Autorisation refus\u00E9e (nom utilisateur ou mot de passe incorrect)."},
    {"ADF-MF-16014", "Acc\u00E8s interdit"},
    {"ADF-MF-16015", "Impossible de t\u00E9l\u00E9charger le fichier : erreur 403 Acc\u00E8s interdit."},
    {"ADF-MF-16016", "Fichier introuvable"},
    {"ADF-MF-16017", "Impossible de t\u00E9l\u00E9charger le fichier : erreur 404 Fichier introuvable."},
    {"ADF-MF-16018", "Passerelle incorrecte"},
    {"ADF-MF-16019", "Impossible de t\u00E9l\u00E9charger le fichier : erreur 502 Passerelle incorrecte."},
    {"ADF-MF-16020", "Service non disponible"},
    {"ADF-MF-16021", "Impossible de t\u00E9l\u00E9charger le fichier : erreur 503 Service indisponible."},
    {"ADF-MF-16022", "Argument incorrect"},
    {"ADF-MF-16023", "Un nom de package nil a \u00E9t\u00E9 transmis \u00E0 [oraADFLogger getLogger:]."},
    {"ADF-MF-16024", "L'URL du fichier d'erreurs ne peut pas \u00EAtre nil"},
    {"ADF-MF-16025", "Le nom de la propri\u00E9t\u00E9 ne peut pas \u00EAtre nil."},
    {"ADF-MF-16026", "Nombre d'arguments insuffisant."},
    {"ADF-MF-16027", "Nom de classe manquant."},
    {"ADF-MF-16028", "M\u00E9thode manquante."},
    {"ADF-MF-16029", "ID de fonctionnalit\u00E9 manquant."},
    {"ADF-MF-16030", "Type d'appel non reconnu"},
    {"ADF-MF-16031", "El\u00E9ment FeatureContext introuvable."},
    {"ADF-MF-16032", "R\u00E9ponse inattendue"},
    {"ADF-MF-16033", "La r\u00E9ponse CVM renvoy\u00E9e est nil. "},
    {"ADF-MF-16034", "La r\u00E9ponse CVM a renvoy\u00E9 un \u00E9l\u00E9ment FeatureContextAccessor nil."},
    {"ADF-MF-16035", "La r\u00E9ponse JS renvoy\u00E9e est nil."},
    {"ADF-MF-16036", "Impossible d'envoyer les appels JavaScript vers l'ID _Control_Channel_."},
    {"ADF-MF-16037", "Erreur d'entr\u00E9e-sortie"},
    {"ADF-MF-16038", "Erreur lors de la suppression du fichier."},
    {"ADF-MF-16039", "Erreur lors de la copie du fichier."},
    {"ADF-MF-16040", "Le fichier attendu est manquant."},
    {"ADF-MF-16041", "Erreur lors du d\u00E9placement du fichier."},
    {"ADF-MF-16042", "Impossible de cr\u00E9er le r\u00E9pertoire."},
    {"ADF-MF-16043", "Erreur de t\u00E9l\u00E9chargement"},
    {"ADF-MF-16044", "Impossible de cr\u00E9er la connexion"},
    {"ADF-MF-16045", "Une erreur inattendue s'est produite lors du t\u00E9l\u00E9chargement du fichier."},
    {"ADF-MF-16046", "Echec d'authentification"},
    {"ADF-MF-16047", "Le nom utilisateur ou le mot de passe est manquant."},
    {"ADF-MF-16048", "Impossible de t\u00E9l\u00E9charger le fichier en raison d'un \u00E9chec d'authentification."},
    {"ADF-MF-16049", "Document de conteneur non valide"},
    {"ADF-MF-16050", "Un \u00E9l\u00E9ment 'feature' a \u00E9t\u00E9 d\u00E9tect\u00E9 lors du traitement d'un \u00E9l\u00E9ment 'feature' actif."},
    {"ADF-MF-16051", "L''ID de fonctionnalit\u00E9 '_Control_Channel_' est en conflit avec un nom r\u00E9serv\u00E9 d''identificateur de canal de machine virtuelle."},
    {"ADF-MF-16052", "La classe 'OracleAdfmfFeature' a \u00E9t\u00E9 initialis\u00E9e avec un type d'\u00E9l\u00E9ment incorrect."},
    {"ADF-MF-16053", "Etat incorrect"},
    {"ADF-MF-16054", "L'URL du fichier ne peut pas \u00EAtre nil"},
    {"ADF-MF-16055", "Tentative d'ajout d'un objet autre que ASIHTTPRequest \u00E0 ASINetworkQueue"},
    {"ADF-MF-16056", "Erreur de cr\u00E9ation de contact"},
    {"ADF-MF-16057", "Erreur de suppression de contact"},
    {"ADF-MF-16058", "Erreur d'argument non valide"},
    {"ADF-MF-16059", "Erreur de temporisation"},
    {"ADF-MF-16060", "Erreur de l'op\u00E9ration en attente"},
    {"ADF-MF-16061", "Erreur d'E/S"},
    {"ADF-MF-16062", "Erreur de non-prise en charge"},
    {"ADF-MF-16063", "Erreur d'autorisation refus\u00E9e"},
    {"ADF-MF-16064", "Erreur inconnue"},
    {"ADF-MF-16066", "Classe non valide"},
    {"ADF-MF-16067", "L'impl\u00E9mentation d'une fonction obligatoire est manquante dans la classe. Activez le d\u00E9bogage pour journaliser les informations sur la classe."},
    {"ADF-MF-16068", "Classe de vue de fonctionnalit\u00E9 introuvable."},
    {"ADF-MF-16069", "Impossible de cr\u00E9er la classe de vue de fonctionnalit\u00E9."},
    {"ADF-MF-16070", "Le contr\u00F4leur de vue a fourni une vue nil pour la vue de fonctionnalit\u00E9."},
    {"ADF-MF-16071", "La classe n'est pas un type de vue valide. La sous-classe actuellement prise en charge doit provenir de : UIView ou UIViewController"},
    {"ADF-MF-16072", "L'\u00E9l\u00E9ment HttpURLConnection utilis\u00E9 par la fonctionnalit\u00E9 est introuvable."},
    {"ADF-MF-16073", "Un \u00E9l\u00E9ment HttpURLConnection utilis\u00E9 par la fonctionnalit\u00E9 poss\u00E8de une URL nil."},
    {"ADF-MF-16074", "Message non valide"},
    {"ADF-MF-16075", "Type de message inconnu indiqu\u00E9 par le message."},
    {"ADF-MF-16076", "Erreur de connexion"},
    {"ADF-MF-16077", "Erreur de configuration"},
    {"ADF-MF-16078", " Echec lors du chargement de l'\u00E9l\u00E9ment UIWebView"},
    {"ADF-MF-16079", " Echec du chargement de la fonctionnalit\u00E9 '%@' ; URL : %@"},
    {"ADF-MF-16080", "Contactez l'administrateur."},
    {"ADF-MF-16081", "Le serveur de connexion n'est pas accessible."},
    {"ADF-MF-16082", "Nom utilisateur/mot de passe non valide. Si le probl\u00E8me persiste, contactez l'administrateur syst\u00E8me."},
    {"ADF-MF-16083", "Erreur de configuration. Contactez l'administrateur. "},
    {"ADF-MF-16084", "Echec d'ACS"},
    {"ADF-MF-16085", "Configuration ACS non valide. L'objet utilisateur n'a pas \u00E9t\u00E9 extrait correctement en raison d'une erreur de configuration ACS. L'utilisateur n'est peut-\u00EAtre pas inscrit aupr\u00E8s d'ACS. Contactez l'administrateur."},
    {"ADF-MF-16086", "Le serveur n'est pas accessible. Assurez-vous que le dispositif est connect\u00E9 \u00E0 Internet."},
    {"ADF-MF-16087", "Nom utilisateur/mot de passe non valide. R\u00E9essayez."},
    {"ADF-MF-16088", "Erreur de configuration. L'URL du service de contr\u00F4le d'acc\u00E8s est manquante. Contactez l'administrateur."},
    {"ADF-MF-16089", "Vous avez d\u00E9pass\u00E9 le nombre maximal autoris\u00E9 de tentatives de connexion. Vous \u00EAtes bloqu\u00E9. Contactez l'administrateur."},
    {"ADF-MF-16090", "Le contr\u00F4le des modifications de configuration n'a pas pu \u00EAtre r\u00E9alis\u00E9. V\u00E9rifiez votre connexion r\u00E9seau ou contactez un administrateur."},
    {"ADF-MF-16091", "Impossible de mettre \u00E0 jour les configurations \u00E0 partir du service de configuration."},
    {"ADF-MF-16092", "Format du message incorrect"},
    {"ADF-MF-16093", "Les messages de demande vides ne sont pas autoris\u00E9s."},
    {"ADF-MF-16094", "Message non pris en charge"},
    {"ADF-MF-16095", "Les messages syst\u00E8me ne sont pas pris en charge sur ce canal"},
    {"ADF-MF-16096", "Demande syst\u00E8me non valide %@"},
    {"ADF-MF-16097", "Les messages d'application ne sont pas pris en charge sur ce canal"},
    {"ADF-MF-16098", "Demande d'application non valide %@"},
    {"ADF-MF-16099", "Message non g\u00E9r\u00E9"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId : %d Type : %d Corps : %@"},
    {"ADF-MF-16101", "Message de r\u00E9ponse non sollicit\u00E9 re\u00E7u"},
    {"ADF-MF-16102", "Type de message inconnu re\u00E7u"},
    {"ADF-MF-16103", "AdfChannel.handle - Erreur lors de la gestion du message VMChannel : %@ - ERREUR : %@"},
    {"ADF-MF-16104", "Aucun \u00E9l\u00E9ment '%@' indiqu\u00E9. Erreur supprim\u00E9e : '%@'"},
    {"ADF-MF-16105", "Acc\u00E8s au dispositif d\u00E9sactiv\u00E9 pour la fonctionnalit\u00E9 '%@' : url : %@, baseUrl : %@, msg : %@"},
    {"ADF-MF-16106", "URL non autoris\u00E9e pour l''acc\u00E8s au dispositif pour la fonctionnalit\u00E9 '%@' : url : %@, baseUrl : %@, msg : %@"},
    {"ADF-MF-16107", "ERREUR lors de la cr\u00E9ation de la liste blanche : %@"},
    {"ADF-MF-16108", "Impossible d'envoyer la largeur/hauteur mise \u00E0 jour c\u00F4t\u00E9 Java"},
    {"ADF-MF-16109", "Inscription impossible pour les \u00E9v\u00E9nements de modification de statut du r\u00E9seau. Le statut du r\u00E9seau sera indisponible"},
    {"ADF-MF-16110", "La connexion par d\u00E9faut '%@' n'est pas d\u00E9finie."},
    {"ADF-MF-16111", "Famille manquante pour l'apparence '%@'. Ignor\u00E9e."},
    {"ADF-MF-16112", "La famille d'apparences active '%@' n'a renvoy\u00E9 aucune apparence."},
    {"ADF-MF-16113", "La pi\u00E8ce jointe %@ est introuvable ou illisible"},
    {"ADF-MF-16114", "%@ ne prend pas en charge deliverResponseJson:toCallbackSet:forRequest:"},
    {"ADF-MF-16115", "%@ n''est pas d\u00E9fini dans la vue Web. Abandon de l''appel de r\u00E9sultat JavaScript."},
    {"ADF-MF-16116", "Un probl\u00E8me est survenu lors de l'appel de la fonction '%@' : %@"},
    {"ADF-MF-16117", "ERREUR : une exception a \u00E9t\u00E9 d\u00E9tect\u00E9e lors de l'ex\u00E9cution du callback %d : %@"},
    {"ADF-MF-16118", "Erreur d'authentification de l'application. Raison = %@"},
    {"ADF-MF-16119", "Erreur d'authentification de la fonctionnalit\u00E9. Fonctionnalit\u00E9 d\u00E9sactiv\u00E9e. Raison = %@"},
    {"ADF-MF-16120", "Erreur d'authentification. R\u00E9essayez."},
    {"ADF-MF-16121", "ACS a renvoy\u00E9 une erreur : %@"},
    {"ADF-MF-16122", "ACS n'est pas configur\u00E9 pour une connexion %@. Les objets utilisateur ne sont pas inscrits."},
    {"ADF-MF-16123", "Echec de la connexion au niveau application en raison d'un contexte d'authentification manquant."},
    {"ADF-MF-16124", "Le fichier existe dans le chemin du cache"},
    {"ADF-MF-16125", "Impossible de cr\u00E9er un r\u00E9pertoire pour le cache dans '%@', car un fichier existe d\u00E9j\u00E0"},
    {"ADF-MF-16126", "Echec de la cr\u00E9ation du r\u00E9pertoire cache"},
    {"ADF-MF-16127", "Echec de la cr\u00E9ation du r\u00E9pertoire pour le cache dans '%@'"},
    {"ADF-MF-16128", "Impossible de parcourir le r\u00E9pertoire cache"},
    {"ADF-MF-16129", "Echec de l'\u00E9num\u00E9ration du r\u00E9pertoire cache dans le chemin '%@'"},
    {"ADF-MF-16130", "Echec de la suppression du fichier cache"},
    {"ADF-MF-16131", "Echec de la suppression des donn\u00E9es mises en m\u00E9moire cache dans le chemin '%@'"},
    {"ADF-MF-16132", "Arr\u00EAt imm\u00E9diat car la configuration n'a pas pu \u00EAtre t\u00E9l\u00E9charg\u00E9e."},
    {"ADF-MF-16133", "Echec de l'affichage de la fonctionnalit\u00E9"},
    {"ADF-MF-16134", "Impossible d'afficher la fonctionnalit\u00E9. Echec de la tentative d'affichage de la fonctionnalit\u00E9 '%@'. ERREUR : %@"},
    {"ADF-MF-16135", "Erreur du contr\u00F4leur d'application"},
    {"ADF-MF-16136", "Le dossier du contr\u00F4leur d'application '%@' n'existe pas."},
    {"ADF-MF-16137", "Impossible de charger le fichier .properties : %@ - ERREUR : %@"},
    {"ADF-MF-16138", "Erreur lors de la s\u00E9rialisation du renvoi : %@"},
    {"ADF-MF-16139", "Impossible de d\u00E9terminer l'\u00E9l\u00E9ment FeatureId. Abandon de l'appel vers la classe Java."},
    {"ADF-MF-16140", "Echec de la v\u00E9rification du canal CVM."},
    {"ADF-MF-16141", "CVM a renvoy\u00E9 un type d''objet inattendu : %@"},
    {"ADF-MF-16142", "Impossible d'envoyer le message"},
    {"ADF-MF-16143", "Impossible d'envoyer un message car la messagerie textuelle n'est pas disponible sur ce dispositif."},
    {"ADF-MF-16144", "Impossible d'envoyer un message car le composeur de messages texte n'a pas pu \u00EAtre obtenu."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Le nom de classe n'a pas \u00E9t\u00E9 indiqu\u00E9"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - L'appel de morphClassName a entra\u00EEn\u00E9 une erreur : %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Echec du nom de classe morphClassName."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - La m\u00E9thode n'a pas \u00E9t\u00E9 indiqu\u00E9e"},
    {"ADF-MF-16149", "Impossible de cr\u00E9er la classe : %@"},
    {"ADF-MF-16150", "Echec de la cr\u00E9ation d'une instance d'un objet : %@"},
    {"ADF-MF-16151", "L'instance de classe %@ ne r\u00E9pond pas au s\u00E9lecteur '%@'."},
    {"ADF-MF-16152", "L'appel de '%@' a entra\u00EEn\u00E9 une erreur : %@"},
    {"ADF-MF-16153", "La s\u00E9rialisation du r\u00E9sultat \u00E0 partir de '%@' sur le type %@ a entra\u00EEn\u00E9 une erreur : %@"},
    {"ADF-MF-16154", "La s\u00E9rialisation du r\u00E9sultat \u00E0 partir de '%@' sur le type %@ a g\u00E9n\u00E9r\u00E9 la valeur nil."},
    {"ADF-MF-16155", "La cl\u00E9 credentialStoreKey pour la connexion %@ ne peut pas \u00EAtre nil"},
    {"ADF-MF-16156", "La cl\u00E9 credentialStoreKey pour la connexion ne peut pas \u00EAtre nil"},
    {"ADF-MF-16157", "Une erreur de connexion g\u00E9n\u00E9rale est survenue. L'utilisateur a peut-\u00EAtre entr\u00E9 des informations d'identification et de connexion non valides ou la configuration de la connexion contient peut-\u00EAtre des erreurs. Par exemple, l'URL de connexion et/ou le nom de cookie peuvent \u00EAtre manquants ou incorrects."},
    {"ADF-MF-16158", "Impossible d'acc\u00E9der au serveur. V\u00E9rifiez que vous \u00EAtes connect\u00E9 \u00E0 Internet."},
    {"ADF-MF-16159", "Erreur dans threadShellInitializationComplete : %@"},
    {"ADF-MF-16160", "Erreur dans paintMirrorLoop : %@"},
    {"ADF-MF-16161", "ACS n'est pas configur\u00E9 pour la connexion par d\u00E9faut et les fonctionnalit\u00E9s avec contrainte ne sont pas disponibles."},
    {"ADF-MF-16162", "Erreur dans le nom utilisateur"},
    {"ADF-MF-16163", "Le nom utilisateur et/ou le nom de locataire utilis\u00E9s sont diff\u00E9rents du nom utilisateur et/ou du nom de locataire d'origine. Vous devez corriger le nom utilisateur et/ou le nom de locataire si ceux que vous avez entr\u00E9s sont incorrects. Quittez l'application pour pouvoir vous connecter en tant que nouvel utilisateur."},
    {"ADF-MF-16164", "Le nom de l'en-t\u00EAte colocatif est manquant"},
    {"ADF-MF-16165", "Authentification impossible : les informations fournies pour l'authentification dans l'application colocative sont insuffisantes. Le nom de l'en-t\u00EAte colocatif est manquant pour la configuration. Contactez l'administrateur."},
    {"ADF-MF-16166", "Le nom du locataire n'a pas \u00E9t\u00E9 entr\u00E9"},
    {"ADF-MF-16167", "Authentification impossible car le nom du locataire n'a pas \u00E9t\u00E9 indiqu\u00E9. R\u00E9essayez."},
    {"ADF-MF-16168", "Une connexion au niveau application sera tent\u00E9e. Serveur = %@ pour l'utilisateur = %@"},
    {"ADF-MF-16169", "Connexion au niveau application \u00E9tablie."},
    {"ADF-MF-16170", "OMCredentialStore n'a renvoy\u00E9 aucune propri\u00E9t\u00E9 pour kSecAttrLabel."},
    {"ADF-MF-16171", "Les objets utilisateur de l'application sont extraits \u00E0 partir de la banque d'informations d'identification et de connexion : %@"},
    {"ADF-MF-16172", "Le test d'authentification utilisateur renvoie %@."},
    {"ADF-MF-16173", "Echec de la connexion au niveau fonctionnalit\u00E9 en raison d'une condition inattendue."},
    {"ADF-MF-16174", "Tentative de connexion au niveau fonctionnalit\u00E9 pour l'utilisateur = %@."},
    {"ADF-MF-16175", "Tentative de d\u00E9connexion au niveau fonctionnalit\u00E9."},
    {"ADF-MF-16176", "Les objets utilisateur sont extraits (pull) car il s'agit d'une connexion de fonctionnalit\u00E9 distante."},
    {"ADF-MF-16177", "Authentification effectu\u00E9e."},
    {"ADF-MF-16178", "r\u00E9ponse renvoy\u00E9e pour les objets utilisateur = %@"},
    {"ADF-MF-16179", "privil\u00E8ges renvoy\u00E9s pour les objets utilisateur = %@, r\u00F4les = %@"},
    {"ADF-MF-16180", "Appel d'ACS avec les donn\u00E9es trait\u00E9es = %@."},
    {"ADF-MF-16181", "CredentialStoreHandler.logout : authContext non obtenu."},
    {"ADF-MF-16182", "CredentialStoreHandler.isAuthenticated : pausedFeature non obtenu."},
    {"ADF-MF-16183", "CredentialStoreHandler.isAuthenticated : authContext non obtenu."},
    {"ADF-MF-16184", "CredentialStoreHandler.login : pausedFeature non obtenu."},
    {"ADF-MF-16185", "CredentialStoreHandler.login : authContext non obtenu."},
    {"ADF-MF-16186", "Erreur de configuration"},
    {"ADF-MF-16187", "La connexion \u00E0 l'application n'est pas d\u00E9finie. Impossible d'ex\u00E9cuter cette application. Contactez l'administrateur."},
    {"ADF-MF-16188", "La connexion \u00E0 la fonctionnalit\u00E9 n'est pas d\u00E9finie. Impossible d'ex\u00E9cuter cette fonctionnalit\u00E9. Contactez l'administrateur."},
    {"ADF-MF-16189", "D\u00E9connexion"},
    {"ADF-MF-16190", "La d\u00E9connexion a \u00E9t\u00E9 initi\u00E9e. L'application va \u00EAtre interrompue."},
    {"ADF-MF-16191", "Erreur de configuration de connexion. {0} Contactez l''administrateur."},
    {"ADF-MF-16192", "Cl\u00E9 de banque d'informations d'identification et de connexion non indiqu\u00E9e."},
    {"ADF-MF-16193", "Nom utilisateur et/ou mot de passe non valide ou manquant."},
    {"ADF-MF-16195", "Erreur dans la cl\u00E9 de la banque d'informations d'identification et de connexion composite."},
    {"ADF-MF-16196", "URL de service de contr\u00F4le d'acc\u00E8s non valide."},
    {"ADF-MF-16197", "URL de d\u00E9connexion non valide."},
    {"ADF-MF-16198", "URL de connexion non valide."},
    {"ADF-MF-16199", "Cookie non indiqu\u00E9."},
    {"ADF-MF-16200", "Le d\u00E9lai d'inactivit\u00E9 doit \u00EAtre d'au moins 10. La temporisation de session doit \u00EAtre d'au moins 30 et doit \u00EAtre sup\u00E9rieure au d\u00E9lai d'inactivit\u00E9."},
    {"ADF-MF-16201", "Erreur de configuration de connexion"},
    {"ADF-MF-16202", "L'URL d'authentification a renvoy\u00E9 un code de r\u00E9ponse HTTP interdit. Il ne s'agit pas d'une adresse d'authentification de base. Contactez l'administrateur."},
    {"ADF-MF-16203", "Fichier introuvable : %@"},
    {"ADF-MF-16204", "Le courriel n'a pas \u00E9t\u00E9 enregistr\u00E9 ni mis en file d'attente, probablement en raison d'une erreur."},
    {"ADF-MF-16205", "Une erreur est survenue lors de la tentative d'enregistrement du courriel dans le dossier Brouillons."},
    {"ADF-MF-16206", "Une erreur est survenue lors de la tentative de mise en file d'attente ou d'envoi du courriel."},
    {"ADF-MF-16207", "Une erreur inconnue est survenue lors de la tentative de composition ou d'envoi d'un courriel."},
    {"ADF-MF-16208", "Une erreur inconnue est survenue lors de la tentative de composition ou d'envoi d'un message texte."},
    {"ADF-MF-16209", "Fichier introuvable"},
    {"ADF-MF-16210", "Pr\u00E9fixe non valide d\u00E9tect\u00E9 dans la correspondance d'URI. Le pr\u00E9fixe %@ a d\u00E9j\u00E0 \u00E9t\u00E9 mis en correspondance avec l'URI %@. Une nouvelle mise en correspondance du pr\u00E9fixe avec l'URI %@ n'est pas autoris\u00E9e"},
    {"ADF-MF-16211", "Pr\u00E9fixe non valide d\u00E9tect\u00E9 dans la correspondance d'URI. L'URI %@ a d\u00E9j\u00E0 \u00E9t\u00E9 mis en correspondance avec le pr\u00E9fixe %@. Une nouvelle mise en correspondance de l'URI avec pr\u00E9fixe %@ n'est pas autoris\u00E9e"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_CLASS_INIT_ERROR_DURING_LIFECYCLE_ADD = "ADF-MF-16001";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_MAIN_THREAD = "ADF-MF-16003";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_BAD_CONFIG_FILE_TITLE = "ADF-MF-16005";
  public static final String PHRASE_KEY_INVALID_INVALID_CONFIGURATION = "ADF-MF-16006";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_MISSING = "ADF-MF-16007";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CLASS_NOT_FOUND = "ADF-MF-16008";
  public static final String PHRASE_KEY_INVALID_ADFMFCONTAINERUTILITIES_CANNOT_CREATE = "ADF-MF-16009";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST = "ADF-MF-16010";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_REQUEST_MSG = "ADF-MF-16011";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED = "ADF-MF-16012";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_UNAUTHORIZED_MSG = "ADF-MF-16013";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN = "ADF-MF-16014";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_FORBIDDEN_MSG = "ADF-MF-16015";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND = "ADF-MF-16016";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_NOT_FOUND_MSG = "ADF-MF-16017";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY = "ADF-MF-16018";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_BAD_GATEWAY_MSG = "ADF-MF-16019";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE = "ADF-MF-16020";
  public static final String PHRASE_KEY_INVALID_ORAADFREMOTEFILEMANAGER_SERVICE_UNAVAILABLE_MSG = "ADF-MF-16021";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_FILE_URL_MUST_BE_NON_NIL = "ADF-MF-16024";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TO_FEW_ARGS = "ADF-MF-16026";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_FEATURE_ID = "ADF-MF-16029";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_UNREOGNIZED_CALL_TYPE = "ADF-MF-16030";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_FC_MISSING = "ADF-MF-16031";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_IO_ERROR_TITLE = "ADF-MF-16037";
  public static final String PHRASE_KEY_ERROR_REMOVING_FILE = "ADF-MF-16038";
  public static final String PHRASE_KEY_ERROR_COPYING_FILE = "ADF-MF-16039";
  public static final String PHRASE_KEY_FILE_MISSING = "ADF-MF-16040";
  public static final String PHRASE_KEY_ERROR_MOVING_FILE = "ADF-MF-16041";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_DIR = "ADF-MF-16042";
  public static final String PHRASE_KEY_DOWNLOAD_ERROR_TITLE = "ADF-MF-16043";
  public static final String PHRASE_KEY_COULD_NOT_CREATE_CONNECTION = "ADF-MF-16044";
  public static final String PHRASE_KEY_UNEXPECTED_DOWNLOAD = "ADF-MF-16045";
  public static final String PHRASE_KEY_AUTH_FAIL_TITLE = "ADF-MF-16046";
  public static final String PHRASE_KEY_AUTH_NO_USR_PSW = "ADF-MF-16047";
  public static final String PHRASE_KEY_AUTH_FILE_CANNOT_DOWNLOAD = "ADF-MF-16048";
  public static final String PHRASE_KEY_INVALID_CONTAINER_DOC = "ADF-MF-16049";
  public static final String PHRASE_KEY_EMBEDDED_FEATURE = "ADF-MF-16050";
  public static final String PHRASE_KEY_BAD_USE_OF_RESERVE_ID = "ADF-MF-16051";
  public static final String PHRASE_KEY_ORACLEADFMFFEATURE_WRONG_ELEM_TYPE = "ADF-MF-16052";
  public static final String PHRASE_KEY_BAD_STATE = "ADF-MF-16053";
  public static final String PHRASE_KEY_BAD_STATE_NIL_FILE_URL = "ADF-MF-16054";
  public static final String PHRASE_KEY_BAD_NON_ASIHTTPREQUEST = "ADF-MF-16055";
  public static final String PHRASE_KEY_CREATE_CONTACT_ERROR = "ADF-MF-16056";
  public static final String PHRASE_KEY_REMOVE_CONTACT_ERROR = "ADF-MF-16057";
  public static final String PHRASE_KEY_CNTACT_INVALID_ARG = "ADF-MF-16058";
  public static final String PHRASE_KEY_CNTACT_TIMEOUT = "ADF-MF-16059";
  public static final String PHRASE_KEY_CNTACT_PENDING = "ADF-MF-16060";
  public static final String PHRASE_KEY_CNTACT_IOERROR = "ADF-MF-16061";
  public static final String PHRASE_KEY_CNTACT_NO_SUPPORT = "ADF-MF-16062";
  public static final String PHRASE_KEY_CNTACT_PERMISSION = "ADF-MF-16063";
  public static final String PHRASE_KEY_CNTACT_UNKNWN = "ADF-MF-16064";
  public static final String PHRASE_KEY_INVALID_CLASS = "ADF-MF-16066";
  public static final String PHRASE_KEY_INVALID_CLASS_MISSING_FNC = "ADF-MF-16067";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_MISSING = "ADF-MF-16068";
  public static final String PHRASE_KEY_INVALID_CLASS_VIEW_CLASS_CREATE_FAIL = "ADF-MF-16069";
  public static final String PHRASE_KEY_INVALID_VIEW_CONTOLLER_VIEW = "ADF-MF-16070";
  public static final String PHRASE_KEY_INVALID_CUSTOM_VIEW_TYPE = "ADF-MF-16071";
  public static final String PHRASE_KEY_UNDEFINED_CONNECTION_REF_BY_FEATURE = "ADF-MF-16072";
  public static final String PHRASE_KEY_NIL_URL_CONNECTION_REF_BY_FEATURE = "ADF-MF-16073";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_LOGIN_ERROR = "ADF-MF-16076";
  public static final String PHRASE_KEY_CONFIGURATION_FAILURE = "ADF-MF-16077";
  public static final String PHRASE_KEY_UIWEBVIEW_LOAD_FAILURE = "ADF-MF-16078";
  public static final String PHRASE_KEY_UIWEBVIEW_FAILED_TO_LOAD_FEATURE = "ADF-MF-16079";
  public static final String PHRASE_KEY_CONTACT_ADMIN = "ADF-MF-16080";
  public static final String PHRASE_KEY_LOGIN_SVR_NOT_AVAIL = "ADF-MF-16081";
  public static final String PHRASE_KEY_INVALID_UN_PW = "ADF-MF-16082";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN = "ADF-MF-16083";
  public static final String PHRASE_KEY_ACS_FAILED = "ADF-MF-16084";
  public static final String PHRASE_KEY_INVALID_ACS_CONFIGURATION = "ADF-MF-16085";
  public static final String PHRASE_KEY_SERVER_NOT_REACHABLE = "ADF-MF-16086";
  public static final String PHRASE_KEY_INVALID_UN_PW_PLEASE_TRY_AGAIN = "ADF-MF-16087";
  public static final String PHRASE_KEY_ACS_URL_IS_MISSING = "ADF-MF-16088";
  public static final String PHRASE_KEY_INVALID_UN_PW_SOME_FEATURES_NOT_AVAIL = "ADF-MF-16089";
  public static final String PHRASE_KEY_CHECK_FOR_CONFIGURATION_FAILED = "ADF-MF-16090";
  public static final String PHRASE_KEY_COULD_NOT_UPDATE_CONFIG = "ADF-MF-16091";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILESHELL_ERROR_DROPPED = "ADF-MF-16104";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_DEVICE_ACC_DSBLE = "ADF-MF-16105";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_URL_NOT_ALLOWED = "ADF-MF-16106";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_WHITELIST_ERROR = "ADF-MF-16107";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_SEND_WIDTH_HEIGHT_TO_JAVA = "ADF-MF-16108";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_NO_NETWORK_CHANGE_EVENTS = "ADF-MF-16109";
  public static final String PHRASE_KEY_ORACLEADFMFCONNECTIONS_DEFAULT_LOGIN_CONN_NOT_DEFINED = "ADF-MF-16110";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_MISSING_FAMILY = "ADF-MF-16111";
  public static final String PHRASE_KEY_ORACLEADFMFSKINS_ACTIVE_FAMILY_RETURNED_NO_SKIN = "ADF-MF-16112";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIVIEW_JSON_RESPONSE_NOT_SUPPORTED = "ADF-MF-16114";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_UIWEBVIEW_EXCEPTION_EXEC_CALLBACK = "ADF-MF-16117";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_APP_AUTH_ERROR = "ADF-MF-16118";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_FEATURE_AUTH_ERROR = "ADF-MF-16119";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_AUTH_ERROR_RETRY = "ADF-MF-16120";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_RETURN_ERROR = "ADF-MF-16121";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_FOR_CONN = "ADF-MF-16122";
  public static final String PHRASE_KEY_APP_LVL_LGN_FAILED_MISSING_AUTH_CNTXT = "ADF-MF-16123";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS = "ADF-MF-16124";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FILE_EXISTS_MSG = "ADF-MF-16125";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY = "ADF-MF-16126";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOCREATECACHEDIRECTORY_MSG = "ADF-MF-16127";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY = "ADF-MF-16128";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOTRAVERSECACHEDIRECTORY_MSG = "ADF-MF-16129";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE = "ADF-MF-16130";
  public static final String PHRASE_KEY_ASIDOWNLOADCACHE_FAILEDTOREMOVECACHEFILE_MSG = "ADF-MF-16131";
  public static final String PHRASE_KEY_CRASH_DUE_TO_CONFIG_DWNLD_FAIL = "ADF-MF-16132";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR = "ADF-MF-16135";
  public static final String PHRASE_KEY_APPLICATION_CONTROLLER_ERROR_FOLDER_DOES_NOT_EXIST = "ADF-MF-16136";
  public static final String PHRASE_KEY_COULD_NOT_LOAD_PROPERTIES_FILE = "ADF-MF-16137";
  public static final String PHRASE_KEY_ERROR_SERIALIZING_RETURN = "ADF-MF-16138";
  public static final String PHRASE_KEY_FEATURE_ID_NOT_DETERMINED = "ADF-MF-16139";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR = "ADF-MF-16140";
  public static final String PHRASE_KEY_CVM_STARUP_ERROR_WRONG_RETURN_TYPE = "ADF-MF-16141";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL = "ADF-MF-16155";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_AUTH_ERROR_GENERAL = "ADF-MF-16157";
  public static final String PHRASE_KEY_LOGIN_INTERNET_NOT_AVAIL = "ADF-MF-16158";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_THREAD_INIT_ERR = "ADF-MF-16159";
  public static final String PHRASE_KEY_ADFSHELLDELEGATOR_PAINT_MIRROR_ERR = "ADF-MF-16160";
  public static final String PHRASE_KEY_ADFAUTHENTICATIONCONTEXT_ACS_NOT_CONFIGED_CONSTR = "ADF-MF-16161";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME = "ADF-MF-16162";
  public static final String PHRASE_KEY_ERROR_IN_USERNAME_MESSAGE = "ADF-MF-16163";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG = "ADF-MF-16164";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_CONFIG_REASON = "ADF-MF-16165";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME = "ADF-MF-16166";
  public static final String PHRASE_KEY_AUTH_INVALID_MULTI_TENANT_NAME_REASON = "ADF-MF-16167";
  public static final String PHRASE_KEY_LOGIN_ATTEMPT = "ADF-MF-16168";
  public static final String PHRASE_KEY_APP_LOGIN_SUCCESS = "ADF-MF-16169";
  public static final String PHRASE_KEY_KSECATTRLEVEL_NOT_RETURNED = "ADF-MF-16170";
  public static final String PHRASE_KEY_UO_FETCHED = "ADF-MF-16171";
  public static final String PHRASE_KEY_AUTH_TEST_RETURN = "ADF-MF-16172";
  public static final String PHRASE_KEY_FEATURE_LOGIN_UNKNOWN_ERROR = "ADF-MF-16173";
  public static final String PHRASE_KEY_FEATURE_LOGIN_ATTEMPT_WITH_USER = "ADF-MF-16174";
  public static final String PHRASE_KEY_FEATURE_LOGOUT_ATTEMPT = "ADF-MF-16175";
  public static final String PHRASE_KEY_REMOTE_LOGIN_PULLS_UO = "ADF-MF-16176";
  public static final String PHRASE_KEY_AUTHENTICATION_SUCCESS = "ADF-MF-16177";
  public static final String PHRASE_KEY_ACS_RETURNS_UO = "ADF-MF-16178";
  public static final String PHRASE_KEY_ACS_RETURNS_ROLES_PRIV = "ADF-MF-16179";
  public static final String PHRASE_KEY_ACS_INVOKE_WITH_PAYLOAD = "ADF-MF-16180";
  public static final String PHRASE_KEY_LOGOUT_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16181";
  public static final String PHRASE_KEY_ISAUTH_PAUSEDFEATURE_NOT_FOUND = "ADF-MF-16182";
  public static final String PHRASE_KEY_ISAUTH_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16183";
  public static final String PHRASE_KEY_LOGIN_PAUSEDEAFURE_NOT_FOUND = "ADF-MF-16184";
  public static final String PHRASE_KEY_LOGIN_AUTHCONTEXT_NOT_FOUND = "ADF-MF-16185";
  public static final String PHRASE_KEY_AUTH_SECURITY_CONFIG_ERROR = "ADF-MF-16186";
  public static final String PHRASE_KEY_AUTH_DEFAULT_CONNDEF_MISSING_REASON = "ADF-MF-16187";
  public static final String PHRASE_KEY_AUTH_FEATURE_CONNDEF_MISSING_REASON = "ADF-MF-16188";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_LOGOUT_MESSAGE = "ADF-MF-16190";
  public static final String PHRASE_KEY_CONFIG_ERR_CNTACT_ADMIN_DETAIL = "ADF-MF-16191";
  public static final String PHRASE_KEY_CONFIG_ERR_CRED_STORE_KEY = "ADF-MF-16192";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_CREDENTIALS = "ADF-MF-16193";
  public static final String PHRASE_KEY_CONFIG_ERR_INTERNAL_BAD_COMPOSITE_CRED_KEY = "ADF-MF-16195";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_ACS_URL = "ADF-MF-16196";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGOUT_URL = "ADF-MF-16197";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_LOGIN_URL = "ADF-MF-16198";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_COOKIE = "ADF-MF-16199";
  public static final String PHRASE_KEY_CONFIG_ERR_CONFIG_BAD_TIMEOUT = "ADF-MF-16200";
  public static final String PHRASE_KEY_CONFIG_ERR_BAD_LOGIN_CONFIG = "ADF-MF-16201";
  public static final String PHRASE_KEY_CONFIG_ERR_INVALID_AUTH_URL_RESPONSE = "ADF-MF-16202";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String PHRASE_KEY_PREFIX_TO_MULTIPLE_URI = "ADF-MF-16210";
  public static final String PHRASE_KEY_URI_TO_MULTIPLE_PREFIXES = "ADF-MF-16211";

}
